### ISSUE TITLE
Display project's ETH address in Donate with Crypto flow

### ISSUE THREAD

**Issue by willyogo** [Giveth/giveth-2#100]
AC:
1. When a user attempts to donate crypto to a project, they see the project's ETH address (and QR code) (currently this is hardcoded)

**Comment by geleeroyale** [comment]
@brymut  Did you add this to automatically take the users address when creating a project, or is there no implementation yet to link created projects to the creator's address.

**Comment by brymut** [comment]
Nothing yet, was stuck since the only way to create projects was via the `addProjectSimple` mutation which doesn't have a way to link the address, but working on pulling the new fork locally to see what I can do now.

**Comment by mateodaza** [comment]
@CamiloTD will help updating the addProject mutation for it
