### ISSUE TITLE
Donate Fiat - Donate with Credit Card

### ISSUE THREAD

**Issue by willyogo** [Giveth/giveth-2#105]
![image](https://user-images.githubusercontent.com/26232238/93021777-e2b0d180-f5a1-11ea-9d9a-908a12777e0b.png)
(example mockup)

As a donor, I want to be able to donate to projects with my credit/debit card.

We are planning to use the [Stripe Connect SDK](https://stripe.com/connect) to streamline this (at least for MVP).

UX: When a user taps 'Donate' on the Select Amount screen, the Stripe Connect embedded payment widget pops up so the user can input their payment info and execute the transaction. Once the transaction is successfully completed, the widget closes and user is routed to the donation success page.

AC:
1. After a user inputs a valid amount (any positive number) and clicks ‘Donate’, the Stripe Payment Widget pops up to complete the transaction, and the background is blurred (see mockup)
2. *Users can clearly see the Stripe Processing Fee before confirming their donation. Hopefully this is handled in the Stripe Payment Widget but let’s confirm.
3. Users can donate with their debit/credit card
4. If a user successfully completes the transaction, they are redirected to the Donation Success Screen
5. If the user cancels the transaction/closes the Payment Widget, they are routed to the Select Amount to Donate screen and see an error message “Lorem ipsum” and a CTA to ‘Try Again’ or ‘Donate’

**Comment by papermache** [comment]
@mateodaza please pause this work.
