### ISSUE TITLE
Donate Fiat - Donation success screen

### ISSUE THREAD

**Issue by willyogo** [Giveth/giveth-2#106]
![image](https://user-images.githubusercontent.com/26232238/93021827-43400e80-f5a2-11ea-82f3-4f6eedfd454e.png)

[Mockup](https://www.figma.com/proto/FBqHg0UfeuaIueDEZG0tBS/Giveth-Design?node-id=1367%3A295&scaling=scale-down-width) 

As a user, I want to see confirmation that my donation was successful and be able to easily share my donation on social networks.

AC:
1. A ‘Donation Success Screen’ is added that users see after they successfully donate
2. Users can see the project they donated to and the amount donated
3. If a user clicks ‘Download Receipt,’ a PDF of their receipt is downloaded (relevant docs)
4. Users click a button to share a pre-written message on social media

**Comment by mateodaza** [comment]
What should happen when the user clicks on "view transaction details"? Maybe show the same information displayed in the PDF( #134 ) but directly on the screen?

**Comment by markoprljic** [comment]
@mateodaza That should open the transaction details on Etherscan. If it was a Fiat donation then there won't be the link to view transaction details, instead only show the Download receipt (which opens that PDF invoice that we created yesterday).
