### ISSUE TITLE
Donate Fiat - Connect Bank Account

### ISSUE THREAD

**Issue by willyogo** [Giveth/giveth-2#107]
As a project, I want to be able to connect my bank account to accept donations in fiat.

@markoprljic can you please provide the mockup for this?

AC:
1. A final, optional step is added to the project creation flow before a user confirms their details: Connect Bank Account. 
2. If a user clicks ‘Skip,’ they continue to the Confirm step.
3. If a user clicks ‘Connect Bank Account’ they are routed to the Connect Bank Account flow
4. If a user does not successfully connect their bank account, they are routed back to the Connect Bank Account step and see an error message “Error connecting bank account. Try again or skip for now.”
5. Once a user has successfully connected their bank account, they are routed to the Confirm step in the Project Creation Flow.
6. After Stripe connect user creation is finished, the Stripe auth token is saved and linked to the project.

**Comment by markoprljic** [comment]
@willyogo Yes, I will be working on this.

**Comment by markoprljic** [comment]
@willyogo Where can I learn about the Connect Bank Account flow? What happens after user confirms to connect bank account? How does the Stripe flow look like? Does the user has to have a Stripe account first in order to connect his bank account?

I was trying to find example flows and modals for this use case but all I found was checkout examples of modals and flows with stripe.

Please let me know on the above so that I can prepare a prototype. Thanks.

**Comment by markoprljic** [comment]
@willyogo I was searching for this kind of modal from Stripe but couldn't find their demo anywhere. Is this what we're integrating here? 
<img width="204" alt="Image 2020-09-15 at 11 39 43 am" src="https://user-images.githubusercontent.com/5704285/93194343-4412a500-f748-11ea-8b1c-bf04502888f3.png">

**Comment by willyogo** [comment]
@markoprljic I would like to pop up a widget like that, but also can't find any mention of it in their docs. The screenshot you posted is the right product too ([**Stripe Connect Express**](https://stripe.com/docs/connect/express-accounts)). 

This is the example Stripe provides on their website: https://rocketrides.io/
Rather than popping up an iframe, users are routed to Stripe's website in the middle of the Rocket Rides onboarding. I think customizing that example experience from the Stripe dashboard is the best we can do until we do a custom API integration.

web:
![image](https://user-images.githubusercontent.com/26232238/93293682-c8474580-f7a5-11ea-9d88-934afcdef443.png)
mobile:

These are all of the branding customization settings available: https://dashboard.stripe.com/test/settings/applications
![image](https://user-images.githubusercontent.com/26232238/93293952-7fdc5780-f7a6-11ea-8a87-bc681ade999a.png)

I just made an account and sent you an invite so you can check it out.

**Comment by markoprljic** [comment]
@willyogo Thanks for the responses! This is exactly what I needed. Moving on ;)

**Comment by markoprljic** [comment]
@willyogo added to the flow
<img width="436" alt="Image 2020-09-16 at 8 52 27 am" src="https://user-images.githubusercontent.com/5704285/93302291-053d2780-f7fa-11ea-8217-570b608bdb84.png">

Figma prototype updated as well https://www.figma.com/proto/FBqHg0UfeuaIueDEZG0tBS/Giveth-Design?node-id=976%3A158&viewport=-1077%2C-125%2C0.16454927623271942&scaling=min-zoom
