### ISSUE TITLE
Donate Fiat - Display fiat donation history

### ISSUE THREAD

**Issue by willyogo** [Giveth/giveth-2#108]
As a user, I want to see a history of donations on each project's profile.

[Mockup](https://www.figma.com/proto/FBqHg0UfeuaIueDEZG0tBS/Giveth-Design?node-id=2552%3A693&viewport=1493%2C-2854%2C0.5686643123626709&scaling=min-zoom)

![image](https://user-images.githubusercontent.com/26232238/94348972-d1ce7a00-fffd-11ea-9180-ca9719a56722.png)

AC:
1. A new tab is added to each project's profile, **Donations ([# of donations])**, which matches the mockup
2. Users can see the following data for each donation: Date, Donor, Currency, Amount
3. If a donation is ‘anonymous’, users see “Anonymous” as the donor’s name
4. If a donation is not anonymous, users see the donor’s name
5. Stretch: users can search for donations by donor name

**Comment by markoprljic** [comment]
Display fiat donation history - to which page does this refer to? Where should this be displayed?

We have a project details page with 3 sublinks 
<img width="686" alt="Image 2020-09-15 at 11 28 53 am" src="https://user-images.githubusercontent.com/5704285/93193057-ac608700-f746-11ea-9071-c3656ecdc6d5.png">

The **Donations tab** should display all donation history. Did you mean to include fiat donations on this page?

@willyogo

**Comment by willyogo** [comment]
Exactly @markoprljic 💯  hoping to show both fiat and crypto donations in the Donations tab on the project details page

**Comment by markoprljic** [comment]
Here's the preview of Donation page https://www.figma.com/proto/FBqHg0UfeuaIueDEZG0tBS/Giveth-Design?node-id=2552%3A693&viewport=1493%2C-2854%2C0.5686643123626709&scaling=min-zoom

**Comment by willyogo** [comment]
beautiful!

**Comment by jamespfarrell** [comment]
This is done
