### ISSUE TITLE
Error: $walletAddress of required type String not provided 

### ISSUE THREAD

**Issue by jamespfarrell** [Giveth/giveth-2#109]
This is on v2.giveth.io and staging.giveth.io.

I didn't dig to see who introduced this error, but essentially the cause is that walletAddress is out of scope:
 'login' in the torusProvider is being called and walletAddress is out of context. 

We need to bind the context to TorusProvider, or refactor this code somehow to get around this.

@mateodaza ,  @brymut  - are one of you working on this?

**Comment by mateodaza** [comment]
I'll check it out 👍
