### ISSUE TITLE
My Account

### ISSUE THREAD

**Issue by markoprljic** [Giveth/giveth-2#111]
**‘My Account’ MVP Feature Requirements:**

As a user, I want to be able to see a list of my projects.

- The cards for each of a user’s projects are displayed on /account
- At the end of the list of a user’s projects (or if a user has no projects), they see a card to ‘Add a Project’
- Empty state use “Add a Project”

As a user, I want to be able to update my donation address for each of my projects by pasting an address.

- The donation address for each project is displayed beneath the project card on /account alongside an edit button
- If a user clicks the edit project button, they can paste a new address and click ‘Save’
- If a user saves a new donation address, any user that attempts to donate to the project sees the updated donation address
- Add options for Project Settings (Edit donation address, change project details, save)

As a user, I want to see the total value of all assets in my account.

- The total value of all assets in a user’s ethereum account is displayed in $USD on /account
- Total number of My Projects (empty state “Add new Project”)
- Total number of Donations / over time?

Stretch: Users can select from any currency supported by app.tor.us.

As a user, I want to be able to copy my donation address.

- Users can click a copy button to copy their address to their clipboard
- After clicking copy, there is some visual feedback so the user knows their address has been successfully copied

Support 

User should be able to see the Support link in the dropdown
Click on the Support link should trigger the Discord widget and pop it up

Related document https://docs.google.com/document/d/1I0AnY2_bceQYkTSbsec1ly4KInvxHFIx0zLoNmp1kpM/edit

**Comment by markoprljic** [comment]
Related https://github.com/Giveth/giveth-2/issues/63

**Comment by markoprljic** [comment]
Design update:

	•	My account main page https://www.figma.com/proto/FBqHg0UfeuaIueDEZG0tBS/Giveth-Design?node-id=2649%3A0&viewport=886%2C2235%2C0.36186644434928894&scaling=min-zoom
	•	My Projects https://www.figma.com/proto/FBqHg0UfeuaIueDEZG0tBS/Giveth-Design?node-id=2662%3A4&viewport=886%2C2235%2C0.36186644434928894&scaling=min-zoom
	•	Edit Project https://www.figma.com/proto/FBqHg0UfeuaIueDEZG0tBS/Giveth-Design?node-id=2669%3A3&viewport=886%2C2235%2C0.36186644434928894&scaling=min-zoom
	•	My Donations https://www.figma.com/proto/FBqHg0UfeuaIueDEZG0tBS/Giveth-Design?node-id=2673%3A0&viewport=886%2C2235%2C0.36186644434928894&scaling=min-zoom

@willyogo

**Comment by brymut** [comment]
Initial PR on the 'My account main page' -> #140

**Comment by papermache** [comment]
@brymut will you work on this?

**Comment by papermache** [comment]
By Wednesday with @CamiloTD

**Comment by mateodaza** [comment]
We need to add some kind of warning to validate wallet (if not done previously) before showing the projects and allow edition
