### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by markoprljic** [Giveth/giveth-2#114]
How to crypto
How to sell crypto for cash
Marko to design classic FAQ dummy content

Here’s some content for FAQ https://giveth.io/donate

**Comment by markoprljic** [comment]
![FAQ](https://user-images.githubusercontent.com/5704285/96740465-2678d100-13c1-11eb-97ac-f55a96974fcf.png)

**Comment by papermache** [comment]
Up to six questions.

**Comment by papermache** [comment]
https://docs.google.com/document/d/1A_jzYO-m9LutopKDfaCUExKHXw6Q-S4zgwAy6lrmaTw/edit?usp=sharing

**Comment by geleeroyale** [comment]
I like your project ....
- Ledger link missing

Is Giveth recognized as an official charity?
- This is so outdated ... pls update this section @Danibelle 

---
All in all we need **much more content** here. Would love if everyone could come up with questions. If nobody else jumps in, I can answer them myself as well.

**Comment by Danibelle** [comment]
Thank you for the tag and reminder!! I am out today but back on this tomorrow thx

**Comment by Danibelle** [comment]
> https://docs.google.com/document/d/1A_jzYO-m9LutopKDfaCUExKHXw6Q-S4zgwAy6lrmaTw/edit?usp=sharing

I do not have access to this document, is it where I am to provide updated information for this issue?

**Comment by geleeroyale** [comment]
Any form of submitting content is accepted :)

Invited you again to contentful so you might also add/edit to the FAQ directly:
[Link to FAQ content on Contentful](https://app.contentful.com/spaces/movecrqtj4el/entries?id=FL4p91hyBwzyP0jQ&order.fieldId=updatedAt&order.direction=descending&contentTypeId=faqEntry&displayedFieldIds=contentType&displayedFieldIds=updatedAt&displayedFieldIds=author&folderId=LfwGGMplxb3zmcIF)

**Comment by Danibelle** [comment]
Can you please invite Forest, Ashley (WhyldWanderer) and Lauren to edit content @geleeroyale

**Comment by WhyldWanderer** [comment]
@Danibelle 
This has been slightly a confusing topic for me. We have been looking to add to FAQ documentation on many levels.

-general crypto faqs (eg. how to crypto)
-direct faqs about each of the giveth platforms where some questions are geared toward both of the platforms while others should be present only on one (eg. are my donations tax deductible?)
-then we have faqs geared towards giveth governance and tokenomic practices (eg. what is the difference between rep and cred?)

So I guess my question is.. are we collecting this data all in one central location to then be delegated to each section accordingly or does each topic have its own collection site? Has there already been a document started for all/each of these sections? I have added some suggestions in the staging document we are working on with Forest and Lauren but maybe there is a more easily accessible place where we can all collaborate on this?

**Comment by willyogo** [comment]
Next step: share a link to FAQs today for review

**Comment by WhyldWanderer** [comment]
Here is the link to the HackMD file
https://hackmd.io/wsqFFOyjTReIQtgtO9Dl_w

**Comment by geleeroyale** [comment]
@geleeroyale Review and textcheck. @GriffGreen reviews as well.

@WhyldWanderer have a one-on-one with me on Thursday.

**Comment by geleeroyale** [comment]
https://hackmd.io/wsqFFOyjTReIQtgtO9Dl_w

**Comment by geleeroyale** [comment]
Give Ashley's seat to Jeff
Kay imports to contentful
