### ISSUE TITLE
Join our Community

### ISSUE THREAD

**Issue by markoprljic** [Giveth/giveth-2#116]
Content https://giveth.io/join

**Comment by papermache** [comment]
@willyogo do we have designs for these?

**Comment by markoprljic** [comment]
> @willyogo do we have designs for these?

I'm on it.

**Comment by markoprljic** [comment]
Attached design of the Join our Community page.

![Join our Community](https://user-images.githubusercontent.com/5704285/96543477-becd6380-12a4-11eb-8ae4-ba0db4836fc4.png)


Figma preview here https://www.figma.com/proto/FBqHg0UfeuaIueDEZG0tBS/Giveth-Design?node-id=3440%3A0&viewport=-8844%2C2740%2C0.5612824559211731&scaling=min-zoom
