### ISSUE TITLE
Investigate the Torus - direct auth 

### ISSUE THREAD

**Issue by jamespfarrell** [Giveth/giveth-2#12]
Compare with the [iFrame version](https://giveth-torus-iframe.netlify.app), see what is missing with direct auth, and what we might want, and what effort it would take.

Once a user is signed in with Tarus, how will the donate button work from the api / ui perspective

**Comment by jamespfarrell** [comment]
Have this working and deployed

**Comment by GriffGreen** [comment]
This was awesome! Worked perfectly!

**Comment by aminlatifi** [comment]
Torus direct web sdk doesn't have web3 provider, so we need to use either our provider or using torus-embed.
If we continue to use direct auth, we have these options:
* Use infura api
* Setup our web3 gateway
* Implement metamask inpage provider like torus-embed
