### ISSUE TITLE
Write to topia backend after finishing create project

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/giveth-2#120]
Most functionality has been realized on the frontend, but the time has come to start writing created projects to the backend and retrieving it from there.

This specific functionality has been broken during the extension of "create project flow".

**Comment by aminlatifi** [comment]
It's a sample data is ready after project creation:
```{
  "projectName": "Name1",
  "projectAdmin": "Admin1",
  "projectDescription": "Description1\n",
  "projectCategory": {
    "nonprofit": [
      "on"
    ],
    "covid19": [
      "on"
    ],
    "technology": [],
    "other": []
  },
  "nonprofit": [
    "on"
  ],
  "covid19": [
    "on"
  ],
  "technology": [],
  "other": [],
  "projectImpactLocation": "New York, NY, USA",
  "projectImage": "blob:https://v2.giveth.io/6ade0b53-4045-43b1-8be9-482826eb95f8",
  "imageName": "38507369154_e6cae1_192sq.jpg"
}
```
@jamespfarrell There is no sign of organisation! should we remove that entity?
And other fields like title should be renamed maybe
The technical discussion is how to implement projectCategory. I liked to implement it as array of categories and index it using GIN feature of Postgres, but typeorm lacks such capability and we should create index by direct query
So the easiest way would be create different column for each category and index it! It works if categories are finite, and also consumes more space which would not be problem on MVP stage

**Comment by jamespfarrell** [comment]
@aminlatifi organisation is needed for whitelabel, and used to identify the different organisation (Gaia Giveth, Commonstack, Giveth etc), please don't remove. 

I would always make a new table for this kind of thing, can you elaborate on GIN?

**Comment by brymut** [comment]
Keeping track of this. Currently, I've only been able to add projects to backend using `AddProjectSimple` mutation (adds only project title and description) because its the only option avail atm that doesn't require creating a new org. I don't think we can create an organisation via Graphql currently if I'm not mistaken

**Comment by aminlatifi** [comment]
@brymut Thanks... can you just change image (imageUrl) field to have uploaded image data (base64 maybe) instead of just the path? Also it would be amazing if we agree on image size limit and implement it on both front and backend.

**Comment by brymut** [comment]
Absolutely, it might be a bug I'll try to fix. I remember the uploading to pinata and the link being sent to backend working may have introduced a bug later. Also, in the form a gallery of preselected images are provided, how can we handle that in the backend to represent that?

**Comment by aminlatifi** [comment]
@brymut Regarding uploading image to pinata, it was implemented before and tested. Find it in the UploadImage page (you should set api keys to work). But I guess at this stage we can pass image data and upload the files later in backend.
About preselected images, what do you think is the best solution? Maybe we can send path for those and at backend we know it. Or uploading them to ipfs and putting links there

**Comment by brymut** [comment]
Yes, I remember I got the pinata to work just think I broke something in the create project flow because it is no longer working on that end. As for the preselected ones, I think uploading to IPFS would work and then storing the links there would work.

**Comment by brymut** [comment]
Actually, I've double checked and the upload to Pinata is working for images you pick from your computer, its the preselected images that are not working.

**Comment by aminlatifi** [comment]
@brymut https://github.com/topiahq/impact-graph/pull/14 updates api and enables pushing project data to DB. Note how should pass categories. Also `topProjects` query supports categories after and projects view filter can be updated.

**Comment by brymut** [comment]
Thanks @aminlatifi . How do I create an organisation so that I can add projects to it?

**Comment by aminlatifi** [comment]
It's just an string entry now!

**Comment by brymut** [comment]
ahh,okay thanks

**Comment by aminlatifi** [comment]
> @brymut Regarding uploading image to pinata, it was implemented before and tested. Find it in the UploadImage page (you should set api keys to work). But I guess at this stage we can pass image data and upload the files later in backend.
> About preselected images, what do you think is the best solution? Maybe we can send path for those and at backend we know it. Or uploading them to ipfs and putting links there

#137
