### ISSUE TITLE
Use standard torus wallet instead of making a new one

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/giveth-2#123]

**Comment by aminlatifi** [comment]
So we would switch to torus-embed instead of torus-direct-web-sdk. @jamespfarrell as you wasn't in meeting you may want to add something.

**Comment by jamespfarrell** [comment]
@geleeroyale I'm confused, again this comes up, can you please clarify? @willyogo 
 If we are going to change anything, then I think we should switch to onboard.js only.

**Comment by geleeroyale** [comment]
The plan is to use the 'standard' torus wallet, so we can leverage settings and transfer functions from torus wallet app.

Onboard.js is still on the table but part of after MVP as the flow is not as nice as with pure torus

**Comment by jamespfarrell** [comment]
👌
