### ISSUE TITLE
Edit My Project

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/giveth-2#124]
BLOCKED - until create-project-flow is written and read from topia

Implement editing of existing projects

**Comment by geleeroyale** [comment]
This is done, correct? @mateodaza ?

**Comment by mateodaza** [comment]
Yes but there is a couple of bugs

- When the name is changed the slug of the project is not being updated
- We are not editing the location yet because we are not saving it so far

After both of those are solved we can close

**Comment by geleeroyale** [comment]
Edit location is the only missing part
