### ISSUE TITLE
Torus authentication popup

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-2#129]
We have been using message signed by user private key as user authenticator.
After migrating to torus standard wallet #123, we don't have user private key any more. To sign message by standard wallet a popup is shown and may not be our choice on UI/UX design @markoprljic. I have removed signing part yet in #128 to decide about it later. I believe we can defer it until user wants to create or modify some data at least.

I had a conversation with torus guys about a feature that needs popup just once:
![image](https://user-images.githubusercontent.com/5684607/95279527-c9790900-085f-11eb-99e7-d847af15cc2b.png)

**Comment by markoprljic** [comment]
Thanks for tagging me @aminlatifi and let me know if anything else needed after resolving this.
