### ISSUE TITLE
Deploy new instance of impact-graph from Giveth organization

### ISSUE THREAD

**Issue by willyogo** [Giveth/giveth-2#132]
AC:
1. https://github.com/Giveth/impact-graph is deployed
2. Giveth-2 env variables are updated to use the new impact graph instance

**Comment by geleeroyale** [comment]
Will do this next week together with @aminlatifi

**Comment by aminlatifi** [comment]
@jamespfarrell I appreciate if you help us on that

**Comment by aminlatifi** [comment]
CircleCi is configured, master branch will be deployed on server automatically.
@geleeroyale Can we close this issue?

**Comment by geleeroyale** [comment]
Thanks Amin - will close it after reverse proxy is set up
