### ISSUE TITLE
/join & /donation pages

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/giveth-2#133]
Once we have a release version, the plan is to assign giveth's main domain to it. Would be nice to not break any links, so we should have routes/pages for everything that is on the current website. This basically boils down to two pages. 

Explanation and recommendation:

**/join** - On v2 we will have a "contact us" page, which serves the function to contact Giveth with email (I understand the target demographic to be mainly "clients", that is donors and project owners . /join on the other hand is for really joining the Giveth community and therefore needsa to offer onboarding to community chat. My recommendation is to keep "contact" different from "join". In that case we would need a design from @markoprljic 

**/donate** - this should basically become a route to the Giveth project donation page that is part of MVP already.

**Comment by markoprljic** [comment]
Updated related issue https://github.com/giveth/giveth-2/issues/116#issuecomment-712596991
