### ISSUE TITLE
Prompt user to Sign up (Popup)

### ISSUE THREAD

**Issue by markoprljic** [Giveth/giveth-2#136]
If user is not registered or logged in and wanted to Create New project or take similar actions that require a user account, then pop up a message and inform user they need to Sign up first.

**Comment by markoprljic** [comment]
<img width="1045" alt="Image 2020-10-13 at 11 44 03 am" src="https://user-images.githubusercontent.com/5704285/95844645-6bf62800-0d49-11eb-91b5-a4a8ed335802.png">

Figma source https://www.figma.com/file/FBqHg0UfeuaIueDEZG0tBS/Giveth-Design?node-id=3161%3A0

@brymut

**Comment by aminlatifi** [comment]
In this pull request we set torus-embed (torus standard wallet) and I experimentally enabled sign message popup of torus after user sign in
