### ISSUE TITLE
Authentication mechanism 

### ISSUE THREAD

**Issue by papermache** [Giveth/giveth-2#147]
Should first design user entity and identification.

Organization should have some admin.

**Comment by aminlatifi** [comment]
In last conversation with @GriffGreen and @willyogo we decided to keep organization as a string field and show it, just that. Having separate domain for each organization is not in MVP scope.

**Comment by aminlatifi** [comment]
@jamespfarrell we had an authentication initially on impact-graph, but it has been disabled (lines were commented) to go fast on UI development. We aim to on board authentication at this step

**Comment by jamespfarrell** [comment]
Ok, will have a look

**Comment by GriffGreen** [comment]
@aminlatifi will tackle this, this week
