### ISSUE TITLE
Create project header template images

### ISSUE THREAD

**Issue by papermache** [Giveth/giveth-2#149]
Create banners and use as default library.

**Comment by markoprljic** [comment]
Here are the project header images. Updates are in the[ Figma as well.](https://www.figma.com/file/FBqHg0UfeuaIueDEZG0tBS/Giveth-Design?node-id=970%3A1)

![Project Image 1](https://user-images.githubusercontent.com/5704285/96773524-ee838500-13e4-11eb-9711-0ce0aaef2b9c.png)
![Project Image 2](https://user-images.githubusercontent.com/5704285/96773525-ef1c1b80-13e4-11eb-812c-30d09f37391f.png)
![Project Image 3](https://user-images.githubusercontent.com/5704285/96773526-efb4b200-13e4-11eb-8602-4341098c4a81.png)
![Project Image 4](https://user-images.githubusercontent.com/5704285/96773527-f04d4880-13e4-11eb-91f8-f33155681333.png)

**Comment by papermache** [comment]
Great job!
