### ISSUE TITLE
topiahq/impact-graph is the base repo on giveth/impact-graph

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-2#153]
The default base repo for giveth/impact-graph is topiahq/impact-graph. Devs always should change base repo to create pull request. It's annoying and will cause lots of mistake on creating pull request to topiahq one.
![image](https://user-images.githubusercontent.com/5684607/97431338-6430a900-192f-11eb-867c-06f6a78f04a9.png)

**Comment by geleeroyale** [comment]
How can I solve it - do you know? @aminlatifi

**Comment by aminlatifi** [comment]
> How can I solve it - do you know? @aminlatifi
> 
> (you have admin permissions on the repository now btw)

There are two approaches, first removing the repository and creating new one and upload the code again (not fork). By this way we will lose the issues and pull requests comments history.
The second way is to contact GitHub, I did it.

**Comment by papermache** [comment]
@aminlatifi  can you close this?

**Comment by papermache** [comment]
For Sunday.

**Comment by geleeroyale** [comment]
Last time I pulled from impact-graph I saw that this is still a problem. Should I just make a new fork and hook up everything again?

**Comment by aminlatifi** [comment]
It's done. If any one has an impact-graph fork in his repo before, should delete that one  fork this  again.
