### ISSUE TITLE
Internal Release for Feedback and Review

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-2#159]
I hope that we can have a week of internal testing where we can make some projects and practice donating before launching to the public.

**Comment by Danibelle** [comment]
followed by week of following up on issues from internal testing before launching to the public :)

**Comment by papermache** [comment]
Talk about this Wednesday.

**Comment by papermache** [comment]
Post up in Discord about staging.giveth.io then tag everyone. We will circle back around on Sunday.

**Comment by papermache** [comment]
*Happening now* @GriffGreen to review on Mainnet Wednesday.

**Comment by jamespfarrell** [comment]
For me this isn't actionable or assignable. We have and epic to track this, so I'm closing it
