### ISSUE TITLE
Project location state should be saved

### ISSUE THREAD

**Issue by jamespfarrell** [Giveth/giveth-2#162]
To repo:
Opened map and selected Berlin

Then opened and closed "This project has a global impact"
![image.png](https://images.zenhubusercontent.com/5807a7a095e42b6c5baabbd3/50e63c62-280f-4884-a43d-86735ee8eca2) 

Lost my previous 'Berlin' selection.
![image.png](https://images.zenhubusercontent.com/5807a7a095e42b6c5baabbd3/9aa023dd-33a4-4c15-ab84-ecb60014d508)

**Comment by geleeroyale** [comment]
note to self: try a different key

**Comment by geleeroyale** [comment]
solved by adding new key and making the env variable accesible to frontend
