### ISSUE TITLE
Hovering, icon should be a hand

### ISSUE THREAD

**Issue by jamespfarrell** [Giveth/giveth-2#164]
![image.png](https://images.zenhubusercontent.com/5807a7a095e42b6c5baabbd3/98096dd4-4073-481b-a78f-3993e6342c3d)

![image.png](https://images.zenhubusercontent.com/5807a7a095e42b6c5baabbd3/a649cf3a-e33a-4a89-8b1e-264b6b80f932)

**Comment by geleeroyale** [comment]
fixed!
