### ISSUE TITLE
Wallet verification Tasks

### ISSUE THREAD

**Issue by papermache** [Giveth/giveth-2#165]
Signing messages requires a private key. Verifying messages requires a public address. In this way, you can write an arbitrary message and generate a signature that could only have been created by a user with control of the private key for this address. Any user with the message, the public address and the signature can easily verify that only you could have created the signature. Messages are not stored on the blockchain. Instead, you must send these three text snippets (message, address and signature) to your intended recipient using another communication channel, such as email. 

To sign a message with a private key is to provide cryptographic proof that the message signed is coming from the person in control of the private key. For example, if you sign a message with the private key belonging to one of your Bitcoin addresses, anybody could tell that the owner of a certain Bitcoin address (you) was the one that wrote that message.
When we login using torus, everything happens at front-end side! To prove our backend that user has really the private key, we ask him to sign a message and verify he has a real torus wallet and not do spoofing!

If we don't ask him to verify wallet, some one may send mutation (modification) request to backend by falsifying data and claiming to be someone else!

**Comment by markoprljic** [comment]
Is this already implemented on the FE? I'm seeing wallet verification from Torus when I connect my account, that means it's already implemented? Do we need anything else here? Asking so that I know what the actual user flow is and design the missing pieces if required. Let me know, please.
