### ISSUE TITLE
SDG Impact direct fiat integration feasibility study

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-2#168]
Maxim messaged me and said:

SDG built their own payment gateway and is only one step further to transfer to crypto... could be better and cheaper than stripe anyways.

**Comment by willyogo** [comment]
This is the payment gateway SDG has integrated on their website for their projects to accept donations: https://donorbox.org/

It does look super cool (actually pretty similar to Giveth), and is something Giveth Foundation could use to accept donations, but unfortunately doesn't offer the marketplace functionality that Stripe, Dwolla, and Braintree offer to enable projects on our platform to connect their own bank account. 

Donorbox is actually powered by Stripe for credit card processing, and donors/orgs pay both the Stripe fee as well as an additional 1.5% platform fee charged by Donorbox.

I still love the idea of giving projects the ability to apply to be a component of SDG Impact Fund and accept tax deductible donations to SDG's bank account. But from what I've learned, Stripe, Dwolla, or Braintree seem like the best implementation for fiat donations, regardless of whether a project/org is part of SDG.

**Comment by mateodaza** [comment]
Yep, if we want to link the project's bank account directly, a payment infrastructure is needed. I'm optimistic for Dwolla, did you get in touch with them?

As an alternative for our mvp while we wait to clear that out, I'd like to discuss with Maxim how feasible it is to link a SDG fund directly for our projects, so we wouldn't need to set a bank account for each one in this early phase.

Btw, that recurring donations feature in Donorbox looks really interesting.

**Comment by willyogo** [comment]
+1

Re: Dwolla - I filled out the form on their website and a sales rep reached out with some questions and to set up a call. I responded to the q's and got an auto reply saying the rep is OOO until Monday, November 9th. I'm on vacation next week so should be able to speak with them and get confirmation 🤞

**Comment by Gaiaguardian** [comment]
> Yep, if we want to link the project's bank account directly, a payment infrastructure is needed. I'm optimistic for Dwolla, did you get in touch with them?
> 
> 
> 
> As an alternative for our mvp while we wait to clear that out, I'd like to discuss with Maxim how feasible it is to link a SDG fund directly for our projects, so we wouldn't need to set a bank account for each one in this early phase.
> 
> 
> 
> Btw, that recurring donations feature in Donorbox looks really interesting. 
> 
> 

I think this is how SDG is structured. The funds are directly funnelled through SDG, so therefore tax-deductable, they manage the funds through their backend. I think the best thing is to get on a line with Doug, their developer. I am happy to arrange a call, to clear all questions and see the feasibility of integrating their system.

**Comment by Danibelle** [comment]
Great who needs to be in that call, Mateo, Willy, Kay, Me.. ?

From SDG, Doug only or Bryan too? 

@Gaiaguardian please do find their availability and let's work together for the solution, this is critical path for MVP 👍

**Comment by mateodaza** [comment]
Count me in ⚡

**Comment by Gaiaguardian** [comment]
Great I got in touch with Doug now, waiting to see when he is available!

**Comment by Gaiaguardian** [comment]
btw Doug is just finalizing an integration push Bryan told me, they are keen. Might just take a little. I am pushing it...

**Comment by Gaiaguardian** [comment]
![Uploading 99909051...]

**Comment by Gaiaguardian** [comment]
![image](https://user-images.githubusercontent.com/71226702/99909056-ccaf4380-2cab-11eb-9987-0e9f16edb9af.png)

**Comment by Gaiaguardian** [comment]
Bryan told us he can hookup their stripe to our platform no problemo. He's def available anytime pretty much.

**Comment by mateodaza** [comment]
Oh! But I have a question, @willyogo If we make the annotation that the stripe account is being handled by the SDG fund, do you believe they'd have a problem and shut us down or take legal action? I think we must make that really clear on the TOS

**Comment by Gaiaguardian** [comment]
Let me know if I should schedule a call with Bryan! Much love!

**Comment by Gaiaguardian** [comment]
Hey,

@mateo this is Bryan`s reply: Nope.   They can’t shut us down-it’s a valid
use case

how does Friday morning work for you? Bryan is EST to keep in mind please ;)

Am So., 22. Nov. 2020 um 19:01 Uhr schrieb Mateo Daza <
notifications@github.com>:

**Comment by mateodaza** [comment]
Perfect! Can we do 10am EST and add @willyogo to it please 🙌🏼

**Comment by Gaiaguardian** [comment]
Confirmed :)

**Comment by Danibelle** [comment]
I will need to be there please too 🙏

**Comment by Gaiaguardian** [comment]
Great 10am est fr good for u?

**Comment by Gaiaguardian** [comment]
Would 9am EST be fine too, Bryan realized he had a family day planned, so
asked. Thx

**Comment by Gaiaguardian** [comment]
Hey Bryan can do next week too, i wont be there, but pass me ure number and
ill open a thread to arrange a time...

**Comment by mateodaza** [comment]
We are ready to do it right now if available 🚀

**Comment by Danibelle** [comment]
It sounds like we need to do this Monday due to the US holiday.
I haven't received confirmation yet.

**Comment by willyogo** [comment]
Monday 10 am EST sounds good! I had dm'd bryan on telegram this morning and he confirmed that works for him too.

@Gaiaguardian my number is 512-971-6733 for next time

thanks all!

**Comment by Danibelle** [comment]
Meeting Invite:
Bloom Network is inviting you to a scheduled Zoom meeting.

Topic: Giveth DAF Fiat<>Crypto Stripe Integration
Time: Nov 30, 2020 10:00 AM Eastern Time (US and Canada)

Join Zoom Meeting
https://us02web.zoom.us/j/88445461540?pwd=aGIyUjFJN2ZZNjZFd1pEL1RQenJPQT09

Meeting ID: 884 4546 1540
Passcode: 339259

**Comment by Gaiaguardian** [comment]
Great, will not be able to attend but will forward to bryan and confirm! :)

**Comment by Gaiaguardian** [comment]
10 am est 30.11. confirmed

**Comment by snappysnap** [comment]
Confirmed!  
a few notes:
- donorbox.org is not the SDGIF product (That is a 3rd party vendor we used as a stopgap).  We have our own being finalized.

Examples:
https://www.dropbox.com/s/2qbtopwn041bc5g/sdg_demo_1.mp4?dl=0

**Comment by Danibelle** [comment]
Follow up call this morning:
8a Mountain/9a Costa Rica/10a EST/4p CET:

Join Zoom Meeting
https://us02web.zoom.us/j/87892022887?pwd=b29ucmIzQmpyeHoxYUZmUTN4YWU2Zz09

Meeting ID: 878 9202 2887
Passcode: 813354

**Comment by willyogo** [comment]
Can we try again this week @snappysnap @Danibelle @mateodaza? The same time works for me any morning other than Monday (8a Mountain/9a Costa Rica/10a EST/4p CET)

**Comment by Gaiaguardian** [comment]
These dates are available to meet with Doug, pls let me know what works and ill arange and send out invite links
![image](https://user-images.githubusercontent.com/71226702/102424008-e5232d00-3fcf-11eb-8fe0-93464166eb8f.png)
![image](https://user-images.githubusercontent.com/71226702/102424023-e81e1d80-3fcf-11eb-8917-7bc62960715f.png)
