### ISSUE TITLE
Amazingly obvious roadmap and MVP feature list

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-2#169]
It would be incredibly impactful o have a really clear MVP roadmap and feature list that we can show to a donor and they understand our plan in 30 seconds.

**Comment by GriffGreen** [comment]
Willy said in the Community call he wants to take it on

**Comment by willyogo** [comment]
It's on!

**Comment by willyogo** [comment]
Will report back when the draft is up

**Comment by willyogo** [comment]
Draft doc is live: https://www.notion.so/giveth/Roadmap-5a154f91bf9a417ea31b2edbc925201a

Planning to review the format at the governance call on November 9th and then spend more time filling it out.

**Comment by GriffGreen** [comment]
Reviewed, LOVE IT, added some pieces :-D
