### ISSUE TITLE
Sort out @giveth.io email addresses for everybody

### ISSUE THREAD

**Issue by papermache** [Giveth/giveth-2#179]
Get EIN and contact Google for Nonprofits.

**Comment by geleeroyale** [comment]
I guess most want the convenience of google. While I use google docs i.e. extensively myself, I do not like it as much for organizations (especially ones that play with crypto). We will see how it goes, but we could bring email to those still needing a giveth.io address **today**. I would also like to know how this scales, my workflow would still stay cheap at dozens of users - also it is only email and not a big suite of things.

My proposed workflow is to just use a [migadu](https://www.migadu.com) account (unlimited mailboxes on all your domains - you actually pay with usage quota - this is great as most use giveth email address to be reachable).
