### ISSUE TITLE
Standardizing Dev Practices for New Developers

### ISSUE THREAD

**Issue by papermache** [Giveth/giveth-2#218]
This includes supporting docs and things like naming conventions etc.

**Comment by papermache** [comment]
For Thursday. Leave the responsiveness.

**Comment by papermache** [comment]
Include tests standardization.

**Comment by papermache** [comment]
After Mainnet code review.

**Comment by geleeroyale** [comment]
I would love have input on the skeleton structure - I opened an issue for that in the docs repo:

https://github.com/Giveth/giveth-docs/issues/1

**Comment by geleeroyale** [comment]
Currently the dev practices live here - https://docs.giveth.io/docs/dev-guidelines
