### ISSUE TITLE
[ENHANCE] server vs client side render for projects

### ISSUE THREAD

**Issue by mateodaza** [Giveth/giveth-2#228]
CONTEXT: For the projects to be server rendered they need to be ready from the build runtime so the Gatsby page is generated, if a user creates a project he wouldn't be able to see it instantly. The solution for this of course was to fetch them dynamically using the slug during runtime.

PROBLEM: I didn't find a way with Gatsby to split the logic to differentiate when a project needs to be fetched on the client and when it can be rendered from server. Currently the fetch is always happening client side in response to not being able of making this differentiation. 

As for this PR #227 I removed the [] brackets [syntax](https://www.gatsbyjs.com/docs/file-system-route-api/#syntax-client-only-routes) to try and handle it from the server but is useless as it's still making the retrieve on the client. I can move back to this way and embrace the CSR completely, which may be a more clean implementation but not optimal for what we look for.

NextJS handles it like [this](https://nextjs.org/docs/basic-features/pages#scenario-2-your-page-paths-depend-on-external-data) If anyone finds something like this over Gatsby, please refer it here and let's try it out.

**Comment by jamespfarrell** [comment]
Yeah this is something that I flagged as an issue with Gatsby from the beginning, and the key difference between NextJS and Gatsby (gatsby has no server, just static files, so no dynamic routes).

I didn't see realise this exact use case as a limitation, but there were others, such as a list of projects that belong to a logged in user. 

From the beginning we agreed that we would move to NextJS if needs be. I suggest we do our best for now, and review the situation on an ongoing basis.

**Comment by geleeroyale** [comment]
> Yeah this is something that I flagged as an issue with Gatsby from the beginning, and the key difference between NextJS and Gatsby (gatsby has no server, just static files, so no dynamic routes).
> 
> I didn't see realise this exact use case as a limitation, but there were others, such as a list of projects that belong to a logged in user.
> 
> From the beginning we agreed that we would move to NextJS if needs be. I suggest we do our best for now, and review the situation on an ongoing basis.
> 
> A rebuild could be triggered upon adding the project, and we can show it to them client side in the first case?

I want to note that triggering a rebuild currently would take a couple of minutes (which have to be paid) - this might be a **very expensive solution**

**Comment by geleeroyale** [comment]
For now we resolved this issue into a **working** state. Mateo is not too happy however because now we purely render on the client side. This would become a topic when we look at a recode for NextJS.
