### ISSUE TITLE
Nonprofit badge should appear only for organizations that have such designation

### ISSUE THREAD

**Issue by papermache** [Giveth/giveth-2#232]
It doesn't appear Barranquilla Carnival has 501(c)3 status or the local equivalent. We should ask for it during project registration but not make it mandatory.

![image.png](https://images.zenhubusercontent.com/5f728ac74ad324429e195fec/26c9d6bd-7954-49a2-94be-280739773ccb)

**Comment by markoprljic** [comment]
This is the category of the project on Giveth, not the legal entity of that particular project. Is that what you meant?

**Comment by papermache** [comment]
It could be clearer to differentiate the category from the legal entity. I suspect actual registered nonprofits will want to use this in which case we should have a way for them to prove their status.

**Comment by markoprljic** [comment]
> It could be clearer to differentiate the category from the legal entity. I suspect actual registered nonprofits will want to use this in which case we should have a way for them to prove their status.

Hmm.. in that case, we should allow every project to define their legal entity category. Is this information critical for users to know when they're donating?

**Comment by jamespfarrell** [comment]
@markoprljic can you make a call on whether we can close this
