### ISSUE TITLE
What does Support do?

### ISSUE THREAD

**Issue by papermache** [Giveth/giveth-2#233]
Do we have functionality planned or is it just an email address?

**Comment by papermache** [comment]
Mouse over displays a tooltip links to Discord.

**Comment by willyogo** [comment]
Here's an invite link to the new #support channel in Giveth Discord: https://discord.gg/JYNBDuFUpG

* Grants temporary membership
* Never expires
* Unlimited use

AC:
1. 'Support' links to https://discord.gg/JYNBDuFUpG in a new browser tab

**Comment by geleeroyale** [comment]
The solution I tried to implement experimentally for reference: https://widgetbot.io/
