### ISSUE TITLE
Create Project Yields Loading Page and not Confirmation Page

### ISSUE THREAD

**Issue by papermache** [Giveth/giveth-2#234]
Navigate the steps to create a project and there's no confirmation page just a loading page. Unless that functionality isn't ready yet and the projects are just hard coded?

![image.png](https://images.zenhubusercontent.com/5f728ac74ad324429e195fec/84a4583c-0c34-4cc3-b70d-29d32a459466)

**Comment by mateodaza** [comment]
This is the high five view, for some reason it got stuck. Is not hardcoded. Will check it out 👍🏼

**Comment by papermache** [comment]
See #242

**Comment by geleeroyale** [comment]
@mateodaza Put blur with loader here as well

**Comment by WhyldWanderer** [comment]
fixed.. DONE! ✔💖✨
