### ISSUE TITLE
White label Giveth Dapp

### ISSUE THREAD

**Issue by jamespfarrell** [Giveth/giveth-2#235]
The Giveth Dapp should be white labelled so that it can be used by other organisations.

Minimal viable white labelling has been done. 

Process for deploying a new organsation:

1) Logo should be placed in the images folder, and code updated in src/components/Logo.js
2) New css object with styles added to src/gatsby-plugin-theme-ui/sites folder, and code added to src/gatsby-plugin-theme-ui/index.js
3) Add new meta data to ./siteMetaData.js

For the CO2ken label, I have deployed a new version of impact-graph, so as to keep the projects in a separate database. Impact-graph was originally designed to hold projects for any number of websites though, this would allow for any syndication of projects across fund raising websites.

We are currently researching a way to deploy contract from projects instead of using a database, and using the The Graph as middleware, and this may end up being the way in future.

**Comment by Danibelle** [comment]
Amazing work James!

Giveth 2 MVP could well launch as White Label Ready?

**Comment by jamespfarrell** [comment]
Yeah I'm pretty close already... I could merge it tomorrow most likely....

**Comment by jamespfarrell** [comment]
The basic version is live now
