### ISSUE TITLE
UI Audit - Dec 8, 2020

### ISSUE THREAD

**Issue by markoprljic** [Giveth/giveth-2#243]
I reviewed the whole site http://staging.giveth.io/ and found a number of UI inconsistencies with the original design. 
Attached is a document with a complete list of items that should be fixed. These are not blockers and do not prevent a user from completing an action, but they do have an impact on the experience. Whenever it will be possible to address these and make required fixes I'd appreciate it, and our users would also appreciate it :) Thanks!

https://docs.google.com/document/d/1Zd1x29s3z9U78sJuGkQ45A8nF-45O8ZS8RpXbB63P2o/edit?usp=sharing

**Comment by papermache** [comment]
"Join the Future of Giving" button leads to old Giveth site and design inconsistencies.

![image](https://user-images.githubusercontent.com/2126012/101558884-e6c87180-398d-11eb-870f-3765364289ec.png)

**Comment by papermache** [comment]
For Sunday.

**Comment by geleeroyale** [comment]
@geleeroyale Please review
