### ISSUE TITLE
Prepare a List of Categories for projects

### ISSUE THREAD

**Issue by markoprljic** [Giveth/giveth-2#246]
We need a complete list of project categories to be listed in the Project Creation Flow. 
![Image 2020-12-09 at 4.29.22 pm.png](https://images.zenhubusercontent.com/5cc090818b624e26c3734d75/789d6fc8-2269-4cac-ae0a-660adac7131d)

**Comment by papermache** [comment]
@papermache For Sunday.

**Comment by geleeroyale** [comment]
Take out "Non Profit"

Add SDGs

**Comment by geleeroyale** [comment]
Working Spreadsheet for Categories

https://docs.google.com/spreadsheets/d/1wNUlY49XwA-QNYw9EX9utIUQZ9gAc_7DJSAOHK9zxJM/edit?usp=sharing
