### ISSUE TITLE
Add the Network indicator in the main nav

### ISSUE THREAD

**Issue by markoprljic** [Giveth/giveth-2#248]
User needs to see what network they're currently on.
If user is on wrong network, prompt user to switch the network.

**Comment by markoprljic** [comment]
Added the Network indicator in the Dropdown in the main menu.
<img width="490" alt="Image 2020-12-09 at 5 35 10 pm" src="https://user-images.githubusercontent.com/5704285/101658122-feaefc80-3a44-11eb-8e4f-f686e5d353af.png">

If we detect that user is currently on the wrong network we should prompt to switch to the correct network. 
<img width="926" alt="Image 2020-12-09 at 5 52 44 pm" src="https://user-images.githubusercontent.com/5704285/101660372-636b5680-3a47-11eb-9619-2a5823e2ec33.png">

**Comment by geleeroyale** [comment]
Should be in next sprint
