### ISSUE TITLE
some create.js references are undefined

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/giveth-2#253]
`fetch`. `File` are referenced but neither are declared or imported in `create.js`

**Comment by geleeroyale** [comment]
Was this added by you @jamespfarrell ? We are looking for the root purpose of adding this in and a way to fix it.

**Comment by jamespfarrell** [comment]
Hey @geleeroyale fetch exists automatically in the browser, and not in nodejs. 
For this reason node-fetch or isomorphic fetch are often used for NodeJs.

If this is causing an issue, I suggest we move to axios which we are using in other places.

**Comment by geleeroyale** [comment]
Ok - thanks for the info. I am not aware of any bugs caused by this - was trying to clear some warnings when I stumbled upon this.
