### ISSUE TITLE
Calculating Fiat amount of Crypto Donation

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/giveth-2#255]
Use solution that is used by Giveth1 - almost done, currently in testing.

EDIT - We should also use a whitelist for tokens that support price calculation (anything can be donated, but not everything would be exchanged to USD)

**Comment by geleeroyale** [comment]
Amin is working on this for Giveth1 as well. Basically done as an API to use but need to secure access.

**Comment by geleeroyale** [comment]
We should add new env variable (static password) to secure API endpoint from client side. Amin will add password and tell us when we are able to call the API.

**Comment by jamespfarrell** [comment]
https://feathers.beta.giveth.io/conversionRates?txHash=0xf1d564c9890cd8f80455d761ee4ea1e69829f777bd4b0f127fa7ada6d0e8df32&from=PAN&isHome=true

**Comment by jamespfarrell** [comment]
This is deployed, so I'm closing

**Comment by jamespfarrell** [comment]
@aminlatifi still wants to add security to this, so I think it's still in progress actually.

**Comment by geleeroyale** [comment]
Going for now without security
