### ISSUE TITLE
Make entire project card clickable and route to project details

### ISSUE THREAD

**Issue by willyogo** [Giveth/giveth-2#256]
The whole project card should be link to project details, including the 'Learn more' text. Currently only the 'Learn More' text links to project details.

![image.png](https://images.zenhubusercontent.com/5a15c91b8a75884b90887d2e/44d90db1-d695-4234-918d-2e426aaf0328)

AC:
1. The project card matches the above mockup
2. When a user clicks anywhere on the project card besides the 'Donate' CTA, they are routed to that project's details

- This issue came from @markoprljic's recommendation in the [UX audit report on December 2nd 2020](https://github.com/Giveth/giveth-2/issues/222#issuecomment-740575291)

**Comment by geleeroyale** [comment]
For now - remove givers and donations, remove padding, try switching donate and learn more, try experimenting with button width

**Comment by geleeroyale** [comment]
- [ ] Collect transactions in database
- [ ] Fiat price conversion from Giveth1
