### ISSUE TITLE
Banner image on Project card is squeezed

### ISSUE THREAD

**Issue by markoprljic** [Giveth/giveth-2#261]
I uploaded an image of 1140 × 395 px and it shows squeezed in Project Card.

![Image 2020-12-16 at 5.40.49 pm.png](https://images.zenhubusercontent.com/5cc090818b624e26c3734d75/1bfa002f-4d79-4a05-a4b0-61e47f24df9d)

**Comment by geleeroyale** [comment]
Review this with a couple of weird image sizes

**Comment by laurenluz** [comment]
Tried this with image size 1140 x 384 px...

In the project banner, the image is not squeezed, but would probably look better in general if it were centered, rather that left justified.

Maybe we could give the user the option to edit how the image appears in the project banner? 

The project I'm referring is the one on the right:

![image](https://user-images.githubusercontent.com/75490971/104358656-5e7d4500-54d4-11eb-85e9-5add6b836256.png)
