### ISSUE TITLE
When donating if wallet doesn't have enough funds add custom designed popup

### ISSUE THREAD

**Issue by markoprljic** [Giveth/giveth-2#264]
Instead of browser default info popup we should use one of our custom modals to show this information.|

![Image 2020-12-16 at 5.52.50 pm.png](https://images.zenhubusercontent.com/5cc090818b624e26c3734d75/eb69161e-9c91-4613-96e2-87e73ef42d4c)

**Comment by geleeroyale** [comment]
Message is from onboard.js

Maybe we can customize it somehow?

**Comment by markoprljic** [comment]
Maybe something like this. 
<img width="587" alt="Image 2021-01-20 at 1 33 01 pm" src="https://user-images.githubusercontent.com/5704285/105175326-0a9ddc00-5b24-11eb-9082-0e71b6b5f557.png">

**Comment by divine-comedian** [comment]
![image](https://user-images.githubusercontent.com/67759413/113509438-91f3cc80-9523-11eb-9a58-e055d7cf32ea.png)
