### ISSUE TITLE
Make the Donate button bigger

### ISSUE THREAD

**Issue by markoprljic** [Giveth/giveth-2#267]
On the Homepage in the header make the Donate button bigger! Please :)
Right now it looks that the same button on the project cards is used in the header.

![Image 2020-12-16 at 6.11.52 pm.png](https://images.zenhubusercontent.com/5cc090818b624e26c3734d75/7140954c-2d3e-4c55-a0f1-cf336d4da076)

**Comment by geleeroyale** [comment]
@markoprljic Do you like how it looks now?

**Comment by markoprljic** [comment]
Yes it's good.

**Comment by WhyldWanderer** [comment]
This one is DONE! ^_^
