### ISSUE TITLE
Giveth 2 Launch and move to Giveth.io Plan

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-2#273]
## 📋 Anything to add?
From our meeting of Dec 13th, we know we won't launch in 2020.. so.. When Mainnet is indeed the question..
From internal testing to external testing to a planned and celebrated launch, strategy needed.

## ⏰ Urgency/Deadline/Blockers?
Blog posts and social media announcements, past contributor communications - giving advance notice and building up to launch..

## ❓ Why is it important?
Because a successful launch gets us to the moon.

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by geleeroyale** [comment]
- [ ] Deployed on mainnet
- [ ] Prepare move to giveth.io
- [ ] Move

**Comment by Danibelle** [comment]
Narrative needs to include an announcement / post about Giveth launching G2 and it now being found at giveth.io . plus where to find Giveth 1 and other subdomain details..

**Comment by geleeroyale** [comment]
Move planned for 24th Jan 2021
