### ISSUE TITLE
What non-dev deliverables are needed for Giveth 2 Launch?

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-2#274]
## 📋 Anything to add?
Dev guides, user guides, intro videos or screen share demos..

## ⏰ Urgency/Deadline/Blockers?
This can come hand in hand with internal testing..

## ❓ Why is it important?
 A good clean launch has other dependencies besides the dapp functionality.. usability and clear communication

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by geleeroyale** [comment]
Please open issues concerning communication in giveth-planning
