### ISSUE TITLE
Update URLs in the 'How to write a good project description' modal

### ISSUE THREAD

**Issue by willyogo** [Giveth/giveth-2#275]
AC:
- [x]  Copy is updated from "How to write a good project description" to "How to write a great project description"
- [x]  Copy is updated from "See how others have done it." to "See how others have done it:"
- [x]  When a user clicks 'Browse examples', https://v2.giveth.io/projects opens in a new tab
- [x]  Copy is updated from "Want to learn more? Read our blog post tutorial" to "Read this blog post tutorial" 
- [x]  When a user clicks "Read this blog post tutorial", https://knowhow.ncvo.org.uk/how-to/how-to-write-an-overview-of-a-nonprofit-organization# opens in a new tab

**Comment by jamespfarrell** [comment]
@willyogo

> When a user clicks 'Browse examples', https://v2.giveth.io/projects opens in a new tab

We agreed with Marko today that usability best practices are for users to control the opening of tabs.

**Comment by laurenluz** [comment]
1. Still says "good" not "great"
2. Still say "." not ":"
3. "Browse examples" sends me back to staging.giveth.io in the same tab
4. Still unchanged
5. Still unchanged, "read this blog post tutorial" sends the user back to staging.giveth.io in the same tab

**Comment by laurenluz** [comment]
1. It says "great" in the popup, but says "good" in the main page... see screenshot:
![image](https://user-images.githubusercontent.com/75490971/104475648-f3d81200-5584-11eb-87d8-0c7ed5e2e865.png)

2. It says "see how others have done it -" not "see how others have done it:" The hyphen is a bit awkward, I think
3. Fixed!
4. Fixed!
5. Fixed!
