### ISSUE TITLE
In Brave Torus has a cookies requirement... How do you do that!?

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-2#276]
## 📋 Anything to add?

The pop up takes you to this site: https://docs.tor.us/torus-wallet/faq-1/users#cookies It seems encouraging but it takes 3

## ⏰ Urgency/Deadline/Blockers?

Low Pri!

## ❓ Why is it important?

Friction

## 🎉 Subtasks

- [ ] Have someone smarter than me figure it out
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

## 🔗 Work doc - inspirational links

![Screen Shot 2020-12-20 at 11 49 41 AM](https://user-images.githubusercontent.com/14945613/102719033-cbddf180-42eb-11eb-9ef2-3100c0d74464.png)

**Comment by mateodaza** [comment]
oh, torus is using third party cookies when using google/twitter/facebook etc. 

According to this [forum](https://support.brave.com/hc/en-us/articles/360050634931-How-Do-I-Manage-Cookies-In-Brave-) it can be solved by a couple of configurations. Maybe we could indicate this on the FAQ section?

**Comment by geleeroyale** [comment]
Solve this by pointing out above workaround to documentation - FAQ, docs
