### ISSUE TITLE
🐞 Error creating or editing project when description is longer than a sentence (Argument validation error)

### ISSUE THREAD

**Issue by willyogo** [Giveth/giveth-2#277]
I'm running into the same error when I try to create a project with a long description, or if I try to edit my project description and make it longer. I'm able to consistently create projects with one word descriptions, and similarly can successfully edit projects as long as the description is short. However, as soon as I try to update the description to a few sentences (see recording) I experience `Argument validation error `

Steps to repro:
1. Create a project with a paragraph long description. (Join us in building the future of giving! In addition to maintaining beta.giveth.io, we’re actively developing v2.giveth.io, the free, open-source, and decentralized application for peer-to-peer donations. Donations such as yours are our primary source of funding and are deeply appreciated!)
2. When that fails, try again with a one word description
2. Edit the project, and try to update the description to the paragraph

Expected result:
1. When user clicks 'save' project is launched/updated successfully

Actual result:
1. When a user clicks 'save' their project is not launched/updated

AC:
1. As long as all inputs are valid, when a user clicks 'Save' their project is updated successfully

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/26232238/102722151-70e0d600-42bc-11eb-964c-0876cde74b81.gif)

**Comment by mateodaza** [comment]
I noticed in the impact-graph there is a limit of 255 characters for the description. I guess we should make it longer, what's a good length size?

**Comment by geleeroyale** [comment]
In the frontend a limit for 2000 characters is denoted. We should make it consistent for the backend

**Comment by mateodaza** [comment]
Gotcha, will change that on the backend 👍🏼

**Comment by mateodaza** [comment]
This is done
