### ISSUE TITLE
Edit Project Button takes me to Create a Project

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-2#278]
## 📋 Anything to add?
First time creating a project I never saw how to put in a picture and it created with one that is not relevant at all to my projecft..
Project URL: https://v2.giveth.io/project/The-DBC
I went back to project:
![image](https://user-images.githubusercontent.com/39466970/102724133-fff8e880-42d2-11eb-9817-e33b67682f8c.png)
 and clicked the EDIT button, it brought me here:
![image](https://user-images.githubusercontent.com/39466970/102724140-1141f500-42d3-11eb-9e1a-a283dd26d13c.png)

## ⏰ Urgency/Deadline/Blockers?
Showstopper IMO

## ❓ Why is it important?
Project owners will frequently need to edit after creating and seeing what needs to be changed.

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by Danibelle** [comment]
@WhyldWanderer please test this works now!

**Comment by WhyldWanderer** [comment]
Fixed!!

**Comment by Danibelle** [comment]
Woohoo thanks, closing issue!
