### ISSUE TITLE
Add meta tag to site

### ISSUE THREAD

**Issue by willyogo** [Giveth/giveth-2#279]
Add meta tag info for google search results and sharing

![image.png](https://images.zenhubusercontent.com/5a15c91b8a75884b90887d2e/1486f6e1-71a2-4b02-a63b-37e0b69cd1b0)

**Comment by jamespfarrell** [comment]
@willyogo Can you please provide the text that we should use? Or should we change it to what's in the screenshot above?

**Comment by GriffGreen** [comment]
It should be also for the Project as well... 

For the Project:

Donate to "TITLE"

For Giveth:
Change it to:
"Building the Future of Giving #Blockchain4Good"
