### ISSUE TITLE
Refactor Create Project button to element in header

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/giveth-2#28]
There is a new dedicated element to create a project:

![image](https://user-images.githubusercontent.com/317685/85205949-eaecce00-b31e-11ea-96f9-2007e9299205.png)

Comment from Marco(figma): This is the main CTA and should always be visible. If user is not signed in we will prompt to sign in befire continuing with project creation.

**Comment by geleeroyale** [comment]
fixed in #34

**Comment by willyogo** [comment]
LGTM!
