### ISSUE TITLE
Improve UX of 'Select impact location' in project creation flow

### ISSUE THREAD

**Issue by willyogo** [Giveth/giveth-2#280]
The UX for selecting a location is not as clear as it could be.

I think the most confusing parts are
1. knowing to click 'Select Location' 
2. knowing how to select location (the only button to click is 'close')

As a quick improvement, I propose taking the search and map components out of the modal and embedding them right on the page (see attached mockup).

Current UX:
![image.png](https://images.zenhubusercontent.com/5a15c91b8a75884b90887d2e/65c65844-294b-4685-a480-d0b2d0831602)
![image.png](https://images.zenhubusercontent.com/5a15c91b8a75884b90887d2e/3567db3d-c352-431e-8b10-f3de283c99fd)

Proposed UX:
![image.png](https://images.zenhubusercontent.com/5a15c91b8a75884b90887d2e/866201b5-ca7f-4f1e-bef7-e23d3eab8143)

**Comment by willyogo** [comment]
@markoprljic what do you think of this proposed ux change?

**Comment by markoprljic** [comment]
Yes! That is good.

**Comment by geleeroyale** [comment]
* also needs to be on edit project
