### ISSUE TITLE
Display 4 decimals of precision on donation total in donations table

### ISSUE THREAD

**Issue by willyogo** [Giveth/giveth-2#281]
Currently the donation total on the project view only displays up to 2 decimals. We want to display up to 4 decimals of precision instead.

![image.png](https://images.zenhubusercontent.com/5a15c91b8a75884b90887d2e/5ba31878-2316-4353-b593-922813c07b85)

AC:
1. Donation total on project view displays up to 4 decimals of precision

**Comment by HarshadVaghasiya** [comment]
Hi
