### ISSUE TITLE
Generate jdenticon avatar if no avatar is available

### ISSUE THREAD

**Issue by willyogo** [Giveth/giveth-2#282]
Currently a cute puppy image is being used as the avatar if no avatar is available. Instead, let's use the user's address to generate a unique jdenticon.

example: https://jdenticon.com/#icon-0xc770eefad204b5180d

AC:
1. if no avatar is available, a unique jdenticon is generated and used

![image](https://user-images.githubusercontent.com/26232238/102727958-4b68c200-42e6-11eb-91ff-0a66a0b8900a.png)

**Comment by mateodaza** [comment]
Love it, totally will do!
