### ISSUE TITLE
v2 mobile homepage text overlap

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-2#283]
Thebtext overlaps on thr v2 mobile homepage.

## 📋 Anything to add?
![Screenshot_20201221-123024_Chrome](https://user-images.githubusercontent.com/74267818/102810848-4b65d200-4379-11eb-924f-959aeb0d6ca0.jpg)

## ❓ Why is it important?
To keep it clear and concise for users

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by geleeroyale** [comment]
Thanks for testing! Filing this as UI style issue and assign myself. Please test staging.giveth.io before v2.giveth.io for the moment.
