### ISSUE TITLE
Add meta to projects pages

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/giveth-2#292]
Project pages should have their own meta tags.

**Comment by mateodaza** [comment]
As /project and /donate routes are currently rendered client side, the slug won't appear on the meta title assigned in the SEO, the helmet meta updates by the moment slug and content is fetched but the preview cards won't display these changes. It's needed a server render for this to work. Relates to #228. For now I'm leaving an standard message for both cases like this:

<img width="603" alt="Screen Shot 2021-01-18 at 5 34 11 PM" src="https://user-images.githubusercontent.com/18689480/104968324-7b71b680-59b3-11eb-9846-ff9b10ae7b81.png">
<img width="609" alt="Screen Shot 2021-01-18 at 5 34 46 PM" src="https://user-images.githubusercontent.com/18689480/104968328-7dd41080-59b3-11eb-8fe5-0f7ebca6b846.png">

The texts are open for modification**

This issue also talks about what's going on https://github.com/gatsbyjs/gatsby/issues/25171

**Comment by divine-comedian** [comment]
@mateodaza  If we're not able to easily change the meta tag  for projects should we icebox this?

**Comment by willyogo** [comment]
Update: this requires more investigation into server-side rendering. Deferred from MVP

**Comment by mateodaza** [comment]
I still need to find a way to display base64 images but this is working for now

**Comment by divine-comedian** [comment]
looks hella slick! nice work mateo, tested on brave w/ google keep

![image](https://user-images.githubusercontent.com/67759413/111475281-4f4c8a80-8703-11eb-9518-c53836481008.png)
