### ISSUE TITLE
Post donation page could be more of a celebration, where is the confetti?

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-2#295]
<img width="590" alt="Screen Shot 2021-01-03 at 11 16 40 AM" src="https://user-images.githubusercontent.com/14945613/103483465-aff84680-4de7-11eb-8bae-cca309fd5490.png">

The text over the background looks a little weird and I would love some animations or something that screams: You are a Hero! Fuck yeah, thank you! Let's party!!!

**Comment by mateodaza** [comment]
This is dark because v2 is not up to date btw

@markoprljic if you are up for some experimentation with [lottie](https://github.com/chenqingspring/react-lottie) I'm up for it! 😃

**Comment by markoprljic** [comment]
> This is dark because v2 is not up to date btw
> 
> @markoprljic if you are up for some experimentation with [lottie](https://github.com/chenqingspring/react-lottie) I'm up for it! 😃

Oh YES! :)

**Comment by jamespfarrell** [comment]
@mateodaza are you waiting anything from @markoprljic on this, or you will do something next?

**Comment by mateodaza** [comment]
Yes, waiting. No rush on it, as soon as Marko have some animation for it, I'll give life to this 😄

**Comment by markoprljic** [comment]
@mateodaza I was thinking of using the confetti animation above the title https://lottiefiles.com/14162-taras-chenenko-succcess-confetti

**Comment by markoprljic** [comment]
Here's a quick mockup, but live will look much better 
<img width="687" alt="Image 2021-01-14 at 2 10 05 pm" src="https://user-images.githubusercontent.com/5704285/104595030-493e1d00-5672-11eb-86be-8e5d69d90dd5.png">

**Comment by mateodaza** [comment]
I ended up using this that has transparent background https://lottiefiles.com/13982-testing 🎊 

Btw, are these cool to use for free or should we put the copyrights somewhere?

**Comment by markoprljic** [comment]
Cool.

We're free to use. We can state somewhere on about page small that we're
using lottie.

**Comment by laurenluz** [comment]
This works just fine, looks super cute too. I'd call this done.
![image](https://user-images.githubusercontent.com/75490971/104848212-8dffc900-58a9-11eb-956d-a134151be8a0.png)

**Comment by markoprljic** [comment]
Don't think we need to add the cred on this page.
