### ISSUE TITLE
When we verify the person's account to make a project, the secret is "our_secret" and that feels weak

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-2#296]
IMO When making the project the secret should be some crazy text that is not memorable... that would feel more "safe" even if it doesnt matter

**Comment by mateodaza** [comment]
I think @aminlatifi has a plan for this, let's give this some priority!

**Comment by jamespfarrell** [comment]
assigning myself to this too

**Comment by jamespfarrell** [comment]
This is a side effect of the Torus integration, and this is being tracked on this ticket here - https://github.com/Giveth/giveth-2/issues/308
