### ISSUE TITLE
What is the 13/55 thing at the corner of the Create Project flow?

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-2#297]
<img width="926" alt="Screen Shot 2021-01-03 at 11 41 37 AM" src="https://user-images.githubusercontent.com/14945613/103483995-95c06780-4deb-11eb-90ed-8f537f2f44a2.png">

**Comment by mateodaza** [comment]
Put inside the input field so it's more clear. Let's apply this for every other similar indication

**Comment by laurenluz** [comment]
This still hasn't been moved to inside the input field, but I still find it clear that it's function is to count characters of input text.

**Comment by divine-comedian** [comment]
the character limit display hasn't been moved into the input field, moving back a column for devs to please verify
