### ISSUE TITLE
When I go over the Char Limit... it lets me proceed

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-2#298]
<img width="972" alt="Screen Shot 2021-01-03 at 11 49 58 AM" src="https://user-images.githubusercontent.com/14945613/103484063-27c87000-4dec-11eb-8d3a-7560ade4a560.png">

**Comment by laurenluz** [comment]
Looks good! Using Brave 🍉

![image](https://user-images.githubusercontent.com/75490971/104355184-ead93900-54cf-11eb-9198-9e55fa68107b.png)
