### ISSUE TITLE
Set up a DB - IPFS might be better than Postgress... ?

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-2#3]
Confirm that Postgres is the way forward (sounded like 98% certainty from kick off call) then set up the Database!

The IPFS requirement should go on the roadmap... but its not on the MVP Scope

**Comment by jamespfarrell** [comment]
All data persistence will run through the GraphQL server, so we can switch out any database or storage solution in the background and the app won't care... 

Let's keep to a database for now. I believe we may need one regardless of our later decisions, and it will get us where we want to go fast with little investment or resources.

**Comment by jamespfarrell** [comment]
Let's track this together with the GraphQL server...  https://github.com/Giveth/giveth-2/issues/4
