### ISSUE TITLE
Add Project - React Front end

### ISSUE THREAD

**Issue by jamespfarrell** [Giveth/giveth-2#30]
So far we have a very simple add project form that puts the data in the database via GraphQL.

We need to build out the forms that bring us through the process of adding project name  / organisation etc.

We should build up an object using react hooks and at the end there should be an object that represents the project details. This object is then sent to the addProject endpoint on the GraphQL server.

**Comment by geleeroyale** [comment]
Also just made an issue about this :) - https://github.com/Giveth/giveth-2/issues/29 - added it as a dependency.

**Comment by willyogo** [comment]
Here are the designs from Marko 🎉  https://www.figma.com/proto/FBqHg0UfeuaIueDEZG0tBS/Giveth-Design?node-id=976%3A158&viewport=479%2C379%2C0.03263114020228386&scaling=scale-down-width

These have been approved and are ready to be brought to life on top of the simple, but elegant backend that @jamespfarrell has developed.

The UI/UX for the project creation flow was inspired by [TypeForm](http://typeform.com/). If you're not already familiar with TypeForm's awesome UX, please check it out to get an understanding of the desired look and feel.

User Story: As a user, I want to create a project on Giveth 2 so I can share my project with the world and begin accepting donations.

Steps in project creation flow:
1. When a user clicks 'Create a Project' on v2.giveth.io, they enter the first step of the project creation flow
2. Step 1: Project Name ([Mockup](https://www.figma.com/proto/FBqHg0UfeuaIueDEZG0tBS/Giveth-Design?node-id=976%3A158&viewport=479%2C379%2C0.03263114020228386&scaling=scale-down-width))
Details: Limit length of name to 55 characters. Display character count. When a user clicks 'Next', the project name is added to the object and the user continues to Step 2.
3. Step 2: Project Description ([Mockup](https://www.figma.com/proto/FBqHg0UfeuaIueDEZG0tBS/Giveth-Design?node-id=982%3A27&viewport=479%2C379%2C0.03263114020228386&scaling=scale-down-width))
Details: Limit length of description to 2000 characters. Display character count. If a user clicks 'How to write a good project description' they see the Project Description Instruction Modal. If a user clicks 'Next', the project description is added to the object and the user continues to Step 3.
4. Step 2.5: Project Description Instruction Modal ([Mockup](https://www.figma.com/proto/FBqHg0UfeuaIueDEZG0tBS/Giveth-Design?node-id=982%3A27&viewport=479%2C379%2C0.03263114020228386&scaling=scale-down-width))
Details: Use placeholder links for now (v2.giveth.io/projects). All links open in a new tab. If a user clicks 'Close', the modal closes.
5. Step 3: Project Category ([Mockup](https://www.figma.com/proto/FBqHg0UfeuaIueDEZG0tBS/Giveth-Design?node-id=989%3A0&viewport=479%2C379%2C0.03263114020228386&scaling=scale-down-width))
Details: Project Categories from the DB are displayed in a list with checkboxes. Users must select one, and can also select multiple. When a user clicks 'Next', all selected categories are added to the object and user continues to Step 4.
6. Step 4: Location (mockup)
Details: This one probably warrants its own issue, so feel free to skip or to put a placeholder in for this now. Ideally users can type any location (ie. address, zip code, city, province, country, continent) as a tool such as google maps autocompletes. Then, when a user has selected a location from autocomplete, data gets saved as a point on the map or as an area. Users can also check a box if the project has a 'Global' impact.
7. Step 5: Project Image ([Mockup](https://www.figma.com/proto/FBqHg0UfeuaIueDEZG0tBS/Giveth-Design?node-id=982%3A131&viewport=479%2C379%2C0.03263114020228386&scaling=scale-down-width))
Details: Users can click 'Upload from Computer' to select a file to upload. They can also select an image from the gallery. (use placeholder images for now). When a user clicks 'Next' the image is added to the object and the user proceeds to the final confirmation step.
8. Step 6: Confirm and Publish ([Mockup](https://www.figma.com/proto/FBqHg0UfeuaIueDEZG0tBS/Giveth-Design?node-id=982%3A263&viewport=479%2C379%2C0.03263114020228386&scaling=scale-down-width))
Details: Users can see their previous inputs (Description is truncated to first 200 characters). When a user clicks 'START RAISING FUNDS', their project details object is sent to the addProject endpoint on the GraphQL server. If an error occurs, display the error message below the CTA. If successful, user continues to the success screen. Stretch: add a loading state to the 'Start Raising Funds' button if it's taking a bit to load.
9. Step 7: High Five! ([Mockup](https://www.figma.com/proto/FBqHg0UfeuaIueDEZG0tBS/Giveth-Design?node-id=976%3A303&viewport=479%2C379%2C0.03263114020228386&scaling=scale-down-width))
Details: User sees their Project Card, which links to their project page. Users see a link to 'View my project' or 'Go to Homepage' ; User also sees links to share on Twitter, Facebook, or LinkedIn. Draft copy for sharing: "Interested in supporting the [Project Category] cause? Check out the project we just launched on @Givethio. 100% of each donation goes directly to [Project Name]. [Project URL]"

AC:
1. Until a user has input a valid response, the 'Next' button is disabled and the user cannot continue (a response is required for each step)
2. At each step of the flow, users see a link to edit previous inputs. If a user clicks 'Edit' they are returned to that step and can see their input.
3. UI matches mockups as closely as reasonable
4. UX matches TypeForm as closely as reasonable

This looks like it could be a large body of work! Let me know if you'd like to break this up into smaller chunks/issues.

BTW, there is a step in the current flow that we're removing "Is your project part of an organization?" Please do not include this step in the flow.

Thank you!! Please let me or Marko know if you have any questions about UI/UX! 🚀

**Comment by willyogo** [comment]
This has been broken down into more specific tickets for each step in the flow. @jamespfarrell will add any remaining tickets
