### ISSUE TITLE
Add ENS to the Project address selection

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-2#300]
<img width="895" alt="Screen Shot 2021-01-03 at 11 52 47 AM" src="https://user-images.githubusercontent.com/14945613/103484105-99082300-4dec-11eb-9435-ec7612a1608b.png">

Yeah it is!

**Comment by jamespfarrell** [comment]
Not working for me 
![image](https://user-images.githubusercontent.com/10499048/104374124-b0988780-5521-11eb-8176-a93d64e035ee.png)

**Comment by mateodaza** [comment]
You have to deploy your domain to the testnet as well https://docs.ens.domains/ens-deployments

**Comment by mateodaza** [comment]
Follow thee same process as in mainnet but connected to ropsten in https://app.ens.domains/

**Comment by willyogo** [comment]
Confirmed this is working in staging now for domains registered on Ropsten network! 🎉 

Awesome sauce 🥇
