### ISSUE TITLE
Too hard to make issues

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-2#302]
I would love to see a big button on every page that will make it obvious to the user that they can give feedback...

**Comment by mateodaza** [comment]
Create a floating modal bottom right of the page, nice design that links to github <3

**Comment by geleeroyale** [comment]
signal color (primary)

**Comment by laurenluz** [comment]
Looks good to me! Can we move this to "done"? 🍉

**Comment by markoprljic** [comment]
Why is this issue closed when I did not provide any design for this? 
This is good to go? 
<img width="271" alt="Image 2021-01-20 at 1 35 13 pm" src="https://user-images.githubusercontent.com/5704285/105175531-59e40c80-5b24-11eb-93fc-6e75d8af5ba5.png">

**Comment by markoprljic** [comment]
Would this be ok? It's a bit larger and more welcoming text. 
<img width="1426" alt="Image 2021-01-20 at 1 51 51 pm" src="https://user-images.githubusercontent.com/5704285/105177285-c19b5700-5b26-11eb-9d64-7d381caaa671.png">

**Comment by markoprljic** [comment]
Maybe we can do it like this instead.

<img width="550" alt="Image 2021-01-20 at 4 56 25 pm" src="https://user-images.githubusercontent.com/5704285/105200754-74c47a00-5b40-11eb-920d-f6564e7da236.png">

And then implement something like Zenhub does

<img width="769" alt="Image 2021-01-20 at 4 55 44 pm" src="https://user-images.githubusercontent.com/5704285/105200868-8dcd2b00-5b40-11eb-97cd-13d14702740f.png">

**Comment by divine-comedian** [comment]
@mateodaza  @markoprljic  when I click give feedback can it open up to a separate page? it's kind of annoying to lose the giveth page and go to github with no convenient way to navigate back.

**Comment by geleeroyale** [comment]
@geleeroyale Make it open in a new tab
