### ISSUE TITLE
Create a new secret token for the jwt on both impact graph and the dapp

### ISSUE THREAD

**Issue by jamespfarrell** [Giveth/giveth-2#303]
## 📋 Anything to add?
We currently sign the message of a hard coded string:
`const signedMessage = await signMessage('our_secret')`

This should be put into the relevant env file.

## ⏰ Urgency/Deadline/Blockers?
Before MVP

## ❓ Why is it important?
Security

## 🤼‍ Reviewer

@jamespfarrell

**Comment by mateodaza** [comment]
relates to #296

**Comment by jamespfarrell** [comment]
duplicate so closing
