### ISSUE TITLE
Torus Logged in user session is fragile with undesirable UX

### ISSUE THREAD

**Issue by jamespfarrell** [Giveth/giveth-2#308]
## 📋 Anything to add?
A user can be logged in while not having a jwt token. They don't get jwt until they 'prove' their address. This makes developing for a logged in user problematic as we have 2 different states of logged in - ness. 

## ❓ Why is it important?
The user experience is ugly and confusing:
![image](https://user-images.githubusercontent.com/10499048/104090998-c6385380-527a-11eb-93d1-7b8c0a11433a.png)

## Ideal solution:

1. Detect for Metamask
    - if present allow user to choose between metamask and wallet connect
2. If no metamask go with torus
   - Torus will support to find a better solution - waiting for a response from Leonard

## 🎉 Subtasks

- [ ] detect metamask
- [ ] create an account with metamask or other wallet

**Comment by geleeroyale** [comment]
Tor.us scheduled for update tomorrow

**Comment by jamespfarrell** [comment]
We need to upgrade embed 1.9.4 released today

**Comment by mateodaza** [comment]
I think it will update automatically according to the repo https://github.com/torusresearch/torus-embed

**Comment by aminlatifi** [comment]
> We need to upgrade embed 1.9.4 released today

We use CDN and it loads the lates version, not it's 1.9.5

**Comment by jamespfarrell** [comment]
![image](https://user-images.githubusercontent.com/10499048/104728658-85878100-5737-11eb-81ca-92f9a7d77e60.png)

**Comment by jamespfarrell** [comment]
Deployed, please test
