### ISSUE TITLE
Search Functionality

### ISSUE THREAD

**Issue by jamespfarrell** [Giveth/giveth-2#31]
In the short term [search-js](https://www.gatsbyjs.org/docs/adding-search-with-js-search/) will be quick and easy to implement and I suggest that in the short term.

If the above is insufficient, or we realise some advantages, we could use Elastic search as it's open source.

**Comment by jamespfarrell** [comment]
This is a nice self contained task for someone to own.

**Comment by geleeroyale** [comment]
I implemented search for the commons stack FAQ which is also based on Gatsby. To begin I can try to plug it in. Some things would need to be refactored ofc. Most prominently how to display results.

**Comment by aminlatifi** [comment]
Kay mentioned: https://www.meilisearch.com/

**Comment by aminlatifi** [comment]
## Algolia
### Pros
- It's a service
- Free for our scale, also has supports for open source and non-profits by discounting or free service in case
- Good documentation
- Gatsby plugin
- Good comunity

### Cons
- Not open source!
## MeiliSearch
### Pros
- Open source
- Server side searching
- Good Documentation

### Cons
- Should setup service ourselves, no cloud service
		
## autoComplete.js
### Pros
- Open source
- Free

### Cons
- Run on client
- Not scalable

## Elasticsearch
### Pros
- Open source
- Scalable
- Great power

### Cons
- Complex

**Comment by jamespfarrell** [comment]
I would add that Algolia gives very cool statistics on search queries etc. It's also super quick to implement so it's not a big upfront investment, which is relevant. I think Algolia isn't free, but for NGO / Charities, like us it should be. 

If it was up to me I would contact Algolia, see about it being free and if so run with it for now.

**Comment by papermache** [comment]
Considering implementing search on backend.

**Comment by papermache** [comment]
for Sunday.

**Comment by papermache** [comment]
@aminlatifi Implemented on impact graph but not for front end.

**Comment by papermache** [comment]
@mateodaza implement front end.

**Comment by papermache** [comment]
user should be able to search for donations by name and address. Donations are sorted by date.

**Comment by papermache** [comment]
shelving for now.

**Comment by jamespfarrell** [comment]
I will and env variable to show hide for now iny white label pull request

**Comment by jamespfarrell** [comment]
https://github.com/Giveth/giveth-2/issues/31
