### ISSUE TITLE
Deploy to two servers after push via CircleCI

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-2#312]

**Comment by aminlatifi** [comment]
Done,
https://app.circleci.com/pipelines/github/Giveth/impact-graph/95/workflows/bad506b7-a634-433f-856e-eb439dbaf4b2/jobs/126

**Comment by mateodaza** [comment]
Great!! But after staging was re deployed, the projects were cleaned up. Can we remove that as we are in the middle of a soft launch?
