### ISSUE TITLE
Broken link while creating a project

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-2#317]
## 📋 Anything to add?
On the 'What is your project about page' the section that offers advice on how to write a good product description... when I click the link to the blog post only takes me back to the home page.
First this: ![image](https://user-images.githubusercontent.com/74267818/104260341-ecabe980-5448-11eb-9ac5-9aee26e12643.png)
Then when I click, it takes me here: 
![image](https://user-images.githubusercontent.com/74267818/104260384-051c0400-5449-11eb-917e-6bf55481e322.png)

## ❓ Why is it important?
Easy onboarding

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by jamespfarrell** [comment]
@markoprljic @Danibelle Do you know if the blog post mentioned here exists yet, and if so where it is? I want to fix the link as it's a bug that was reported during testing.

**Comment by markoprljic** [comment]
I don't think this blog post exists.

**Comment by laurenluz** [comment]
It also sends me straight back to the homepage when I click "browse examples" after following the same initial trajectory. Might make more sense to send the user to the Projects page.

**Comment by laurenluz** [comment]
There's already a comprehensive issue for this, I'm seeing:
https://github.com/Giveth/giveth-2/issues/275

Also, the blog post is here, apparently: https://knowhow.ncvo.org.uk/how-to/how-to-write-an-overview-of-a-nonprofit-organization#

**Comment by WhyldWanderer** [comment]
The blog post link is working now
