### ISSUE TITLE
staging.giveth.io/donate page not loading

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-2#321]
## 📋 Anything to add?
I clicked the "For Givers" "Donate to a project" from the home screen and the content didnt load on staging.giveth.io/donate
![image](https://user-images.githubusercontent.com/74267818/104263401-27188500-544f-11eb-8739-c87f30bb40fa.png)

This is what I got after clicking the link

![image](https://user-images.githubusercontent.com/74267818/104263370-1962ff80-544f-11eb-86a5-d55ffd0fc6c9.png)

## ❓ Why is it important?
We want donations

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by mateodaza** [comment]
There's no design for this route, should I redirect the users to the /projects view instead?

**Comment by WhyldWanderer** [comment]
Seems like that would be better than a blank screen?

**Comment by WhyldWanderer** [comment]
Functional fix! I would call this one done!
