### ISSUE TITLE
Usability suggestion: links on join page open in a new tab.

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-2#324]
## 📋 Anything to add?
I think it would make the app more user friendly if the links on the join page opened in a new tab. That way the user can still remain on the giveth dapp while they are joining the discord or telegram etc. When they open in the same window, i am likely to get distracted from the app itself.

![image](https://user-images.githubusercontent.com/74267818/104265526-677a0200-5453-11eb-85db-7c7b287403d2.png)

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by jamespfarrell** [comment]
I have mixed feelings on this one, but agree I would personally prefer in a new tab.
Opinions? @willyogo @markoprljic

**Comment by markoprljic** [comment]
The usability rule is to give users the freedom to choose how the links are open. Default is in the same window.

**Comment by jamespfarrell** [comment]
👍

**Comment by jamespfarrell** [comment]
Good enough for me, I have seen that usability recommendation many years, ago but was uncertain of the current status quo.
Great hussle @WhyldWanderer .... thank you, but gunna close this one
