### ISSUE TITLE
Arrangement of the categories when adding a project

### ISSUE THREAD

**Issue by jamespfarrell** [Giveth/giveth-2#325]
## 📋 Anything to add?## 📋 Anything to add?

![image.png](https://images.zenhubusercontent.com/5807a7a095e42b6c5baabbd3/9cb98596-7818-4524-8ff8-1f74fe4562e6)

@markoprljic Can you please test add a project, are you happy with this, or shall we perhaps have to columns?

**Comment by markoprljic** [comment]
@jamespfarrell Can we not hide the categories behind a scroll, instead expand the list and Next button at the bottom.

**Comment by divine-comedian** [comment]
looks fixed on my end!
