### ISSUE TITLE
I liked a project by clicking the heart and it removed the preexisting heart

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-2#327]
## 📋 Anything to add?
![image](https://user-images.githubusercontent.com/75490971/104334384-e3a63100-54b7-11eb-8480-63dcef4abaff.png)

I clicked the heart to like the Diamante Bridge Water Initiative Project and it subtracted a like rather than adding a like. Basically Ashley "liked" the project and it added a heart, and then I "liked" the project from my account on a separate browser and computer and her heart disappeared, leaving no hearts for that project :(

**Comment by mateodaza** [comment]
Could you clean cache of your browser? I think this was solved backend side, weird that is still happening :(

**Comment by laurenluz** [comment]
Cleared my cache and tried again - seems to work now! (Using Brave btw)

**Comment by jamespfarrell** [comment]
I have identified the issue, and I'm working on a fix.

Essentially token that is returned to you when you logged in is still saved in your local storage in your browser. In the meantime the database was wiped, and the userId you used to have is no longer valid (it now belongs to someone else). 

This would never happen when we are live, but it highlighted that we needed more resilience, and I'm working on a fix. In the mean time, you can get around this by logging out and back in again. 

Or:

**Go to:**
chrome://settings/siteData

![image](https://user-images.githubusercontent.com/10499048/104506100-36313b80-55e5-11eb-8152-0f0983474243.png)

**Comment by jamespfarrell** [comment]
Ok, I updated the JWT_SECRET which should invalidate all JWT tokens, so you all users should have to re-login now.

Please retest and make sure this is no longer and issue.
