### ISSUE TITLE
blue indicator on please select a category

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-2#331]
## 📋 Anything to add?
when I'm making a project the little blue indicator on the please choose category goes away if you click it more than 3 times. also functionality is a bit weird, maybe it should follow the mouse pointer instead of sticking to the last clicked object?

![image](https://user-images.githubusercontent.com/67759413/104343598-bfe7e880-54c1-11eb-9a6d-1b9f43e4a0a4.png)

![image](https://user-images.githubusercontent.com/67759413/104343684-daba5d00-54c1-11eb-845f-149532fc190a.png)

**Comment by jamespfarrell** [comment]
This is default browser behaviour:
![image](https://user-images.githubusercontent.com/10499048/104635198-dc427b80-56a1-11eb-89cb-fb55e592282f.png)

The blue square can be moved around the screen with the tab button - this is an accessibility feature. We will have to live with it 🤓
