### ISSUE TITLE
black rectangle on active state

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-2#334]
## 📋 Anything to add?
When I click to add an image to my project a rectangular outline shows up inside the dotted rectangular outline on the page. also shows up as a regular mouse pointer on that rectangle when its a clickable object, should be a hand pointer to make it more obvious. When I hover over the link inside of that clickable area it turns into a text pointer, if the whole thing is a clickable link to the pop up window why make only that text look like a clickable link?

![image](https://user-images.githubusercontent.com/67759413/104345659-3be33000-54c4-11eb-9e40-730e7c655310.png)

**Comment by jamespfarrell** [comment]
This should go live with @mateodaza's next PR.

**Comment by divine-comedian** [comment]
@jamespfarrell  I still get the rectangle that pops up within the larger dotted rectangle outline, but the mouse hover does show up as a hand now instead of the regular pointer. Are we leaving it as is?

**Comment by geleeroyale** [comment]
coming from theme-ui ... we need to globally override this behaviour

**Comment by jamespfarrell** [comment]
I can confirm that the hand pointer now works.

I couldn't get rid of the border, but it is default browser behaviour and not important in my opinion.

If anyone else feels like they may have better luck, please go ahead.

**Comment by divine-comedian** [comment]
Observation: Testing this out, when I hover inside the dotted line it shows hand pointer, that part works well. However, if I click inside the dotted line but outside of where the black solid line rectangle is normally it does nothing. If I click multiple times in this void zone it starts highlighting elements on the page. On staging with Brave with clean cache @jamespfarrell 

![image](https://user-images.githubusercontent.com/67759413/113185780-e138b500-9224-11eb-8258-06f0c07e1276.png)
