### ISSUE TITLE
Option to Edit Projects that I didn't Create

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-2#335]
## 📋 Anything to add?
![image](https://user-images.githubusercontent.com/75490971/104345837-6339fd00-54c4-11eb-9dc2-21504f8fbdfd.png)

When I open the Diamante project created by Ashley, instead of a Donate button, there is an Edit button. (see above)

When I open the Giveth project though, there's the option to Donate...

![image](https://user-images.githubusercontent.com/75490971/104346133-af853d00-54c4-11eb-9724-b816845ec4c3.png)

I wonder if for some reason the site is assuming Ashley and I are the same? But we're logged in w different accounts, different browsers, different computers. Same IP address though.

**Comment by jamespfarrell** [comment]
I have identified the issue, and I'm working on a fix.

Essentially token that is returned to you when you logged in is still saved in your local storage in your browser. In the meantime the database was wiped, and the userId you used to have is no longer valid (it now belongs to someone else). 

This would never happen when we are live, but it highlighted that we needed more resilience, and I'm working on a fix. In the mean time, you can get around this by logging out and back in again. 

Or:

**Go to:**
chrome://settings/siteData

![image](https://user-images.githubusercontent.com/10499048/104506100-36313b80-55e5-11eb-8152-0f0983474243.png)

**Comment by jamespfarrell** [comment]
Ok, I updated the JWT_SECRET which should invalidate all JWT tokens, so you all users should have to re-login now.

Please retest and make sure this is no longer and issue.
