### ISSUE TITLE
clicked 'back' on my browser and I lost my project

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-2#337]
## 📋 Anything to add?
I was on the last step to make my project and I went to edit the categories page, I changed my mind and clicked back on my browser to take me back to the last window I was on. Instead it went back to the first create project page and I lost my project. :( I'm using brave on private mode. 

![image](https://user-images.githubusercontent.com/67759413/104346759-684b7c00-54c5-11eb-94bf-231a7e0c8d43.png)

**Comment by jamespfarrell** [comment]
Let's put a warning if the user that they will lose all they have entered, and give them the option to go back a single step, as if they clicked on this 'back' button.
