### ISSUE TITLE
The update I made last night... now says that Lauren posted it?

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-2#339]
## 📋 Anything to add?
The author of the "aquired grey water system design" update has changed

![image](https://user-images.githubusercontent.com/74267818/104347189-f3c50d00-54c5-11eb-95a2-76ead0ea35be.png)

I posted this update last night and now it shows Lauren (karmaticacid) as the creater

**Comment by laurenluz** [comment]
Adding to this... Ashley just made a project called "Actually Ashley??" and suddenly the projects I made today are deleted/gone along with the ones Tommy and Ashley made earlier...

Also it shows that I am a creator of Ashley's project, and I didn't create it:

![image](https://user-images.githubusercontent.com/75490971/104364901-e23b2f80-54dc-11eb-8f5b-99de5250560d.png)

**Comment by laurenluz** [comment]
{"profileImage":"https://cdn.discordapp.com/embed/avatars/3.png","name":"karmaticacid#1218","email":"lauren.bajin@gmail.com","verifierId":"492394339532800020","verifier":"discord","typeOfLogin":"discord","addresses":["0x9c364D7d69Bd50a0d4035AeB50338E0940053185"],"userIDFromDB":"5"}

**Comment by jamespfarrell** [comment]
I have identified the issue, and I'm working on a fix.

Essentially token that is returned to you when you logged in is still saved in your local storage in your browser. In the meantime the database was wiped, and the userId you used to have is no longer valid (it now belongs to someone else). 

This would never happen when we are live, but it highlighted that we needed more resilience, and I'm working on a fix. In the mean time, you can get around this by logging out and back in again. 

Or:

**Go to:**
chrome://settings/siteData

![image](https://user-images.githubusercontent.com/10499048/104506100-36313b80-55e5-11eb-8152-0f0983474243.png)

**Comment by jamespfarrell** [comment]
Ok, I updated the JWT_SECRET which should invalidate all JWT tokens, so you all users should have to re-login now.

Please retest and make sure this is no longer and issue.
