### ISSUE TITLE
Formatting of Project Name//Diamante Grey Water

### ISSUE THREAD

**Issue by tommygiveth** [Giveth/giveth-2#340]
![image](https://user-images.githubusercontent.com/75334355/104347573-646c2980-54c6-11eb-865f-73fc1c995a89.png)

The title name formatting is broken between lines.  And the donations parentheses are also broken between lines.

**Comment by jamespfarrell** [comment]
I'm not sure what to do about this. We can reduce the fontsize, or use parenthesis, or else just accept that a minority of projects will have a long name, and will do the above.

What do you think @markoprljic ?

**Comment by markoprljic** [comment]
We should automatically break the line and put "initiative" in second line.
