### ISSUE TITLE
finalized project, now stuck on loading screen

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-2#342]
## 📋 Anything to add?
I finished my project and went to create it, it's stuck on the loading screen now.  this is the error info from the console.  still using brave on private mode.

![image](https://user-images.githubusercontent.com/67759413/104348349-405d1800-54c7-11eb-992a-1fdc6cde0a2b.png)

**Comment by laurenluz** [comment]
I'm experiencing the same issue... Been at more than 10 min on the same screen

![image](https://user-images.githubusercontent.com/75490971/104349259-4f909580-54c8-11eb-9ccc-572aab4d6374.png)

**Comment by mateodaza** [comment]
Our backend is being blocked by an issue of CORS that seemingly only occurs in brave, while we solve this feel free to try the dApp out in any other browser

**Comment by jamespfarrell** [comment]
@laurenluz are you also using the Brave browser, or what are you using?

**Comment by mateodaza** [comment]
You can see in her screenshot that she actually is

**Comment by laurenluz** [comment]
Yeah - confirmed, I was using Brave. Also this was happening when Ashley, Mitch, Tommy and I were all trying to make projects simultaneously. Later, when things quieted down, I was able to make a project no problem.

**Comment by mateodaza** [comment]
Closing as I couldn't replicate. Brave browser working as expected

**Comment by laurenluz** [comment]
@mateodaza this is happening to me again... been on the load screen for 5 min, using Brave

![image](https://user-images.githubusercontent.com/75490971/104854409-2a3ac780-58cc-11eb-8a60-4fdaa09c393a.png)
