### ISSUE TITLE
Takes two clicks on share

### ISSUE THREAD

**Issue by tommygiveth** [Giveth/giveth-2#345]
![image](https://user-images.githubusercontent.com/75334355/104349697-de9dad80-54c8-11eb-9e24-a24e2f00f3a5.png)

Second click

![image](https://user-images.githubusercontent.com/75334355/104349743-ebba9c80-54c8-11eb-9553-7f851e74bfbe.png)

**Comment by mateodaza** [comment]
Can you give more description on what you mean?

**Comment by tommygiveth** [comment]
When I click the share icon, it first just opens up Learn More and Donate. If I choose to click share icon again, then it brings the pop up with share options.  I'm using brave browser.

**Comment by mateodaza** [comment]
Understood!

**Comment by mateodaza** [comment]
@tommygiveth Is this a laptop or a tablet? I tried to replicate this on brave browser and didn't happen

**Comment by tommygiveth** [comment]
This was on Brave browser on an iPad

**Comment by jamespfarrell** [comment]
@tommygiveth are you staying that it should take 1 click, not 2?

I'm calling this a usability issue and deferring post MVP, unless there's a serious usability issue, in which case feel free to re-open and move back to the 'New Issue' pipeline.

**Comment by mateodaza** [comment]
Following on this, it takes 2 clicks on the tablet as the hover state doesn't exist there. I think it's alright to mark this as usability issue foe after mvp

**Comment by tommygiveth** [comment]
Ok so normally the Learn More/Donate would appear from hovering and then clicking would share.  I see @mateodaza what you mean about hover state of tablet.  Yes this is a usability post MVP issue @jamespfarrell

**Comment by jamespfarrell** [comment]
This is default behaviour on ipad -- there is no hover, I'm closing this issue.
