### ISSUE TITLE
Donations not recieved

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-2#346]
## 📋 Anything to add?
i donated to the grey water initiative project (of which i am the project manager) from 0xed8DB37778804A913670d9367aAf4F043AAd938b (a different profile than the creator profile) but it still shows no donations. 
![image](https://user-images.githubusercontent.com/74267818/104350090-5ff54000-54c9-11eb-8203-4d4b0c8e16ac.png)

However the funds do show in the my account page under "total value of assets in wallet"
![image](https://user-images.githubusercontent.com/74267818/104350146-74393d00-54c9-11eb-93ce-04b0afd5b286.png)

Tommy also tried to donate to the water initiative project but the donation is not showing up.

**Comment by mateodaza** [comment]
Same issue as #344
