### ISSUE TITLE
Add a "Report Issue" button somewhere that will allow users to easily make a github issue

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-2#35]
See beta.giveth.io
<img width="270" alt="Screen Shot 2020-07-06 at 8 48 45 PM" src="https://user-images.githubusercontent.com/14945613/86628387-1c75c280-bfca-11ea-99ca-7fbd8752409f.png">

**Comment by jamespfarrell** [comment]
@markoprljic

**Comment by markoprljic** [comment]
@jamespfarrell I have intentionally avoided to make that option available on the homepage as it isn't targeting our audience at that stage. I believe this option should exist in user account or be less prominent by placing it in the footer. I will create a mockup and let you know.

**Comment by markoprljic** [comment]
Following up from my last comment I placed the report issue option in the footer of the Homepage https://share.getcloudapp.com/9ZujyLOr
It will also be available in User Account on a more prominent place.

**Comment by willyogo** [comment]
Covered this in new issues for nav bar and footer:

https://github.com/Giveth/giveth-2/issues/56
https://github.com/Giveth/giveth-2/issues/57
