### ISSUE TITLE
partnerships page when I click an object it goes to URL in same window instead of creating a new one.

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-2#350]
## 📋 Anything to add?
I clicked on one of the links for the partners and it followed that link on the same window instead of creating a new window for the link.

![image](https://user-images.githubusercontent.com/67759413/104356382-7f906680-54d1-11eb-8c5a-b0f5e8582839.png)

![image](https://user-images.githubusercontent.com/67759413/104356408-8919ce80-54d1-11eb-83e4-3f957b085133.png)

**Comment by mateodaza** [comment]
@markoprljic mentioned in a previous issue that it is a usability rule to give users the freedom to choose how the links are open. Default is in the same window. #324
