### ISSUE TITLE
Editing project yields different appearance in the project page

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-2#354]
## 📋 Anything to add?
When I edit my project like this:
![image](https://user-images.githubusercontent.com/74267818/104357223-8370b880-54d2-11eb-8e06-c3ae50bc78f4.png)
The text format is changed when it reaches the project page. The alphabetical list does not start on each new line the same way it appears in the editing page.
![image](https://user-images.githubusercontent.com/74267818/104357317-a1d6b400-54d2-11eb-8aeb-7602b236a302.png)

**Comment by mateodaza** [comment]
Here #222 we are considering on adding rich text after MVP, so far it's just plain text
