### ISSUE TITLE
Can't create multiple projects linked to the same Eth Address

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-2#357]
## 📋 Anything to add?
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/56af781f-c140-4dd8-b7ef-653985cfe917)

Created one project, no issues, tried to create a second project, but it won't let me use the same Eth address.

**Comment by mateodaza** [comment]
So far we allow one wallet per project. This has been discussed in the past. It can make a great functionality after MVP, we are planning to make it happen!  #194 and #94 are related
