### ISSUE TITLE
Lauren's project shows up in my "my account" page

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-2#358]
## 📋 Anything to add?
![image](https://user-images.githubusercontent.com/74267818/104357707-2cb7ae80-54d3-11eb-8510-4770ed66d7fe.png)
I did not create this project but it is showing up in my account page under my projects.

Lauren and I are on the same IP address however are on different profiles and different wallets.

**Comment by jamespfarrell** [comment]
I have identified the issue, and I'm working on a fix.

Essentially token that is returned to you when you logged in is still saved in your local storage in your browser. In the meantime the database was wiped, and the userId you used to have is no longer valid (it now belongs to someone else). 

This would never happen when we are live, but it highlighted that we needed more resilience, and I'm working on a fix. In the mean time, you can get around this by logging out and back in again. 

Or:

**Go to:**
chrome://settings/siteData

![image](https://user-images.githubusercontent.com/10499048/104506100-36313b80-55e5-11eb-8152-0f0983474243.png)

**Comment by jamespfarrell** [comment]
Ok, I updated the JWT_SECRET which should invalidate all JWT tokens, so you all users should have to re-login now.

Please retest and make sure this is no longer and issue.

**Comment by laurenluz** [comment]
@WhyldWanderer looks like the projects got wiped again so I can't check anymore if I still have access to your projects. I just made one now though called "Actually Lauren?". Lets just try to edit each others projects and see if anything comes up.

**Comment by WhyldWanderer** [comment]
I havent seen this issue come up for a while. It seems fixed to me.
