### ISSUE TITLE
Sent money to my Torus Address 15 minutes ago but it has shown up on the UI

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-2#36]
Is there a min decimal point or something?

https://etherscan.io/tx/0x265928cede54f62501d1a98891e50b8df6b6d4688ab8a84ec98d8790f9c7cdfe

<img width="397" alt="Screen Shot 2020-07-06 at 8 50 06 PM" src="https://user-images.githubusercontent.com/14945613/86628527-4d55f780-bfca-11ea-8e0f-ff18bc09861d.png">
Tried waiting, refreshing, and logging in and out...

**Comment by jamespfarrell** [comment]
We are using Ropsten at the moment. 

Also I believe the Balance is currently hard coded to 0, and even if the balance was in the wallet it would show 0.

**Comment by geleeroyale** [comment]
Functionality did not exist when this bug report was files - closing this
