### ISSUE TITLE
When editing project, have to click save twice before "Saved!" popup appears

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-2#361]
## 📋 Anything to add?
If I edit, for example, my project description then scroll down and click save, the changes are saved (I checked by navigating back to the projects screen to confirm). However, there is no immediate indication that the project has been saved. If I click "save" twice though, the Save popup appears.

After one click (changes are saved, but the screen looks like this):
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/0fe59ed8-ace0-46cf-92c9-ce2605b041d5)

After two clicks:
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/f6c396c0-edfe-4e44-aee9-15eea7f90151)

**Comment by jamespfarrell** [comment]
Ah maybe only in brave?
