### ISSUE TITLE
My donations table showing wrong amount donated

### ISSUE THREAD

**Issue by mateodaza** [Giveth/giveth-2#363]
## 📋 Anything to add?
Wrong value, I donated 0.0020 ETH

![image](https://user-images.githubusercontent.com/18689480/104366254-16b3e900-54e7-11eb-8f7b-2654d6cd5d5d.png)

## 🎉 Subtasks

- [ ]  I know what to do already! on it 😃 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by WhyldWanderer** [comment]
I have tried a few times to recreate the issue but am unable to do so. I believe this bug has been fixed.
