### ISSUE TITLE
Amount of Givers showing wrong number

### ISSUE THREAD

**Issue by mateodaza** [Giveth/giveth-2#364]
## 📋 Anything to add?

![image](https://user-images.githubusercontent.com/18689480/104370818-68f80880-54ed-11eb-80bf-6490ce48d5f1.png)

## 🎉 Subtasks

- [ ]  fix filtering of donations to this
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by WhyldWanderer** [comment]
Im unable to recreate this issue now... i think this is fixed now
