### ISSUE TITLE
User ID replication through loginWallet mutation

### ISSUE THREAD

**Issue by mateodaza** [Giveth/giveth-2#370]
## 📋 Anything to add?
Every time when a new user logs in, it gets another user's ID and gets all the permissions and capabilities of it. 
IDs should not replicate and must be unique for every user. 
Relates to #327, #335, #339, #358

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by jamespfarrell** [comment]
I have identified the issue, and I'm working on a fix.

Essentially token that is returned to you when you logged in is still saved in your local storage in your browser. In the meantime the database was wiped, and the userId you used to have is no longer valid (it now belongs to someone else). 

This would never happen when we are live, but it highlighted that we needed more resilience, and I'm working on a fix. In the mean time, you can get around this by logging out and back in again. 

Or:

**Go to:**
chrome://settings/siteData

![image](https://user-images.githubusercontent.com/10499048/104506100-36313b80-55e5-11eb-8152-0f0983474243.png)

**Comment by jamespfarrell** [comment]
Ok, this should be fixed now, please retest

**Comment by jamespfarrell** [comment]
Ok, I updated the JWT_SECRET which should invalidate all JWT tokens, so you all users should have to re-login now.

Please retest and make sure this is no longer and issue.

**Comment by divine-comedian** [comment]
how am I able to check my userid?

**Comment by laurenluz** [comment]
I think these are all fixed... haven't had the issue come up in a while
