### ISSUE TITLE
clicking 'settings' under my account doesn't do anything

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-2#376]
## 📋 Anything to add?
under the drop down menu that appears when I hover over my account, top right, the 'settings' button doesn't do anything or go anywhere. 

![image](https://user-images.githubusercontent.com/67759413/104768124-c4ff9e80-5732-11eb-863c-68340d3b2e4c.png)

**Comment by divine-comedian** [comment]
This now redirects to the tor.us settings page, I'm assuming If I log in with another type of wallet it at some point it will redirect to a different 'settings' page, maybe clarify on the button that it's tor.us settings or wallet settings?

**Comment by mateodaza** [comment]
Yes, it will need more clarification when we are able to login with other providers. For now Torus is default

**Comment by jamespfarrell** [comment]
I like the idea to clarify depending on wallet type.

**Comment by geleeroyale** [comment]
- Use external link icon
- Change text to "My Wallet"
