### ISSUE TITLE
After Submitting a Project, stuck "setting everything up"

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-2#395]
This is happening both to me and @divine-comedian right now while trying to test...

We're using Brave on PC. 

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/df4db080-2d07-462a-a0cf-8aca5879b3f2)

**Comment by jamespfarrell** [comment]
This is fixed with a clearing of the cache and logging out and back in again. I'm working on this failing more gracefully though.
