### ISSUE TITLE
Project submitted, was there then not

### ISSUE THREAD

**Issue by tommygiveth** [Giveth/giveth-2#396]
![image](https://user-images.githubusercontent.com/75334355/105071204-e4a40900-5a49-11eb-9189-2b83227f435e.jpeg)

I went to visit my project.  The page was all there. I then clicked Projects at the top of page, which brought me to all Projects except the one just created.  I then go to My Projects and it no longer exists.

**Comment by mateodaza** [comment]
Replicated. If you refresh it should show. I will improve this so you can see it instantly 👍🏼
