### ISSUE TITLE
On High Five Project Done page, weird square?

### ISSUE THREAD

**Issue by tommygiveth** [Giveth/giveth-2#397]
![image](https://user-images.githubusercontent.com/75334355/105071694-8c213b80-5a4a-11eb-838e-b3ecf18da2a0.jpeg)

The empty check mark looking box above the project image seems weird.  It was on the last project too.  It's part of the background art?

**Comment by mateodaza** [comment]
haha yes, it's part of the art, my input would be to set both figures to the sides when the screen is at this size so they don't crash with the cards

@markoprljic what do you think of this solution?

**Comment by markoprljic** [comment]
Yes, move them aside. Thanks @mateodaza

**Comment by jamespfarrell** [comment]
I agree it looks like a checkbox, it catches my attention way too much :)
