### ISSUE TITLE
Verify wallet Link does nothing

### ISSUE THREAD

**Issue by tommygiveth** [Giveth/giveth-2#398]
![image](https://user-images.githubusercontent.com/75334355/105073371-9e9c7480-5a4c-11eb-88a5-81c6c5f086b0.jpeg)

Link doesn't verify wallet. Doesn't say load, or error. Just doesn't verify. Last log in it worked fine?

**Comment by jamespfarrell** [comment]
I suspect this is caused by not clearing cache and re-logging in, but we should try to reproduece this, so that we fail more gracefully.

**Comment by tommygiveth** [comment]
Logged out and in. Went to pull down on my account

![image](https://user-images.githubusercontent.com/75334355/105074435-f9829b80-5a4d-11eb-9842-45481a1bcd72.jpeg)

Clicked Verify Wallet, then I for a split second see a loading wheel then nothing happens.  The wheel is such a blip I couldn't screenshot it

**Comment by mateodaza** [comment]
no need to verify wallet now, refactor fixed this issue
