### ISSUE TITLE
Return project reactions for each project

### ISSUE THREAD

**Issue by jamespfarrell** [Giveth/giveth-2#399]
## 📋 Anything to add?
Investigate why GetProjectReactions is being called so many times
![image](https://user-images.githubusercontent.com/10499048/105073963-120fa780-5a88-11eb-973f-230c495b3a08.png)

## ⏰ Urgency/Deadline/Blockers?
MVP go live

## ❓ Why is it important?
It's a much higher number of requests and may indicate a logic problem

**Comment by mateodaza** [comment]
Currently like this, I can move it to an useEffect event instead. I guess Project Cards are refreshed way too many times. Will dive in

![image](https://user-images.githubusercontent.com/18689480/105074373-3fdbf880-5a56-11eb-876f-353eb620aec2.png)

**Comment by jamespfarrell** [comment]
Add the reactions for each project to the graphql response.

**Comment by geleeroyale** [comment]
Still pending a change

**Comment by jamespfarrell** [comment]
XHR request per project:
![image](https://user-images.githubusercontent.com/10499048/107117720-92058200-687c-11eb-9042-cdee6ff48821.png)

Performance:
![image](https://user-images.githubusercontent.com/10499048/107117756-c2e5b700-687c-11eb-9ffb-8b3304efcd94.png)
![image](https://user-images.githubusercontent.com/10499048/107117819-25d74e00-687d-11eb-8fea-bd0cfcc22e8f.png)


**After**
2 XHR requests
![image](https://user-images.githubusercontent.com/10499048/107117775-e446a300-687c-11eb-9615-53a0a4463396.png)

**Comment by jamespfarrell** [comment]
![image](https://user-images.githubusercontent.com/10499048/107131508-65328880-68d7-11eb-9a38-c707a65851bc.png)

**Comment by jamespfarrell** [comment]
![image](https://user-images.githubusercontent.com/10499048/107131524-9612bd80-68d7-11eb-8771-d44f23a7eff8.png)

**Comment by jamespfarrell** [comment]
![image](https://user-images.githubusercontent.com/10499048/107131545-c0647b00-68d7-11eb-8a5f-746ecdd0f3c6.png)

**Comment by jamespfarrell** [comment]
There won't be much to actually see here for testers, it's all under the covers
