### ISSUE TITLE
Set up the GraphQL server

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-2#4]
Hasura.io can be used to spin up a basic GraphQL server and host on heroku for free.

AC:
1. A GraphQL server is spun up that Amin and James have control of

**Comment by jamespfarrell** [comment]
I have a better solution for now. I already have a custom GraphQL server that fits us perfectly deployed, it's ready to be hooked up to front end, as soon as front end is ready - which it now is...

This will allow us to put projects into the database
