### ISSUE TITLE
Top Projects

### ISSUE THREAD

**Issue by jamespfarrell** [Giveth/giveth-2#40]
![image](https://user-images.githubusercontent.com/10499048/87193952-611a9a00-c2f9-11ea-9a23-da3304c42d38.png)

**Comment by willyogo** [comment]
Check with James before starting on this issue

**Comment by willyogo** [comment]
AC:
1. Projects are sorted by amount raised
2. Project list is truncated to first two rows
3. A 'show more' button is added beneath the list of projects
4. Full list of projects is added on /projects
5. If a user clicks 'show more' they are routed to /projects
