### ISSUE TITLE
Inconsistent wording "how to write good (vs. great) project description"

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-2#400]
Clickable link says "how to write a good project description"
Popup says "how to write a great project description" 

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/7a3ba33e-c285-4f80-b410-0bbba46b6186)

**Comment by laurenluz** [comment]
While we're here also, I think "See how others have done it:" would look better/more consistent than the current hyphen ending

**Comment by jamespfarrell** [comment]
Should be 'great' not 'good.

**Comment by divine-comedian** [comment]
@mateodaza  the wording is a bit funny, should be 'guide' instead of 'guidance' in that context. Also the top title looks funny, what do you think about left justifying it like the rest of the text below and adding punctuation like a period or a colon, you could  get crazy too and finish it with an exclamation point!

**Comment by geleeroyale** [comment]
@geleeroyale have a look at Mitch`s comment

**Comment by laurenluz** [comment]
this is related to #275, would be good to also change the awkward hyphen, and make it a colon

**Comment by laurenluz** [comment]
@jamespfarrell not actually sure how to fix this issue without bugging anyone, can you assign the appropriate person?

**Comment by jamespfarrell** [comment]
ok I've added it to the next sprint

**Comment by laurenluz** [comment]
It still says "a guidance" on both staging and giveth.io... Should say "a guide"

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/bfba18ca-ae6a-45c0-8a0a-3b31082ce585)

**Comment by laurenluz** [comment]
yay! fixed
![image](https://user-images.githubusercontent.com/75490971/114792898-715b1c00-9d46-11eb-8fac-01fd42685877.png)
