### ISSUE TITLE
Add Sentry to GraphQL server for error logging

### ISSUE THREAD

**Issue by jamespfarrell** [Giveth/giveth-2#403]
## 📋 Anything to add?
Monitor GraphQL server
[Bunyan and Winston](https://dev.to/yurigrinshteyn/what-s-the-best-way-to-log-errors-in-node-js-dfn)

## ⏰ Urgency/Deadline/Blockers?
Not urgent, but would be nice to have place as we launch

## ❓ Why is it important?
To monitor if we have errors, users encounter bugs, and log info useful for debugging

**Comment by geleeroyale** [comment]
Put sentry key in env
