### ISSUE TITLE
Subscribed to newsletter, needs some styling

### ISSUE THREAD

**Issue by jamespfarrell** [Giveth/giveth-2#405]
## 📋 Anything to add?
When you submit your email address, it needs some styling?
![image.png](https://images.zenhubusercontent.com/5807a7a095e42b6c5baabbd3/974b39f4-619e-4ae3-b94e-20805e47c9c4)

**Comment by jamespfarrell** [comment]
What do you think @markoprljic ?

**Comment by markoprljic** [comment]
Good

**Comment by markoprljic** [comment]
Maybe this, and add the [Lottie animation](https://lottiefiles.com/18025-email-equilibrium).

<img width="826" alt="Image 2021-02-03 at 9 26 03 am" src="https://user-images.githubusercontent.com/5704285/106718852-e4873a00-6601-11eb-8b47-b5f601ce91c0.png">
