### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by jamespfarrell** [Giveth/giveth-2#406]
## 📋 Anything to add?

We should have some sort of analytics in place ahead of launch.

## ⏰ Urgency/Deadline/Blockers?
Ahead of big launch. 

## ❓ Why is it important?
To know who's coming through and where they fall off

## 🎉 Subtasks

- [ ] Identify the best package (it's not Google analytics)

**Comment by mateodaza** [comment]
[Here's ](https://www.gatsbyjs.com/docs/how-to/adding-common-features/adding-analytics/) a curated list of plugins from gatsby's documentation, they have many alternatives besides google. I have little experience with these, if you guys recognize a familiar one let's check it out!

**Comment by geleeroyale** [comment]
#490

**Comment by jamespfarrell** [comment]
Closing in favour of Segment issue
