### ISSUE TITLE
Fix email sign up form on homepage (mailchimp)

### ISSUE THREAD

**Issue by willyogo** [Giveth/giveth-2#408]
Currently if a user attempts to sign up for the Giveth newsletter, they see a success message "Thank you for signing up," but they are never added to Giveth's mailing list in mailchimp. This was working on July 30th 2020 but appears to have broken at some point since then.

![image](https://user-images.githubusercontent.com/26232238/105251428-b5b89080-5b38-11eb-98b6-976ad95e65c5.png)

AC:
1. When a user signs up for the Giveth newsletter, they are successfully added to Giveth's mailing list in mailchimp

**Comment by geleeroyale** [comment]
I fixed it. However these fixes might be temporary. We should make a habit of logging into mailchimp regularly to check if we receive contacts. We are not using real API keys but a hack to use embedded form links. These seem to be invalidated after some time.

![image](https://user-images.githubusercontent.com/317685/105384784-f2f15100-5c12-11eb-8765-87dbf1930c25.png)
