### ISSUE TITLE
Transfer the Staging Site Content Google Doc into Contentful when ready and complete

### ISSUE THREAD

**Issue by ForestSoleil** [Giveth/giveth-2#413]
## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by geleeroyale** [comment]
It does not occur anywhere - I think we used it in the footer before, but changed it recently.

**Comment by jamespfarrell** [comment]
@ForestSoleil What is this? Can it be closed?

**Comment by WhyldWanderer** [comment]
https://docs.google.com/document/d/1wtqbz6Y7nNjO-Q1zj_FRUGar4bxHPUqYuiT7qlEaFCw/edit?usp=sharing
