### ISSUE TITLE
Confirm Team Consensus prior to go live - make sure all plans are in place prior to official public launch

### ISSUE THREAD

**Issue by ForestSoleil** [Giveth/giveth-2#414]
## ❓ Why is it important?
team consensus on checking in prior to go live. Ensure everyone is on the same page and all plans are in place prior to official public launch. 

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by markoprljic** [comment]
We launched so I guess this can be closed.
