### ISSUE TITLE
Add wildcard domain for preview to whitelist of deploy

### ISSUE THREAD

**Issue by jamespfarrell** [Giveth/giveth-2#419]
## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by geleeroyale** [comment]
Putting this in fast follow. Functionality is not strictly needed for deploy previews but would be nice to have.

**Comment by jamespfarrell** [comment]
We don't appear to need this
