### ISSUE TITLE
Replace "revolution.eth" with "giv.eth"

### ISSUE THREAD

**Issue by willyogo** [Giveth/giveth-2#422]
Griff acquired this amazing ENS name, giv.eth, and pointed it at the giveth multisig address (0x8f951903c9360345b4e1b536c7f5ae8f88a64e79) 🎉 

This is the official donation address we want to use for Giveth going forward. Please replace all uses of "revolution.eth" with "giv.eth" in Giveth 2.

AC:
1. revolution.eth is replaced with giv.eth throughout the giveth 2 app

**Comment by geleeroyale** [comment]
There is no instance of revolution.eth used anywhere on the DApp. I think we removed it recently. Should we add it somewhere? @willyogo
