### ISSUE TITLE
Test Balance polling

### ISSUE THREAD

**Issue by jamespfarrell** [Giveth/giveth-2#425]
## 📋 Anything to add?
I disabled it while refactoring

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by geleeroyale** [comment]
Currently broken - needs help by @mateodaza

**Comment by mateodaza** [comment]
What's this? I'm trying to remember but confused 😅

**Comment by mateodaza** [comment]
done with this, coming next PR

**Comment by laurenluz** [comment]
how do we test this? can this be closed? @mateodaza
