### ISSUE TITLE
View my projects while not logged in

### ISSUE THREAD

**Issue by jamespfarrell** [Giveth/giveth-2#426]
## 📋 Anything to add?
Search code for navigate('/?welcome')
should redirect to home page and trigger welcome

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by jamespfarrell** [comment]
Navigating here without being logged in should show a good message and / or redirect to a good login prompt.

**Comment by mateodaza** [comment]
done, coming next PR

**Comment by divine-comedian** [comment]
I get the prompt to sign into an account when i try to navigate to the url to view my projects, works as described
