### ISSUE TITLE
Wallet address in my account dropdown is clickable but doesn't link to anything

### ISSUE THREAD

**Issue by markoprljic** [Giveth/giveth-2#433]
<img width="342" alt="Image 2021-01-27 at 5 13 45 pm" src="https://user-images.githubusercontent.com/5704285/106019657-2b85a480-60c3-11eb-913b-c70e956a90e9.png">

**Comment by geleeroyale** [comment]
Behaviour now: Copy to clipboard

- [ ] Change to *4 digits ... 4 digits*
- [ ] Add external link icon that leads to etherscan+address in new space
- [ ] Add tooltip that address has been copied to clipboard

**Comment by jamespfarrell** [comment]
Are you working on this?

**Comment by mateodaza** [comment]
I removed any functionality clicking the address, and left the etherscan link when clicking "My Wallet" item instead
 
In my opinion it makes more sense like this. Let me know if you agree
