### ISSUE TITLE
Skip wallet config at setup to let Giveth hold funds until it's defined

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-2#438]
## 📋 Anything to add?
![image](https://user-images.githubusercontent.com/39466970/106160715-fa48bb00-613a-11eb-9f97-94119629d6c6.png)

Does the user HAVE to set up the wallet in advance?
Can this be a feature to come in fast follow?

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by mateodaza** [comment]
In the first project it shows the torus wallet by default and a little message explaining what's that. 

Also we are only allowing one project per address so far, so if we skip this part we would need to solve this as well

**Comment by Danibelle** [comment]
Riight.. I can't remember, did we decide that the address can be changed later?

**Comment by mateodaza** [comment]
> Riight.. I can't remember, did we decide that the address can be changed later?

Yes, you can change it anytime on the project edition view

**Comment by Danibelle** [comment]
Ok thank you!
