### ISSUE TITLE
HEYY!! My donation went through when I hit Reject!

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-2#442]
## 📋 Anything to add?
![image](https://user-images.githubusercontent.com/39466970/106162252-c078b400-613c-11eb-8c1b-3a69f19763fc.png)

Testing donation, I made a .001 ETH then balked at gas fees and hit Reject...
Then got a confirmation and.. the money moved!

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by mateodaza** [comment]
DANI WHY ARE YOU ON V2????  😨 

http://staging.giveth.io/ pleaseee

**Comment by mateodaza** [comment]
Also, I'm not sure why that happened. Can't replicate 😢

**Comment by laurenluz** [comment]
I can also reject transactions with no issues. Maybe this issue has something to do with the fact that she was originally on v2?

![image](https://user-images.githubusercontent.com/75490971/106397816-efa95280-63d4-11eb-82d0-37c20054933c.png)

**Comment by Danibelle** [comment]
I was doing a demo .. sorrryyyy...  !!!!
