### ISSUE TITLE
Integrate Metamask

### ISSUE THREAD

**Issue by jamespfarrell** [Giveth/giveth-2#443]
## 📋 Anything to add?
Lots of refactoring involved

## ⏰ Urgency/Deadline/Blockers?
By MVP

## ❓ Why is it important?
We are about giving, we shouldn't limit how people can give

## 🎉 Subtasks

**Comment by divine-comedian** [comment]
@jamespfarrell  I'm logged in via metamask, when I click on my account in the top right the drop down menu says im on tor.us and the ropsten test network when I'm in fact on metamask mainnet, also when I click on my wallet it takes me to the tor.us settings site when I'm using metamask

![image](https://user-images.githubusercontent.com/67759413/106399680-b88c6e80-63df-11eb-9e83-69ec2a7b872b.png)

**Comment by divine-comedian** [comment]
this issue I see has been fixed!
