### ISSUE TITLE
Error Creating Public Profile

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-2#446]
Was trying to test Issue #404

Not able to edit my public profile... After inputting my data and hitting "save" I just got an error

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/9579cf6a-92af-4a88-a558-6ac2e008a459)

**Comment by mateodaza** [comment]
ohoh you noticed, this is a work in progress still! 😃

**Comment by laurenluz** [comment]
haha ok :) I'll look for other things to break
