### ISSUE TITLE
Sign out/sign in - a series of related issues

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-2#447]
Wanted to test logging in with a different platform other than discord, so I signed out. When I go to sign in again it automatically signs me in again with discord, no option to sign in with a different account, or (for example) as a different person on the same computer.

I cleared the cache and tried signing in again and got the eternal spinning wheel... Now I'm stuck on this page:

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/34ccf067-a37f-4edc-89ec-fa783b40f074)

**Comment by laurenluz** [comment]
Update: can't seem to sign in on my phone or computer anymore... clicking "sign in" gives me the spinning wheel for less than a second and then stops, back on the original page, still not signed in

**Comment by laurenluz** [comment]
I did a series of test cases signing in/out to see what I could find, as follows:

1. No issues signing in/out w metamask at any point
2. Issue signing in with Torus via twitter... it gives me this "account changed" message, without actually signing me in, and then when I try again, it gives me the spinning wheel for a second and then clears, without giving me the option of selecting twitter, discord etc. Still not signed in. (see below image)
3. No issue signing in w Torus via discord or facebook
4. In general, if I'm signed in with Torus on something and then sign out and then don't clear the cache, if I hit "sign in" again w Torus, it automatically signs me in again with the same account (e.g. discord). I can switch to signing in w metamask though, without clearing the cache first

![image](https://user-images.githubusercontent.com/75490971/106398440-66941a80-63d8-11eb-9717-72ace55adc04.png)

**Comment by laurenluz** [comment]
No issues anymore signing in with any of the options!

Only thing is that, unless I clear the cache in between, if I was logged in with Torus, it automatically signs me in again in the same way (no option to select metamask/Torus, no option to select fb/twitter/discord). This could be an issue for multiple users on the same computer... What do you think @jamespfarrell ?

(FYI If I start by signing-in and then out w metamask, I don't have the same issue with it auto-signing me back into metamask... in this case I still have all the options available)

**Comment by jamespfarrell** [comment]
@laurenluz this is because of how Torus wallet works. It keeps the session active, unless you close the window. This isn't something we can change, but well done for figuring this all out... 

Thanks you for the testing!
