### ISSUE TITLE
Revamp the Landing Page to clearly show who we are and what to do

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-2#449]
## 📋 Anything to add?
UX Designer Feedback:
I don't know why I'm here or who I am when I land on this website. 
Am I a project creator, it says create a project but I don't intuitively know to scroll down to view projects..
Why is there a donate button too, why would I go straight there if I'm a donor and what am I donating to?

A more clear statement and options to View Projects by Makers before rushing to 'Create a Project'..
Info shown way down, about 'How it Works' should be more prominently accessible - if this was the landing page with buttons and index links to next sections it would clear up a lot of the confusion.

## ⏰ Urgency/Deadline/Blockers?
This to me is kind of a big blocker - it's been a personal blocker that created low grade dissatisfaction with the page. My own inability to identify and express this previously has really prevented me from moving forward on content revisions.. it's just not in the right places to guide a user through the process of finding a project, donating to it, or creating a new one.

## ❓ Why is it important?
The current tagline "Sustainable Fundraising for Social Impact" is the opposite of 'Donor-centric' or donor owned.. it looks and sounds like we are just another crowdfunding platform, without saying anything about what makes us special. Sustainable is overused everywhere, already part of the SDG language, and isn't donor identifiable.

I think if we launch like this we will end up with a bunch of projects that even if they are great won't get funding.

## 🎉 Subtasks

- Replace "Sustainable Fundraising for Social Impact" with something donor-relatable and punchy.. current favorite suggestion floated about is "Regenerative Giving for Regenerative Living"  ... for some reason everyone like the repetition, we've tried replacing the second Regenerative with other words and always come back to this.
- Reorder the presentation of information and put some clear buttons that skip down to more information on who we are, how it works, and what's so special about Giving with Giveth.
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

## 🔗 Work doc - inspirational links
https://docs.google.com/document/d/1wtqbz6Y7nNjO-Q1zj_FRUGar4bxHPUqYuiT7qlEaFCw/edit?ts=5fff140e#

**Comment by willyogo** [comment]
wow, we are on the same wavelength this morning! was just playing around with different ideas for the hero. what do you think of simpler hero language like this?

![image](https://user-images.githubusercontent.com/26232238/106388058-f9619480-6399-11eb-8f14-619f7cdb72f0.png)

**Comment by Danibelle** [comment]
Better!!
A focus on marketing is really helping us get our messaging clear :)

**Comment by jamespfarrell** [comment]
@Danibelle - is this in progress?

**Comment by willyogo** [comment]
Updates:
1. Kay made it super easy to update homepage copy (https://github.com/Giveth/giveth-2/blob/staging/src/content/giveth.md)
2. Opened a PR to update the homepage copy to the screenshot above. feel free to edit further! https://github.com/Giveth/giveth-2/pull/487

**Comment by mateodaza** [comment]
This is done
