### ISSUE TITLE
Review - Metamask OS app browser - can’t sign in?? Or?

### ISSUE THREAD

**Issue by tommygiveth** [Giveth/giveth-2#451]
Click Metamask. Asks to sign. Click sign, does nothing. Tried on mainnet and ropsten. This is from within the MetamaskOS app browser.![image](https://user-images.githubusercontent.com/75334355/106390738-721f1b80-63af-11eb-940b-7165db1abe52.png)

**Comment by markoprljic** [comment]
@tommygiveth Can you test again please?

**Comment by positonic** [comment]
I can confirm that it's not possible to login using metamask on mobile at present.

**Comment by laurenluz** [comment]
@tommygiveth can you test this and close if fixed?
