### ISSUE TITLE
Improve metamask message signing

### ISSUE THREAD

**Issue by jamespfarrell** [Giveth/giveth-2#456]
![image.png](https://images.zenhubusercontent.com/5807a7a095e42b6c5baabbd3/ede8e2cb-8d91-41a5-b889-d57ab5afa62c)

**Comment by mateodaza** [comment]
Following this https://medium.com/metamask/scaling-web3-with-signtypeddata-91d6efc8b290

**Comment by mateodaza** [comment]
![image](https://user-images.githubusercontent.com/18689480/107861864-ac100900-6e16-11eb-8952-a867ebd5e3a5.png)
