### ISSUE TITLE
edit my project while viewing a project that is mine

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-2#458]
## 📋 Anything to add?
I'm looking at a project that is mine. a nice UI feature would be able to have a button to edit my project from this screen instead of navigating to 'my projects' and then to edit project. 

![image.png](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/f29cf399-d148-4322-9298-b6b27622e8fb)

**Comment by mateodaza** [comment]
The "Donate" button already changes to "Edit" when you are the owner of it.
It's not showing to you more likely because of this issue #459
