### ISSUE TITLE
I want to 'heart' a project  while viewing it

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-2#460]
## 📋 Anything to add?
I'm viewing a project and I want to give it a 'heart' but there's no option from this page... 

![image.png](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/acc7e391-021b-4cf0-943f-4afb866ec14d)

**Comment by markoprljic** [comment]
@divine-comedian Why do you want to "heart" a project while viewing it?

**Comment by divine-comedian** [comment]
@markoprljic 

I was thinking in terms of having the same functions as this page : 

![image](https://user-images.githubusercontent.com/67759413/106762994-01b90a00-65fc-11eb-8e3b-2d623fee868d.png)

on this page: 

![image](https://user-images.githubusercontent.com/67759413/106763080-172e3400-65fc-11eb-803d-07254f87fe57.png)

If I can share, heart and donate in the simple view of the project I should have at least those functions and/or more when I go to view a project in more detail.

**Comment by markoprljic** [comment]
@mateodaza Just center-aligned, please :)

<img width="374" alt="Image 2021-02-03 at 3 51 10 pm" src="https://user-images.githubusercontent.com/5704285/106763975-aad12600-6637-11eb-90f8-774248d1cccb.png">

**Comment by mateodaza** [comment]
Got it!

**Comment by mateodaza** [comment]
coming next update

**Comment by divine-comedian** [comment]
yay! more hearts! looks to be working fine 

![image](https://user-images.githubusercontent.com/67759413/108250576-6a3bd700-7124-11eb-96be-4f79cb8fa981.png)
