### ISSUE TITLE
hovering over links on the footer shows type cursor instead of hand cursor.

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-2#461]
## 📋 Anything to add?
hovering over the links at the bottom footer, some of the links show the appropriate hand cursor when over them but about half of them for some reason show the type cursor when hovering over the link text

![image.png](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/22ff319f-b552-4ca2-976c-88d7a3e90c30)

**Comment by willyogo** [comment]
great catch 🙏  closing because this is also covered in this issue: https://github.com/Giveth/giveth-2/issues/532
