### ISSUE TITLE
Logged in with Metamask, clicking on 'my wallet' opens Torus

### ISSUE THREAD

**Issue by jamespfarrell** [Giveth/giveth-2#463]
![image](https://user-images.githubusercontent.com/10499048/106605811-9e7a9980-6561-11eb-945b-b3d6cd4f97d0.png)

**Comment by geleeroyale** [comment]
We could either make this button conditionally shown only when logged in with Tor.us or redirecting to metamask full size tab when detecting metamask

**Comment by jamespfarrell** [comment]
[This is currently going here](https://metamask.zendesk.com/hc/en-us) is that intentional? Wouldn't etherscan be better?

**Comment by mateodaza** [comment]
Yes it makes sense, coming in next PR

**Comment by divine-comedian** [comment]
On staging, my wallet now redirects to wallet address on etherscan when using metamask
