### ISSUE TITLE
User acceptance testing - Donating as logged-in and non-logged in users

### ISSUE THREAD

**Issue by jamespfarrell** [Giveth/giveth-2#465]
## What to test:

Donation as a logged in user

Donation as a non-logged in user

**Comment by laurenluz** [comment]
Tried donating as a logged in user, a couple of issues:

1. First donation actually popped up in my wallet twice so I accidentally donated twice to Giveth without going through the donations page (but maybe I misclicked?)
2. Donated to another project... none of my donations are showing up even though the transactions all went through

![image](https://user-images.githubusercontent.com/75490971/106820672-63e82e00-6641-11eb-84ba-e55fd6a8d17e.png)

**Comment by laurenluz** [comment]
Tried donating as a non-logged in user, donations are not showing up in "my donations" nor are they showing up as donations to the project. (I donated 0.002 eth twice to "break all the things")

![image](https://user-images.githubusercontent.com/75490971/106821205-52535600-6642-11eb-91db-1ef7c0c44baf.png)

**Comment by laurenluz** [comment]
I'm not having any issues with donations anymore in any of the following use cases:

- [x] as a logged-in user w metamask
- [x] as a non-logged-in user w metamask
- [x] as a logged-in user in a Torus account (tried all 3: twitter, discord, facebook), donating via metamask

And it seems that all my donations are being listed properly under "my donations" for each respective account 👍

**Comment by laurenluz** [comment]
Tested

- [x] as a logged-in user in a Torus account w Torus
- [x] as a non-logged in user w Torus
- [x] as a logged in user in a metamask account w Torus wallet
