### ISSUE TITLE
Clicking Sign In on the popup doesn't bring up Sign In Screen

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-2#468]
When i click the link in this window (which I got to by clicking Create A Project when NOT signed in..

it just closes the window instead of opening the Sign In Screen
![image](https://user-images.githubusercontent.com/39466970/106779765-2b723100-65fc-11eb-881d-e1ab7e831f4d.png)

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by jamespfarrell** [comment]
Fixed
