### ISSUE TITLE
Unable to post project updates in latest staging

### ISSUE THREAD

**Issue by willyogo** [Giveth/giveth-2#478]
The latest version of staging is awesome, but I am no longer able to post project updates with either metamask or torus wallets.

Examples of projects affected:
https://staging.giveth.io/project/Free-Peaches
https://staging.giveth.io/project/Building-houses-out-of-giant-puzzle-pieces

![2021-02-04 22 52 13](https://user-images.githubusercontent.com/26232238/106995276-c6bdf000-673b-11eb-8efd-1050837ed5f5.gif)

**Comment by mateodaza** [comment]
I'll get on it, I introduced this error with my latest changes

**Comment by mateodaza** [comment]
FIxed  🤟🏼
