### ISSUE TITLE
Network validation on user dropdown - Toast on network change

### ISSUE THREAD

**Issue by mateodaza** [Giveth/giveth-2#479]
## 📋 Anything to add?
Let's show the user's wallet connected network instead of the instance and make the flow better showing when the user changed the network to a wrong one

## ⏰ Urgency/Deadline/Blockers?
Not sure if urgent for mvp but cool to have

**Comment by willyogo** [comment]
Love it! Not required, but if it's not too hard it would be cool to use the same color coding as metamask for the ETH testnets 

![image](https://user-images.githubusercontent.com/26232238/107080276-484e6600-67ae-11eb-8753-4b3675565e77.png)

**Comment by mateodaza** [comment]
ready, coming next update

**Comment by WhyldWanderer** [comment]
Is this something that is supposed to be showing at all times or just a pop up that comes up at the time of the network switch? 
The pop up is working.. but there is no indicator of what network im currently on when the message goes away.
 Also, the colors are not coordinated with Metamask but thats probably not a blocker.

**Comment by mateodaza** [comment]
It's just a popup saying that you should change your network when it's wrong. I just noticed the tab doesn't automatically refresh, not a blocker but will fix.

Does it sound better to have an indicator that is always visible?
