### ISSUE TITLE
Description

### ISSUE THREAD

**Issue by jamespfarrell** [Giveth/giveth-2#48]
![image](https://user-images.githubusercontent.com/10499048/87211329-49eba480-c319-11ea-9940-692a6f692f98.png)

Functionally working, but much visual work

**Comment by willyogo** [comment]
Details: Limit length of description to 2000 characters. Display character count. If a user clicks 'Next', the project description is added to the object and the user continues to Step 3.

The 'How to Write a Great Project Description' drawer is covered in a [separate ticket](https://github.com/Giveth/giveth-2/issues/58)
