### ISSUE TITLE
Cause: COVID-19 for MVP

### ISSUE THREAD

**Issue by jamespfarrell** [Giveth/giveth-2#49]
![image](https://user-images.githubusercontent.com/10499048/87211364-769fbc00-c319-11ea-87a7-a8862f8f3822.png)

**Comment by willyogo** [comment]
Details: Project Categories from the DB are displayed in a list with checkboxes. Users must select one, and can also select multiple. When a user clicks 'Next', all selected categories are added to the object and user continues to Step 4.
