### ISSUE TITLE
Integrate Segment

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/giveth-2#490]

**Comment by willyogo** [comment]
1. Created a segment account ✅ 
2. Applied for segment's awesome startup program (https://segment.com/industry/startups/) ✅ 
3. I think we got instantly accepted? (see screenshot) ✅ 
4. Invited kay@giveth.io as workspace owner and james@giveth.io & mateo@giveth.io as workspace members. Are these the right emails @jamespfarrell @mateodaza?

https://segment.com/docs/getting-started/

**Comment by geleeroyale** [comment]
![Uploading screencapture-app-segment-giveth-io-destinations-catalog-2021-02-17-16_19_43.png…]()

**Comment by geleeroyale** [comment]
![screencapture-app-segment-giveth-io-destinations-catalog-2021-02-17-16_19_43](https://user-images.githubusercontent.com/317685/108234423-12619800-7145-11eb-8b08-b723358a7b5c.png)

**Comment by geleeroyale** [comment]
included in #563
