### ISSUE TITLE
After donating, enable user to click to view the project they just donated to

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-2#493]
## 📋 Anything to add?
This is a nice-to-have... Every time I donate, I wish I could just click on the project via this page (below), and then navigate back to the project I just donated to.

![image](https://user-images.githubusercontent.com/75490971/107177052-81e1c580-6996-11eb-98c6-28d383fe0229.png)

**Comment by mateodaza** [comment]
Would you like this to happen when you click the project card?

**Comment by laurenluz** [comment]
yeah!

**Comment by divine-comedian** [comment]
redirects to project page when clicking on the image! works as described!
