### ISSUE TITLE
Need design for this overlay popup

### ISSUE THREAD

**Issue by jamespfarrell** [Giveth/giveth-2#497]
![image.png](https://images.zenhubusercontent.com/5807a7a095e42b6c5baabbd3/8bbb0742-d9c9-45d2-9a04-daaf788370fc)

**Comment by markoprljic** [comment]
Preview here, source in Figma.

<img width="420" alt="Image 2021-02-08 at 3 17 40 pm" src="https://user-images.githubusercontent.com/5704285/107231662-d9c50e80-6a20-11eb-8f7b-ef03c0fbe8a2.png">

**Comment by mateodaza** [comment]
@markoprljic I added this design but the arc icon below in the modal is showing like this when I download it

![arcs](https://user-images.githubusercontent.com/18689480/107576232-db2c3d80-6bbe-11eb-8051-2587270891de.png)
 
can you help me set the color right?
SORRY FOR BOTHERING!!

**Comment by markoprljic** [comment]
> @markoprljic I added this design but the arc icon below in the modal is showing like this when I download it from figma
> 
> ![arcs](https://user-images.githubusercontent.com/18689480/107576232-db2c3d80-6bbe-11eb-8051-2587270891de.png)
> 
> can you help me set the color right?
> SORRY FOR BOTHERING!!

![Group 176](https://user-images.githubusercontent.com/5704285/107633945-1b47fa80-6c69-11eb-9fd6-18be0ac05ca9.png)

**Comment by divine-comedian** [comment]
pop up shows when i try to do certain actions that normally require login, i.e. create project. works as intended

![image](https://user-images.githubusercontent.com/67759413/108251571-8ee47e80-7125-11eb-9e33-4a5a22463294.png)
