### ISSUE TITLE
Create project button in the corner doesnt work?

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-2#498]
<img width="671" alt="Screen Shot 2021-02-08 at 10 12 10 AM" src="https://user-images.githubusercontent.com/14945613/107238788-82c33780-6a28-11eb-91c0-4f3003160a9d.png">

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by mateodaza** [comment]
This was solved in latest update
