### ISSUE TITLE
Create user

### ISSUE THREAD

**Issue by willyogo** [Giveth/giveth-2#5]
As a user, I want to be able to sign up/in with Tor.us and save project information to my tor.us account.

Answer the questions:
1. How will tor.us talk to the GraphQL server?
2. How will we initiate, detect, persist, and end sessions?
3. Will the tor.us iFrame fulfill our needs for MVP? Or do we need any functionality that is only available via the API integration?

AC:
1. When a user signs up in tor.us, a user record & eth address are saved in the DB

**Comment by markoprljic** [comment]
@jamespfarrell Can you please look into Tor.us and let me know datasets we can get for a user:

- Name
- Profile picture
- Bio
- Other?

Looking at the auth verifiers listed here I assume it depends on the auth type user selects https://docs.tor.us/direct-auth/supported-authenticators-verifiers
Having said that, can we determine the minimum common data across all verifiers we can count on to receive while building up a user account/profile?

**Comment by jamespfarrell** [comment]
Hi @markoprljic, sorry I missed your message before.
This is default torus for inspiration:
![image](https://user-images.githubusercontent.com/10499048/83972639-976f8e80-a8e1-11ea-9c07-a3520bb53e11.png)

Check out http://giveth2.netlify.app/ for the working ugly version

**Comment by jamespfarrell** [comment]
Current status is that a user can log in. We are not yet saving they user in the database, and can't save projects yet either.

**Comment by markoprljic** [comment]
@jamespfarrell Thanks!

So, I tried out the "ugly" version and it allows me to login with google account only. Will there be more login options in the future?
