### ISSUE TITLE
Create project - Location

### ISSUE THREAD

**Issue by jamespfarrell** [Giveth/giveth-2#50]
![image](https://user-images.githubusercontent.com/10499048/87211412-a9e24b00-c319-11ea-9ecc-9a51735756a5.png)

Not started

**Comment by willyogo** [comment]
Ideally users can type any location (ie. address, zip code, city, province, country, continent) as a tool such as google maps autocompletes. Then, when a user has selected a location from autocomplete, data gets saved as a point on the map or as an area. Users can also check a box if the project has a 'Global' impact.
