### ISSUE TITLE
Remove "simple" from the browser tab description

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-2#500]
<img width="228" alt="Screen Shot 2021-02-08 at 10 09 59 AM" src="https://user-images.githubusercontent.com/14945613/107241785-9a4fef80-6a2b-11eb-956c-c11ffce45ba5.png">

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by mateodaza** [comment]
Should we just leave "Giveth" or something else?

**Comment by GriffGreen** [comment]
My vote is to leave as is... just remove "simple"

**Comment by divine-comedian** [comment]
on staging shows 'Giveth Donation Application - fixed as described!
