### ISSUE TITLE
OMG I LOVE THE SOFT LAUNCH NOTIFICATION

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-2#502]
<img width="366" alt="Screen Shot 2021-02-08 at 6 50 34 PM" src="https://user-images.githubusercontent.com/14945613/107296052-ee30f780-6a70-11eb-9d38-db5a5e4eaea3.png">

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by Danibelle** [comment]
🔥🔥🔥

**Comment by jamespfarrell** [comment]
Love is love
