### ISSUE TITLE
Reloads landing page to different layout after SoftLaunch pop up

### ISSUE THREAD

**Issue by tommygiveth** [Giveth/giveth-2#506]
When you go to Giveth.io, it first loads this view for a moment

![image](https://user-images.githubusercontent.com/75334355/107303953-b6f92100-6a45-11eb-9062-e1751f73bb07.jpeg)

Then the soft launch pop up appears then it quickly reloads the page to this 

![image](https://user-images.githubusercontent.com/75334355/107304070-fc1d5300-6a45-11eb-947b-f5dcc5c45a86.jpeg)

**Comment by tommygiveth** [comment]
On Ipad brave browser

**Comment by tommygiveth** [comment]
![image](https://user-images.githubusercontent.com/75334355/107539351-7e169480-6b8a-11eb-87e9-f47039ac75b8.png)

Chrome looks like this, with both Create A Project and Sign in

**Comment by tommygiveth** [comment]
![image](https://user-images.githubusercontent.com/75334355/107539638-c766e400-6b8a-11eb-89d4-4962663d624b.png)

This was Brave but horizontal.  Didn't replicate issue

**Comment by jamespfarrell** [comment]
This isn't a serious enough issue for us to support on such an edge case of brave browser and iPad, if you disagree, please re-open and ping me.
