### ISSUE TITLE
join.giveth.io and giveth.io/join go nowhere!!

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-2#507]
These links are everywhere...  we need that join link to have a page at the end please :)
![image](https://user-images.githubusercontent.com/39466970/107436369-46eca880-6ae2-11eb-909e-035c769f78dd.png)

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by jamespfarrell** [comment]
We have [a page](https://giveth.io/join/) now :)

**Comment by divine-comedian** [comment]
hallelujah! it works!
