### ISSUE TITLE
donate.giveth.io and giveth.io/donate go nowhere!

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-2#508]
Even if it's just to the Projects page.. or to the Giveth project page itself.. 

These are key links that are still out there..
![image](https://user-images.githubusercontent.com/39466970/107436576-903cf800-6ae2-11eb-85ec-1b5857ddb58d.png)

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by jamespfarrell** [comment]
This looks like some sort of bug yeah

**Comment by mateodaza** [comment]
As there's not a specific view for this, where should we redirect?

**Comment by willyogo** [comment]
I think donate.giveth.io and giveth.io/donate can redirect to https://giveth.io/donate/giveth

**Comment by mateodaza** [comment]
I can handle the giveth.io/donate  redirection but I'm not sure how to do the other one, @geleeroyale I'm sure you know how to set the redirection for donate.giveth.io

**Comment by geleeroyale** [comment]
Updated donate.giveth.io - pls allow some time for DNS propagation

**Comment by divine-comedian** [comment]
donate.giveth.io works fine, something funny is happening with the redirect on giveth.io/donate, it redirects to giveth.io/donate/ loads briefly, you can see parts of the UI show up but then it goes to a blank screen with the URL giveth.io/donate - I can send you a quick vid @mateodaza via telegram to better demonstrate.

![image](https://user-images.githubusercontent.com/67759413/108250078-d1a55700-7123-11eb-8e43-0f5d4acd8685.png)

then goes to 

![image](https://user-images.githubusercontent.com/67759413/108250143-e1bd3680-7123-11eb-8904-9efbc0146d03.png)

**Comment by geleeroyale** [comment]
thank Mitch - but giveth.io/donate is not a redirect - it is the route that leads to project donation pages --- the project named mitch would have its donation page at giveth.io/donate/mitch

Mateo wrote above that he will take care of making it redirect to Giveth's donation page

**Comment by laurenluz** [comment]
![image](https://user-images.githubusercontent.com/75490971/114784211-2b975700-9d38-11eb-9895-77e71d389238.png)
