### ISSUE TITLE
Upload Picture

### ISSUE THREAD

**Issue by jamespfarrell** [Giveth/giveth-2#51]
![image](https://user-images.githubusercontent.com/10499048/87211439-c1213880-c319-11ea-9ffe-cf01b1260998.png)

**Comment by jamespfarrell** [comment]
Cloudinary is probably easiest

ipfs is interesting

**Comment by willyogo** [comment]
Details: Users can click 'Upload from Computer' to select a file to upload. There is a separate ticket to [select an image from the gallery](https://github.com/Giveth/giveth-2/issues/38). When a user clicks 'Next' the image is added to the object and the user proceeds to the [final confirmation step](https://github.com/Giveth/giveth-2/issues/52)

**Comment by aminlatifi** [comment]
I implemented simple uploading directly to pinata!

On this branch [f_51_upload_picture_pinata](https://github.com/Giveth/giveth-2/tree/f_51_upload_picture_pinata) use this pass to see how it works: http://localhost:8000/upload_image

Just need to fill these two on .env.development with your pinata key
PINATA_API_KEY=your api key
PINATA_SECRET_API_KEY=your secret api key
