### ISSUE TITLE
Failed to fetch at the last step of project creation

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-2#515]
## 📋 Anything to add?
I was adding a few of the pilot projects from our notion document. when I got to the last step of project creation
![image](https://user-images.githubusercontent.com/74267818/107590238-441ab200-6bcd-11eb-8acc-978e036244af.png)
After pressing start raising funds button I get this error screen
![image](https://user-images.githubusercontent.com/74267818/107590291-657b9e00-6bcd-11eb-920f-a16ff375478f.png)
Then i press the back button in my browser and it takes me to the projects page
![image](https://user-images.githubusercontent.com/74267818/107590343-85ab5d00-6bcd-11eb-8c0c-4dd5bb7d8be6.png)
If I press create a project again from there... All of my info has been saved so I dont need to fill it back in but when i get back to the last step, I get the same error.

**Comment by WhyldWanderer** [comment]
I signed out, cleared cache, and logged back in but am still having the same issue

**Comment by WhyldWanderer** [comment]
I went back through the creation process again but this time I chose a different image and it worked.
The first image was 3.36 MB and the second was only 666 KB maybe this had something to do with it?
I did not receive an error message when adding the photo at all and the preview was looking fine.

After finalizing the project creation, I went into my account to edit the project to try to change the image to the bigger one that I tried to use first. I uploaded the image fine but when I press save at the bottom, I get no error I just get a loading screen.
![image](https://user-images.githubusercontent.com/74267818/107591539-80034680-6bd0-11eb-930c-a2fad1752e0b.png)

**Comment by geleeroyale** [comment]
We have a maximum filesize set. Should handler this with an error and tell users the maximum accepted size

**Comment by mateodaza** [comment]
Nice find @WhyldWanderer! I love the testers are so great at debugging!!

**Comment by mateodaza** [comment]
I'm trying to replicate, did the flow with bigger images and it works. 

@WhyldWanderer can you tell me what format did you try to upload?

**Comment by WhyldWanderer** [comment]
both were .jpg images

**Comment by WhyldWanderer** [comment]
It seems that i can only use images under 1MB

**Comment by jamespfarrell** [comment]
Could it be a combination of slow up upload on your internet connection?

**Comment by WhyldWanderer** [comment]
Its a possibility... but an image of 998kb goes through in seconds and an
image of 1.07MB will not go through no matter how long i let the pink
circle spin

**Comment by mateodaza** [comment]
I'm having trouble replicating this 😅 
@WhyldWanderer for now can you show me what you get in your console with this specific image?

**Comment by WhyldWanderer** [comment]
Is there a good method in which i can record my screen as i go through the
steps or is it more efficient to take screenshots? I will get on it first
thing in the morning!

**Comment by jamespfarrell** [comment]
{
  "errors": [
    {
      "message": "Variable \"$somefile\" got invalid value {}; Upload value invalid.",
      "locations": [
        {
          "line": 1,
          "column": 11
        }
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}

**Comment by jamespfarrell** [comment]
![image](https://user-images.githubusercontent.com/10499048/109183527-516b9b00-778e-11eb-8997-144ed626782a.png)

**Comment by jamespfarrell** [comment]
![image](https://user-images.githubusercontent.com/10499048/109192493-921be200-7797-11eb-8caa-f3cd8b5aeb82.png)

**Comment by jamespfarrell** [comment]
[Trying this](https://stackoverflow.com/questions/64285687/variable-file-got-invalid-value-upload-value-invalid) and [this](https://stackoverflow.com/questions/64658321/variable-file-got-invalid-value-upload-value-invalid)

**Comment by jamespfarrell** [comment]
The above worked. Copied this live as a hotfix, as it could have been blocking people from posting projects on live

**Comment by jamespfarrell** [comment]
@WhyldWanderer this fix is live now....

**Comment by WhyldWanderer** [comment]
Yay! It worked.. I was able to successfully upload my image of 3.37MB
