### ISSUE TITLE
Allow donations in other Cryptocurrency

### ISSUE THREAD

**Issue by markoprljic** [Giveth/giveth-2#518]
## 📋 Anything to add?
Allow donations in DAI, USDC, or any other token. 

## ❓ Why is it important?

Because it is easier and faster to donate if user doesn't have ETH but has many other tokens. Also, someone might not want to give their ETH but instead donate other token.

**Comment by GriffGreen** [comment]
+1 critical feature

**Comment by willyogo** [comment]
Agreed this is critical. Any ideas for which tokens should be listed? We could use a tokenlist like [Coingecko's](https://tokenlists.org/token-list?url=https://tokens.coingecko.com/uniswap/all.json) which gets updated everyday, and delegate the curation of supported tokens to them. Enabling users to import a token by contract address and then remembering which tokens a donor has imported would be a nice to have, but seems far beyond MVP. Open to other suggestions for what this list should be, including with starting with something hardcoded (ie. if we want the list to be shorter, we could hardcode the [69 tokens currently in the top 200 by market cap](https://tokenlists.org/token-list?url=erc20.cmc.eth)).

Proposal for the MVP of this feature:

AC:
1. Users can click 'ETH' to open a dropdown of tokens
2. All tokens in either this [longer list](https://tokenlists.org/token-list?url=https://tokens.coingecko.com/uniswap/all.json) or this [shorter list](https://tokenlists.org/token-list?url=erc20.cmc.eth) are available for a user to select 
3. When a user selects a token to donate, inputs an amount, and clicks 'donate', they are prompted to confirm the donation for the respective token and amount in their wallet
4. Users can search for a token by name or symbol
5. Stretch: when a user selects a token from the list, the rates are updated to reflect the selected token (should be able to get these all from coingecko)

Rough mockup for what this could look like (@markoprljic please feel free to replace this with something better!)
![2021-02-14 11 46 30](https://user-images.githubusercontent.com/26232238/107885954-6a389e80-6eba-11eb-8fb4-5e063362513d.gif)

**Comment by markoprljic** [comment]
That's perfect! No design needed from my end, @willyogo already provided mockup. We have styles in front end I believe @mateodaza you can code it? If UI needed let me know.

**Comment by mateodaza** [comment]
Great! Willy rocks at building mockups!

**Comment by mateodaza** [comment]
Leaving this for documentation
- I will try this approach first https://medium.com/@piyopiyo/how-to-send-erc20-token-with-web3-js-1-0-0-95164b32e9a6 
- There needs to be some changes related to the way we save donations
- Refactor amount donated and donations table after we make the changes

**Comment by divine-comedian** [comment]
@mateo I managed to get USDC and UNI on ropsten from the compound faucet but neither want to show up properly on staging.
UNI contract - 0xc8f88977e21630cf93c02d02d9e8812ff0dfc37a
USDC - 0x07865c6e87b9f70255377e024ace6630c1eaa37f
![image](https://user-images.githubusercontent.com/67759413/111007225-5a4a9800-835c-11eb-9ddd-ecedb51f5215.png)

**Comment by mateodaza** [comment]
I only allowed DAI and UNI besides our test token YAY and the address of the UNI contract I used was 0x1f9840a85d5af5bf1d1762f925bdaddc4201f984 - you can use it instead? I can add USDC for later testing

**Comment by divine-comedian** [comment]
Donated in Ropsten DAI, works like a charm! nice work! 
![image](https://user-images.githubusercontent.com/67759413/111073778-72362f00-84b6-11eb-8f89-7ab4e9a19349.png)

**Comment by divine-comedian** [comment]
Okay I followd up and my donation I made in DAI doesn't show up on my donations or the project donations page, it's been about an hour since I donated.. 
![image](https://user-images.githubusercontent.com/67759413/111075612-3358a700-84bf-11eb-8f97-314de9281e9a.png)

**Comment by mateodaza** [comment]
nice find! this is what I'm getting
![image](https://user-images.githubusercontent.com/18689480/111075704-4798a600-84b7-11eb-9910-b6c47e051749.png)
@jamespfarrell have any idea?

**Comment by divine-comedian** [comment]
Testing this out here, I successfully made a donation with DAI and UNI, it shows up on the project's donation tab very nicely 
![image](https://user-images.githubusercontent.com/67759413/112315984-0f485300-8c81-11eb-82bf-fc8b5bfb4e27.png)

## HOWEVER 
Neither ERC-20 token transactions show up in my account under `MY DONATIONS` 
![image](https://user-images.githubusercontent.com/67759413/112315528-9c3edc80-8c80-11eb-9a4b-e1305afd7122.png)

**Comment by mateodaza** [comment]
I'll check what's going on here, this also relates to #695

**Comment by divine-comedian** [comment]
Sooo funny story .. All of my donations in ERC-20 tokens have been showing up, but just not in chronological order.. I flipped back a couple pages and well.. there they are! Sorry @mateodaza  for wasting your time :/ I'll check into making a separate issue for ordering donations by when they were made

![image](https://user-images.githubusercontent.com/67759413/112652016-58380d00-8e23-11eb-95fb-d43cd2dfede6.png)
