### ISSUE TITLE
Create project - confirm publish page

### ISSUE THREAD

**Issue by jamespfarrell** [Giveth/giveth-2#52]
Admin/Donation wallet - When a project is created, the creator's Tor.us account/address is designated as the project's admin/donation address 
**Confirm and publish project**

![image](https://user-images.githubusercontent.com/10499048/87211495-f9c11200-c319-11ea-8bac-00ab68b4715b.png)

**Comment by willyogo** [comment]
Details: Users can see their previous inputs (Description is truncated to first 200 characters). If a user clicks 'edit' on a step they are returned that step in the flow. When a user clicks 'START RAISING FUNDS', their project details object is sent to the addProject endpoint on the GraphQL server and their project is published. If an error occurs, display a error message below the CTA. If successful, user continues to the success screen. Stretch: add a loading state to the 'Start Raising Funds' button if it's taking a bit to load.

**Comment by willyogo** [comment]
When a project is created, a unique, human-readable URL is generated for the project view

ie. https://v2.giveth.io/projects/[project-name][#]
