### ISSUE TITLE
Press show more projects, “8” changes to “0” before loading

### ISSUE THREAD

**Issue by tommygiveth** [Giveth/giveth-2#523]
![image](https://user-images.githubusercontent.com/75334355/107845609-4bdf7f80-6da2-11eb-908b-05b7221e79fd.jpeg)

It then goes back to the right number and displays all the projects.

**Comment by tommygiveth** [comment]
It also happens when you press the Projects link on the top of the page.

**Comment by jamespfarrell** [comment]
This will be resolved by serverside rendering

**Comment by tommygiveth** [comment]
Ok. Thanks

**Comment by laurenluz** [comment]
looks good
