### ISSUE TITLE
My Account - Allow user to cancel profile editing.

### ISSUE THREAD

**Issue by markoprljic** [Giveth/giveth-2#524]
## 📋 Anything to add?

When user clicks on Edit profile there is no option to cancel editing. User should be able to cancel and dismiss any changes they have made.

Cancel link should be placed next or below the Save button. 
When user clicks cancel they should be prompted with a message: Are you sure you want to cancel? All changes will be lost. (Yes, cancel / Keep editing)

**Comment by markoprljic** [comment]
<img width="628" alt="Image 2021-02-13 at 11 46 08 am" src="https://user-images.githubusercontent.com/5704285/107848089-17df7b00-6df1-11eb-987a-ce640b892436.png">

When user clicks Cancel, maybe just swap current modal content (Edit profile) with this prompt
<img width="449" alt="Image 2021-02-13 at 11 48 01 am" src="https://user-images.githubusercontent.com/5704285/107848140-70167d00-6df1-11eb-882e-e13d80ea8de2.png">

Keep editing brings back edit profile form fields, Yes Cancel closes the modal.

**Comment by mateodaza** [comment]
done, coming next update
