### ISSUE TITLE
Clicking Similar Projects brings up all projects? Add clickable categories?

### ISSUE THREAD

**Issue by tommygiveth** [Giveth/giveth-2#526]
![image](https://user-images.githubusercontent.com/75334355/107845813-189df000-6da4-11eb-8b17-932ce22d85a4.png)

The current projects all have similar tags except for Giveth. And with so many category tags, this may be the case often that it doesn't really accomplish much but claim well, all the projects are similar...

I propose the categories in pink are links themselves that filter to projects with that category.

**Comment by tommygiveth** [comment]
I realize this may a user feature request somewhat.

**Comment by jamespfarrell** [comment]
You are right, well caught...

**Comment by mateodaza** [comment]
It's totally related to a bigger issue #31 

We have been postponing it for after mvp as there won't be as many projects to search/filter, for now we could change the phrasing on that link?

**Comment by jamespfarrell** [comment]
@mateodaza should we remove the button until then?

**Comment by mateodaza** [comment]
> @mateodaza let's remove the link for now....

gotcha

**Comment by divine-comedian** [comment]
no more similar projects link on project page, changes look as described! 

![image](https://user-images.githubusercontent.com/67759413/108252155-4da09e80-7126-11eb-9833-b57f42a4a8d0.png)
