### ISSUE TITLE
Puzzle piece is covering text on front page under, how it works

### ISSUE THREAD

**Issue by tommygiveth** [Giveth/giveth-2#528]
![image](https://user-images.githubusercontent.com/75334355/107846159-2e60e480-6da7-11eb-9edf-b9c6bc031d1c.png)

**Comment by jamespfarrell** [comment]
I believe this is on iPad

**Comment by tommygiveth** [comment]
Hrm ok. Do we not expect users of Giveth to use their phones or iPad?

**Comment by mateodaza** [comment]
done, coming next update

**Comment by divine-comedian** [comment]
one more piece of the puzzle solved. 

![image](https://user-images.githubusercontent.com/67759413/110692729-a9ee5f80-81b4-11eb-9b44-6dc2c5fb088c.png)
