### ISSUE TITLE
Create project success

### ISSUE THREAD

**Issue by jamespfarrell** [Giveth/giveth-2#53]
As a project creator, I want to see a success screen when my project is successfully published.

Stretch: Share on social

![image](https://user-images.githubusercontent.com/10499048/87211524-1f4e1b80-c31a-11ea-9b3d-24bdef9b1f99.png)

**Comment by willyogo** [comment]
Details: User sees their Project Card, which links to their project page. Users see a link to 'View my project' or 'Go to Homepage' ; User also sees links to share on Twitter, Facebook, or LinkedIn. Draft copy for sharing: "Interested in supporting the [Project Category] cause? Check out the project we just launched on @Givethio. 100% of each donation goes directly to [Project Name]. [Project URL]"

**Comment by brymut** [comment]
Currently mostly done, just need a way to generate the link after a successful project addition, maybe using a slug of the project title?

**Comment by GriffGreen** [comment]
need to fix the cart and make the share button work
