### ISSUE TITLE
On about page, says I and not “you”?

### ISSUE THREAD

**Issue by tommygiveth** [Giveth/giveth-2#531]
![image](https://user-images.githubusercontent.com/75334355/107846318-703e5a80-6da8-11eb-826c-62a66b0601e0.png)

As a mutual aid project, I can post details about my project, raise funding, and post project updates.

Change to:

As a mutual aid project, you can post details about your project, raise funding, and post project updates.

Same with donor part.

**Comment by willyogo** [comment]
fixed, thanks for reporting!
