### ISSUE TITLE
Too hard to give feedback and report bugs

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-2#540]
## 📋 Anything to add?

On every page, there should be a visible way to give feedback, currently it is hidden behind the name... its very non-intuitive to find it there. 

Let's double down on collecting user feedback! 

## ⏰ Urgency/Deadline/Blockers?
pretty urgent

## ❓ Why is it important?
the dapp is still very new and we should make it easy for people to offer suggestions

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by mateodaza** [comment]
Once the user clicks on the Github popup exit button it won't appear again, should I change the UX on this so it only disappears in the current view but shows up everywhere else? @GriffGreen @markoprljic

**Comment by markoprljic** [comment]
I would say yes, disable only on current view and show on next. Later we can change that but while we're at softlaunch and launch we want this to be a bit 'annoying' and always accessible to users.

**Comment by mateodaza** [comment]
Related to this issue #542 I got an idea of maybe changing the title of 'Give Feedback' to something more related to the softlaunch. So we wouldn't fill the screen with both alerts, only one.

SoftLaunch Mode
share your feedback or report an issue
GIVE FEEDBACK

It also makes sense to be more clear given that is a bit redundant to have 'Give Feedback' twice in the same box. What do you think @markoprljic ?

**Comment by markoprljic** [comment]
Great idea! Approved :)

**Comment by divine-comedian** [comment]
pop up for feedback shows on every page load, looks good! 

![image](https://user-images.githubusercontent.com/67759413/108251876-f8648d00-7125-11eb-9256-0621f964f398.png)
