### ISSUE TITLE
Weird Notification "dappId needs to be passed..."

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-2#541]
## 📋 Anything to add?

<img width="1440" alt="Screen Shot 2021-02-14 at 11 14 53 AM" src="https://user-images.githubusercontent.com/14945613/107882363-15f8e300-6ee9-11eb-95fb-3e960902d0be.png">

I was using torus, and donated on brave with shields down... got this weird error... 

## ⏰ Urgency/Deadline/Blockers?

low, just a weird pop up.. seemed like it was a torus pop up

## ❓ Why is it important?

when donating... if there is an error... Its really really scary and concerning. We can't be giving mixed messages, errors and confetti... hurts the trust.

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by mateodaza** [comment]
It's onboard.js notify service that's failing. I'll check on this. Thanks!

**Comment by divine-comedian** [comment]
not seeing any torus errors while signing in or donating on brave, looks to be fixed
