### ISSUE TITLE
Make the "We are in soft launch mode" pop up show up EVERY TIME

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-2#542]
I saw it last week... but i didnt see it pop up today

**Comment by mateodaza** [comment]
Maybe it can get annoying to show it in every moment or state change in the dApp so I consider maybe showing it every session or in certain amount of time. What do you think @markoprljic ? what would be the best UX in here?

**Comment by markoprljic** [comment]
I don't think it should show every time. Once per session is fine to inform the user about it.

**Comment by divine-comedian** [comment]
Every time I navigate to a new page on giveth the soft launch pop up is there, is this the intended function or was it once per session? @mateodaza  

![image](https://user-images.githubusercontent.com/67759413/108250785-a66f3780-7124-11eb-8fd3-2b02b712f9f9.png)

**Comment by divine-comedian** [comment]
as per discussion in issue #540 maybe we throw this one in the icebox to adjust after launch? or...? @mateodaza @jamespfarrell

**Comment by jamespfarrell** [comment]
I agree with Marko.... closing for now
