### ISSUE TITLE
I have xDAI in my wallet, I would love to donate it!!

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-2#543]
## 📋 Anything to add?

Gas is so much cheaper on xDAI, it would be cool if i could donate xDai and xDai tokens via torus and via metamask directly through the UI

## ⏰ Urgency/Deadline/Blockers?

If possible, it would be great for this to be part of the MVP launch, otherwise FF

## ❓ Why is it important?

Gas Prices have ruined mainnet for the next several months at least...  we need a L2 solution and this is the easiest option IMO

## 🎉 Subtasks

- [ ] UX Design
- [ ] Torus implementation
- [ ] Metamask Implementation

## 🤼‍ Reviewer

@markoprljic is the first step the design?

**Comment by willyogo** [comment]
This is so necessary. What do you the UX for this should look like? Should xDAI just be one of the options available in the menu of tokens to donate? I think I like that UX if we can pull it off. Also open to other ideas.

Also, it'd be awesome if a project's donation history/total would include donations on both mainnet and xDAI, regardless of which network the user is connected to (if any). I think we need a few issues for this:
1. Ability to donate xDAI to a project directly through the UI
2. Include donations on xDAI in project's donation totals and history

Creating [a separate issue](https://github.com/Giveth/giveth-2/issues/544) for #2, feel free to edit it. Good news: just checked blocknative's notify.js and apparently it works on xDAI 🎉

**Comment by divine-comedian** [comment]
I log in with Metamask on xDai and it throws me an error message 

![image](https://user-images.githubusercontent.com/67759413/110691039-a063f800-81b2-11eb-81df-054a5521dbbc.png)
  and it closes metamask when it attempts to open.

however changing my chain after logging in with ropsten I successfully made a donation with xDai 

![xdai test](https://user-images.githubusercontent.com/67759413/110691729-824ac780-81b3-11eb-82c0-94481ea40a55.png)
