### ISSUE TITLE
Include donations on xDAI in project's donation totals and history

### ISSUE THREAD

**Issue by willyogo** [Giveth/giveth-2#544]
We'll soon be enabling donations on xDAI, and should support the same level of tracking and other functionality that we support for mainnet donations.

AC:
1. When a donor donates to a project on xDAI, they see the donation success screen when their transaction is confirmed
2. Users can see a project's xDAI donation history included in the project's donation table and total donations

**Comment by divine-comedian** [comment]
works as described! I was also successfully able to donate on xDai as mentioned in the other issue.

![image](https://user-images.githubusercontent.com/67759413/111007807-af3ade00-835d-11eb-9bac-37a41e5f7065.png)
