### ISSUE TITLE
User's projects not showing

### ISSUE THREAD

**Issue by jamespfarrell** [Giveth/giveth-2#548]
![image.png](https://images.zenhubusercontent.com/5807a7a095e42b6c5baabbd3/f84ac688-7644-468b-9655-0f260e42dc88)

Kay has a project, but it shows none

**Comment by mateodaza** [comment]
Just tried this out, it only shows if you are logged in.
More likely we have a token requirement for the userByAddress query

**Comment by divine-comedian** [comment]
I can see other users projects while not logged in, looks good. 

![image](https://user-images.githubusercontent.com/67759413/108249151-b5ed8100-7122-11eb-986d-e342a25e2aba.png)
