### ISSUE TITLE
Trying to use an ENS name does not work

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/giveth-2#564]
Does not work for `create project`

![image](https://user-images.githubusercontent.com/317685/108546349-4aa1db80-72e9-11eb-8d04-8937e62d3e9d.png)

Does not work for `edit project`

![image](https://user-images.githubusercontent.com/317685/108546510-7fae2e00-72e9-11eb-8763-15e9813d541f.png)

**Comment by mateodaza** [comment]
BIG QUESTION as I can't test right now, do you have your ens domain ready for ropsten?

**Comment by geleeroyale** [comment]
Hmmm - I had not considered that - its true. Is it possible to always use mainnet for checking ENS regardless of environment? 

I think this happened on live as well for me - will test again.

**Comment by mateodaza** [comment]
@geleeroyale could you replicate this?

**Comment by geleeroyale** [comment]
Ok - ENS worked really well (once I had an ens name registered with the **ropsten ens contract**)

Caveats:
- Switching on a newly created project worked great for `creation`as well as `edit`
- Even tho I changed the address for an old project that had donations, address updated in settings but not in donation view (I guess because it already had donations
- Semi-related: The project was not displayed on the projects page (or anywhere else). If this is because of SSR (it also took some time to be reachable) we should inform the user how long it approximately takes for their project to be reachable - full address of my project is: https://staging.giveth.io/project/testing-ens

**Comment by mateodaza** [comment]
currently working on fetching the data client side after getting the first content from SSR - both issues are related to the content not be on sync with the database

**Comment by divine-comedian** [comment]
I borrowed Kay's ENS address, worked like a charm, can you confirm @geleeroyale ? 
![image](https://user-images.githubusercontent.com/67759413/111008122-66cff000-835e-11eb-9c21-4c7924ce4fc4.png)
