### ISSUE TITLE
Document how to top up with Fiat

### ISSUE THREAD

**Issue by jamespfarrell** [Giveth/giveth-2#573]
If you create an account with a Torus wallet, you can easily donate with money from your credit card, bank transfer etc.

Simply visit the project page you want to donate to, and click donate.
![image](https://user-images.githubusercontent.com/10499048/108763298-8212c100-7551-11eb-94ee-2bdf941f6e39.png)

On the subsequent popup window that is your Torus wallet:
Click 'Topup'
![image](https://user-images.githubusercontent.com/10499048/108763388-9e166280-7551-11eb-9ddc-cc012bf0870d.png)
![image](https://user-images.githubusercontent.com/10499048/108763420-a7073400-7551-11eb-9e15-8d9e817f042b.png)

Enter the details of how much you want to onramp:
![image](https://user-images.githubusercontent.com/10499048/108763829-1da43180-7552-11eb-8a24-194763e3d0cf.png)

You will be re-directed to the respective payment provider:
![image](https://user-images.githubusercontent.com/10499048/108763965-4c220c80-7552-11eb-8ed0-6c7b5d96512e.png)
 
Your email address will be prepopulated from your Torus wallet
![image](https://user-images.githubusercontent.com/10499048/108764045-61973680-7552-11eb-91f5-b18475544ec9.png)

Your wallet address will be pre-populated from your Torus wallet:
![image](https://user-images.githubusercontent.com/10499048/108764145-812e5f00-7552-11eb-9411-ab1114dfa120.png)

Select your country of residence and your payment options will appear:
![image](https://user-images.githubusercontent.com/10499048/108764345-c5216400-7552-11eb-9201-d4778a0f310f.png)

![image](https://user-images.githubusercontent.com/10499048/108762547-84c0e680-7550-11eb-8fc7-6908bbdc525c.png)

**Comment by Danibelle** [comment]
@laurenluz turned my white board drawings, discussion notes and doc links into a thing of beauty.. 

Question i have, is where would this live 🤔

**Comment by jamespfarrell** [comment]
It's a good question.

This could also take the form of a youtube vide @laurenluz @divine-comedian

**Comment by divine-comedian** [comment]
for now I'm going to plug it into the user guides on the giveth-docs

**Comment by divine-comedian** [comment]
the page is finished and merged to master on giveth-docs. PR is here - https://github.com/Giveth/giveth-docs/pull/13
@geleeroyale marked for review
