### ISSUE TITLE
"Failed to Fetch"

### ISSUE THREAD

**Issue by AnneConnelly** [Giveth/giveth-2#577]
## 📋 Anything to add?

Filled in the new project form and when it was complete, when I clicked "start raising funds" I got this:
 "Something went wrong while adding your project
Failed to fetch
Please report this issue"

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by jamespfarrell** [comment]
This should be resolved, I have emailed Anne.

**Comment by jamespfarrell** [comment]
Giveth/giveth-2#515
Failed to fetch at the last step of project creation
