### ISSUE TITLE
As a dev calculating retroactive GIVBack rewards,  I want to have a good list of donors, donation time & donation USD amounts 

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-2#580]
We want to give out retroactive GIVBacks and to do that we need to know how much every address donated in USD amounts 

OUT OF SCOPE DREAM: It would be cool to do it in $RAI... but probably not worth the drama :-(

**Comment by jamespfarrell** [comment]
I'm sorry I only see this now, maybe this is already useful, if you need it now:
![image](https://user-images.githubusercontent.com/10499048/111188570-785f0500-85b5-11eb-81d3-e9c717a5a04c.png)

Can be done here - https://mainnet.serve.giveth.io/graphql

````
{ 
  donations {
    amount  
    fromWalletAddress
    toWalletAddress
    user {
      name
      email
    }
  }
}
````

**Comment by jamespfarrell** [comment]
Otherwise we could quite easily wrap this into the dapp somewhere

**Comment by GriffGreen** [comment]
Fuck yes! wow do i love graphql 

Is the user name and email publicly queryable? It would be great if only we could query that... I assume that is the case. I always feel weird about linking names to eth addresses, I understand that it might not make sense to avoid the names to address connection that since it will likely be viewable all over the place... but it got me thinking that maybe we should hide the email from the front end completely and keep that for ourselves? Or at least make sure it's optional... as projects probably want to be public about their email

Made an issue just in case it is: https://github.com/Giveth/giveth-2/issues/652

But I assume it isn't an issue and that the graphql service is only accessible by our team

**Comment by divine-comedian** [comment]
testing out the graphQL queries - everything we need to calculate a retroactive GIVback seems to capture properly 
It is however in fact, very public. Transparency, right? I'll consider this closed and for the privacy issue we'll refer to Griff's new issue mentioned above.

![image](https://user-images.githubusercontent.com/67759413/114574180-0676eb80-9c47-11eb-9993-515b7f6f12af.png)

**Comment by mendesfabio** [comment]
yes @divine-comedian! the scripts to calculate GIVbacks can be found at https://github.com/Giveth/givbacks-scripts.
