### ISSUE TITLE
Fetch fiat value of both ERC20 and ETH in a donation

### ISSUE THREAD

**Issue by mateodaza** [Giveth/giveth-2#584]
## 📋 Anything to add?
To finish this issue #518 we need to calculate the current value of every donation in FIAT

It would be best if the donation query brings this value already, so it's mainly a work for the impact-graph and then adapt our frontend

EDIT: It's important to also take in count xDAI, as this feature is a work in progress #543

## ⏰ Urgency/Deadline/Blockers?
critical for mvp

**Comment by divine-comedian** [comment]
price looks good, beam it up!

![image](https://user-images.githubusercontent.com/67759413/110693998-14ec6600-81b6-11eb-939f-1f351d1e4284.png)

**Comment by jamespfarrell** [comment]
@mateodaza I think you could fix this faster

**Comment by divine-comedian** [comment]
I noticed now looking up coins on staging, if my token isn't found it produces the text 'no options' 

however it is in the wrong font. 

![image](https://user-images.githubusercontent.com/67759413/113431970-9183f600-93aa-11eb-8d48-7935eb5ee8c5.png)

**Also** - still same UI error while using COMP 

![image](https://user-images.githubusercontent.com/67759413/113432092-c132fe00-93aa-11eb-8fa6-97a759715b21.png)

**Comment by divine-comedian** [comment]
The UI issue looks to be fixed. Price queries in fiat seem to work well on ETH and mainnet 
![image](https://user-images.githubusercontent.com/67759413/113630297-9c9e8680-9635-11eb-9d68-8cf30a55adf6.png)


on Xdai however it does not display the same as mainnet. the price is not displayed above the input field with its value in USD

![image](https://user-images.githubusercontent.com/67759413/113630535-061e9500-9636-11eb-8131-9ea751a82eac.png)

 it also has trouble finding the prices for xdai tokens outside of PAN or stablecoins.. 
 
 
![image](https://user-images.githubusercontent.com/67759413/113630663-3c5c1480-9636-11eb-9cc2-da196f05aba5.png)

**Comment by mateodaza** [comment]
Here we are only fetching the prices of tokens that are on mainnet, it is related to other issue but we have it considered - For now I'll fix the ETH / xDAI differentiation

**Comment by divine-comedian** [comment]
the network fee quote has been correctly changed to display xDAI while on xDAI instead of Ether. hopefully we'll get price tracking for xDAI in the future! 
![image](https://user-images.githubusercontent.com/67759413/114187913-87b44280-9916-11eb-9c07-0b9d33164d2a.png)
