### ISSUE TITLE
Sort projects by number of hearts

### ISSUE THREAD

**Issue by willyogo** [Giveth/giveth-2#591]
As Giveth admins, we want to ensure the highest quality projects show up at the top of the list. As a quick and dirty solution, sort projects by # of hearts. 

AC:
1. Projects are sorted from greatest to least by # of hearts

**Comment by jamespfarrell** [comment]
I have created a field in the database called qualityScore. It is set to 30 by default. The idea is that it should be a range between 0 and 100. 

We can then use this number to order search queries. 

Ideas for what could contribute are having an image, doing ProjectUpdates, number of donations and of course hearts....

**Comment by divine-comedian** [comment]
@jamespfarrell so to clarify this doesn't sort it by hearts but rather by a score in the database? how do user interactions affect this score?

**Comment by divine-comedian** [comment]
**UPDATE -** Still not being sorted by hearts, needs more clarification on what is being tested and how it can be tested. 
<br>
![image](https://user-images.githubusercontent.com/67759413/111906773-aebed900-8a28-11eb-8d13-6a73557ff237.png)

![image](https://user-images.githubusercontent.com/67759413/111906755-9bac0900-8a28-11eb-8f7b-cc667d8247e2.png)

**Comment by jamespfarrell** [comment]
Merlin tested and this is working

**Comment by divine-comedian** [comment]
On the search bar I can sort by hearts. It seems to sort correctly now. 
I tested this feature while signed it and also while not signed in to an account.

![image](https://user-images.githubusercontent.com/67759413/114570101-8bf89c80-9c43-11eb-98c7-d1b396c914ac.png)

I tested adding a heart to a project and see if it moved up the list on page refresh and it also seemed to update correctly.
