### ISSUE TITLE
Tiny Things no biggie

### ISSUE THREAD

**Issue by CostaBallena** [Giveth/giveth-2#592]
## 📋 Anything to add?
1. When logging in got an error, I believe because I tried to use google sign in and in past had used ID and Pass, however, pooped up a strange acceptance message that I agree to and it worked. Maybe the message text can be edited to be more clear.

2. Maybe add donate link to the dashboard of the project, I wanted to see how it worked and had to go to the home page, then projects then click donate they're instead of open, since it's my project it took me to the back end, which is great, it's just my donate link should be there easy to find and open in a new window. 

3. With slow internet when you click on projects, it originally says zero projects for a moment while it loads then updates. Not sure how but would be nice if the real number reflected quickly while it loads. 
 

## ⏰ Urgency/Deadline/Blockers?

4. Lastly Need credit cards in addition to crypto. I know is in process.
## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by positonic** [comment]
> Maybe add donate link to the dashboard of the project, I wanted to see how it worked and had to go to the home page, then projects then click donate they're instead of open, since it's my project it took me to the back end, which is great, it's just my donate link should be there easy to find and open in a new window.

[broke out into this](https://app.zenhub.com/workspaces/giveth-2-5ecaa273967d386713036ca4/issues/giveth/giveth-2/794)

**Comment by positonic** [comment]
I created a new issue above for the one of these, the first issue we can't do anything about without removing Torus, and I believe that the 3rd one is fixed now
