### ISSUE TITLE
As a project creator, I want Giveth.io to give me notifications via email so I would like to be required to input my email at project 

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-2#596]

**Comment by jamespfarrell** [comment]
Hooks in place, @willyogo  is working on the Auto pilot side

**Comment by jamespfarrell** [comment]
I believe this is done for MVP

**Comment by divine-comedian** [comment]
tried to create a project with an incomplete profile and I get this : 

![image](https://user-images.githubusercontent.com/67759413/111487093-7197d580-870e-11eb-9727-a55ff81300c3.png)

I tried to get around it by clicking a few different create projects buttons on the site and it effectively blocks me until I fill out my profile, looks to work good from the Giveth side.
