### ISSUE TITLE
Revise text blurb on Join page

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-2#598]
## 📋 Anything to add?
Currently:
![image](https://user-images.githubusercontent.com/39466970/110224549-8617da80-7e91-11eb-94a3-604357be9249.png)

Change TO:
**Join our 
Community**
We are Givers and Makers, Living the Future of Giving

Giveth is first and foremost a community. We are people working to build and give well the future we made together. Our project is open-source, decentralized, altruistic, and community-led. As you've made it this far, you are probably a Giver and a Maker too. 

Join one of our platforms below and introduce yourself, so we can welcome you!

## ⏰ Urgency/Deadline/Blockers?
Its definitely for MVP.. hopefully a small and easy change.

## ❓ Why is it important?
The Join page is one of the first ones people will see, the first link we give out for people to get more involved.  

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by divine-comedian** [comment]
@jamespfarrell  still showing old text on join on staging. 

![image](https://user-images.githubusercontent.com/67759413/111502345-2a184600-871c-11eb-8873-9506a685f794.png)

**Comment by jamespfarrell** [comment]
Staging is the same as dev and live, please retest... and if it's still wrong put the right text here, and re-assign. Thanks.

**Comment by MerlinEgalite** [comment]
Super!
