### ISSUE TITLE
Create project

### ISSUE THREAD

**Issue by willyogo** [Giveth/giveth-2#6]
As a user, I want to be able to create a project and save project information.

Required project information:
Name - Max 55 characters
Individual or Organization - 
(Individual or Organization) Name - 
Profile picture - Gatsby photo plugin
Description - Max 2000 characters (Quilljs.com)

AC:
1. A a user inputs information, the info is saved in memory
2. Once a user has input valid info in all required fields and clicks 'Publish', their project info is saved to the DB and associated with their user
3. When a user clicks 'Publish', a new webpage is created ((/projects/[project-name]) that displays all of the user & project information
4. (Feel free to make a PR with AC #1 and #2 and create a separate ticket for this): If a project with the same name already exists, append a number or “Markof” string (star naming) to the end of the project name

**Comment by jamespfarrell** [comment]
I believe these we are following the flows as per the [wire frames found here](https://projects.invisionapp.com/freehand/document/yu24GGzVG) @willyogo ?

![image](https://user-images.githubusercontent.com/10499048/83079651-95edcd00-a07c-11ea-8727-b5c4cb7926d8.png)

We also have Marco [doing cool designs in figma here](https://www.figma.com/file/FBqHg0UfeuaIueDEZG0tBS/Giveth-Design?node-id=601%3A0):
![image](https://user-images.githubusercontent.com/10499048/83079980-49ef5800-a07d-11ea-9dd6-d088bdb89439.png)

**Comment by jamespfarrell** [comment]
So I don't feel that we are super ready to start building anything much regarding the onboarding of projects right now. 

What do you think @willyogo ?

**Comment by markoprljic** [comment]
I created this diagram to map out the complete flow, this should help us define all the screens missing from the initial wireframe and answer any other open questions. It is in the [Figma file](https://www.figma.com/proto/FBqHg0UfeuaIueDEZG0tBS/Giveth-Design?node-id=758%3A0&viewport=217%2C-2834%2C0.44637027382850647&scaling=scale-down), feel free to leave comments there. 

<img width="1146" alt="Image 2020-05-29 at 8 06 28 am" src="https://user-images.githubusercontent.com/5704285/83227615-e05a7100-a184-11ea-8da2-09a9ec3d4973.png">

**Comment by jamespfarrell** [comment]
This has been kind of blocked until we get users saved into the database, 

and also finalised designs. The GraphQL server is set up. Once we connect GraphQL to our front end, we can put projects into the database.

Need a separate ticket for the form to add them to the db....
