### ISSUE TITLE
Update Home Page to include "Community" top center

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-2#602]
![image](https://user-images.githubusercontent.com/39466970/110246613-2830d480-7f1d-11eb-9199-5caab233b393.png)

## 📋 Anything to add?
Yes :)
Add the word "Community" top center where it says "Home" and "Projects"
Home brings you back to this top view
Projects scrolls you down to the Projects
Community link takes you to the bottom, where all the links for all the things live:

![image](https://user-images.githubusercontent.com/39466970/110246693-8067d680-7f1d-11eb-8270-9797083fbbda.png)

## ⏰ Urgency/Deadline/Blockers?
Prefer to have it at launch, should be a simple one!

## ❓ Why is it important?
Should see how to learn more about Giveth and get involved right from the top/home page

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by geleeroyale** [comment]
Hmmm - I am not sure about the link target. What do others say? Should we go along with Dani's suggestion here, or not (or make a small change) - i.e. I would link to the `join` page instead of directing people to the footer.

@markoprljic

**Comment by markoprljic** [comment]
If it has to be in the main navigation then it should link to Join our community page, as @geleeroyale pointed out.

**Comment by jamespfarrell** [comment]
@markoprljic can this be closed, or what happens next?

**Comment by markoprljic** [comment]
@jamespfarrell I don't see the Community link in the main nav and linked to Join page. When this is done please close the issue.
