### ISSUE TITLE
Home Page Update: Make Sign In more noticeable like the Donate Button

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-2#603]
![image](https://user-images.githubusercontent.com/39466970/110246822-06841d00-7f1e-11eb-9549-fb6f142e704c.png)

Donate is a big Pink button at bottom, but eye is drawn first to Create a Project at top right because the text is so much bigger than Sign In, which looks like a bit of an after thought in tiny letters next to it.

Can we make "Sign In" a pink button like Donate , just sized appropriately where it is next to "Create a Project"?

## ❓ Why is it important?
Encouraging visitors to the site to Sign In as a first step if they aren't ready to hit the big Donate button just yet.. once you have an account, next time visitors will be more likely to make a donation.

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by markoprljic** [comment]
@mateodaza Maybe instead of full-color button it's better to have an outline button.
![Image 2021-03-15 at 5 26 30 pm](https://user-images.githubusercontent.com/5704285/111186791-a6434a00-85b3-11eb-8148-79deca7fd0c5.jpg)

Once implemented please close the issue.

**Comment by Danibelle** [comment]
Thanks Marko!

**Comment by markoprljic** [comment]
@mateodaza or @MerlinEgalite One of you take it from here?

**Comment by MerlinEgalite** [comment]
Can do it if you want @mateodaza !

**Comment by mateodaza** [comment]
Go! :D
