### ISSUE TITLE
Community Curation via "Flagging" inappropriate projects

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-2#604]
We love the Hearts! And need Flags!

Community Curation needs upvoting AND downvoting.
Idea is that the Projects should sort by hearts, which add a point..
and flags are minus a point.

So we can also auto hide a project if it gets 3 flags.. but this should probably have a notification process behind it.
While we probably don't need to notify project owners when they get a heart, too much.
We probably SHOULD notify a project owner when they get a flag, that has a 1 of 3, 2 of 3..
Then at 3 of 3, notification that your project has been hidden.

Notification can direct Project Owners to join the Project Onboarding channel on Discord to appeal their flag.
This might be a pop up when they sign in?
Or a message on their Account page?
And an email too..

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by Danibelle** [comment]
I saw that @jamespfarrell proposed a point system for actions taken on projects..

That would probably replace the 3 flags you're out suggestion in this issue..

For notifications, it could make sense to keep it at the count instead of explaining the points.

**Comment by Danibelle** [comment]
Was this resolved by the score functionality @jamespfarrell ?

**Comment by Danibelle** [comment]
Great thank you! I'm trying to catch up on how to appropriately label, tag, assign or otherwise place my issues to be reviewed and prioritized...  apologies if I'm not doing right!

**Comment by MerlinEgalite** [comment]
Is something like Kleros Curate too complicated to implement?
The goal of this is to create curated lists in a decentralised way.
https://curate.kleros.io/
