### ISSUE TITLE
Clicked on Diamante Bridge project image, got blank screen

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-2#609]
URL shows correctly but nothing loaded: 
![image](https://user-images.githubusercontent.com/39466970/110516399-60bbe400-80be-11eb-97ed-fdd43646b978.png)

Clicked refresh page, still nothing.

Back button to Projects
Used the pink learn more button..
Still blank:

![image](https://user-images.githubusercontent.com/39466970/110516559-952fa000-80be-11eb-800f-3f7848927a80.png)

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by jamespfarrell** [comment]
Can't replicate. Please retest and re-open if still and issue
[link](https://giveth.io/project/diamante-bridge-collective/)
