### ISSUE TITLE
"Likes" or "hearts" on projects disappear after refresh

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-2#615]
## 📋 Anything to add?
Testing on staging. I tried to "liked" all the first projects

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/223c4542-7003-4c05-b40c-0a8d65b525f4)

Then I clicked "show more projects" and scrolled back up and all my hearts disappeared:

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/06320c83-148f-4036-baba-484340707c7f)

My hearts also disappear when I refresh the page or when I navigate to another project and go back to the home page. They also disappear when I like a project on its project page and then refresh the page there. Basically, the hearts aren't sticking.

**Comment by mateodaza** [comment]
I believe this is related to them being server side rendered - will give it a look

**Comment by divine-comedian** [comment]
looks to be fixed! wow so many hearts... One thing I noticed @mateodaza  is that there is a 1-2 second lag from when the page loads after refresh to when my hearts pop up

![image](https://user-images.githubusercontent.com/67759413/110814433-70226500-8257-11eb-98ab-ecf4a7d62cd4.png)

**Comment by mateodaza** [comment]
Yeah, the first load comes from the server and then I check the latest changes - it's gonna be like this until we figure out a schedule to rebuild the site!
