### ISSUE TITLE
Always 2 account changed messages

### ISSUE THREAD

**Issue by jamespfarrell** [Giveth/giveth-2#616]
Every time I change my wallet, I get 2 messages:
![image.png](https://images.zenhubusercontent.com/5807a7a095e42b6c5baabbd3/06c77a41-be59-4340-9b09-bfcce921fddc)

Seems like an even listener is being created twice

**Comment by divine-comedian** [comment]
@jamespfarrell  
**only 2?** bro ur game is weak. - I get this when I try to log in with metamask from the wrong chain
brave browser, clean cache and cookies.
![image](https://user-images.githubusercontent.com/67759413/112015179-f7969080-8b01-11eb-91ee-462862b4fed3.png)

**Comment by mateodaza** [comment]
hahaha I got this 🤣

**Comment by mateodaza** [comment]
relates to #561
