### ISSUE TITLE
Incorrect styling of default images on add project page

### ISSUE THREAD

**Issue by jamespfarrell** [Giveth/giveth-2#617]
![image.png](https://images.zenhubusercontent.com/5807a7a095e42b6c5baabbd3/d7ec4f12-fbb9-4645-8977-aadd51a3e6b5)

**Comment by mateodaza** [comment]
I wasn't able to replicate. But added transparent background just in case - @jamespfarrell please test again when staging is up to date

**Comment by jamespfarrell** [comment]
Only I can see this apparently... so closing for now

**Comment by laurenluz** [comment]
Wait, no - this is still happening!

![image](https://user-images.githubusercontent.com/75490971/111487205-c5e68980-86fd-11eb-9dd3-f08bcd45e0b0.png)

**Comment by divine-comedian** [comment]
### TESTED 
Looks great, pink borders no longer appear
 - tested on brave, clean cache and cookies

![image](https://user-images.githubusercontent.com/67759413/111674198-222ad580-87f2-11eb-999a-3f40adb3ca73.png)
