### ISSUE TITLE
Adding project updates doesn't show them on the page

### ISSUE THREAD

**Issue by jamespfarrell** [Giveth/giveth-2#619]
Created updates on my project, I received no message, and no error, but nothing appears

![image.png](https://images.zenhubusercontent.com/5807a7a095e42b6c5baabbd3/9b645e07-a296-45b7-b402-fd633f2993d5)

When I refresh the page, the updates do appear.

**Comment by divine-comedian** [comment]
looks to be all good! for the updates sticking after refresh. @mateodaza  have some important UI feedback that I will create an issue for.

![image](https://user-images.githubusercontent.com/67759413/110815278-4e75ad80-8258-11eb-90b4-f328dc97e228.png)
