### ISSUE TITLE
Clickable areas extend past the appropriate confines

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-2#620]
## 📋 Anything to add?
On staging, if you click on the blank spot in the centre of the projects page it brings you to create a project flow:

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/b3132e26-d69c-4038-a97e-20f94a0f11e4)

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/aef71531-0b11-46dc-8499-5e1edcf46f9a)

**Comment by mateodaza** [comment]
well spotted!

**Comment by geleeroyale** [comment]
we should probably highlight the element with `:hover` as Laurens comment is not fully true - at least for account. The cursor changes beween sections like it should, but because the elements are quite large I understand why the user might be confused what they are clicking

**Comment by laurenluz** [comment]
right sorry, I just meant that there are clickable parts throughout that whole area, it does change between sections, but each section extends out through the whitespace next to it. Makes it sort of awkward and easy to accidentally click and navigate away from the page unintentionally.

**Comment by divine-comedian** [comment]
appears to be fixed! I tested the areas around all the other clickable areas on the home page and they look to be roughly what they should be.
