### ISSUE TITLE
Allow login with Metamask on xDai chain

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-2#621]
## 📋 Anything to add?
currently when I try to log in with metamask on the xDai chain I get thrown this error

![image.png](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/d623ed16-a2ca-4f82-b8ea-e8551d521523)

and it closes the metamask window and prevents me from logging in

**Comment by markoprljic** [comment]
Log in direclty with whatever netwtork and then change network if you want,.

**Comment by divine-comedian** [comment]
Wow! hella slick, no hiccups logging into giveth while connected on xDai - Great work Mateo! 
tested brave, clean cache w/ metamask
![xdailogin](https://user-images.githubusercontent.com/67759413/112653213-941fa200-8e24-11eb-8294-033082989258.png)
