### ISSUE TITLE
Donate with Crypto - Token List revisions 

### ISSUE THREAD

**Issue by markoprljic** [Giveth/giveth-2#623]
## 📋 Anything to add?

1. Include the token icon in the list
2. Remove the full token name, keep just the symbol 
3. Change text "Enter your [token] amount" to be generic for all and to read "Enter amount"

![Image 2021-03-11 at 8.17.02 am.jpg](https://images.zenhubusercontent.com/5cc090818b624e26c3734d75/065c1b38-0e61-436c-91b8-2f261f186010)

## 🤼‍ Reviewer

@markoprljic 

## 🔗 Work doc - inspirational links

Crypto icons resources:

https://github.com/Coinomi/crypto-icons
https://github.com/spothq/cryptocurrency-icons
https://cryptologos.cc/

**Comment by markoprljic** [comment]
Also, check if we're supporting all tokens in the list, also based on the network selection.

**Comment by divine-comedian** [comment]
checking out the icons on mainnet - @mateodaza  So i hear you're a MATIC fan... 
![image](https://user-images.githubusercontent.com/67759413/113509689-03804a80-9525-11eb-951f-63fa3af1c29e.png)

There's very little to no image icons for the popular coins on xDAI network - HNY, AGAVE, xDAI, PAN...
![image](https://user-images.githubusercontent.com/67759413/113509767-5a861f80-9525-11eb-9d5c-cd693fb75c46.png)

**Comment by mateodaza** [comment]
Lol blame the package https://github.com/spothq/cryptocurrency-icons we can suggest them to add the missing logos but so far I can add them apart from the library

**Comment by divine-comedian** [comment]
Yes I can help you find some resources today, what do you use for svg editor? @mateodaza

**Comment by mateodaza** [comment]
I'm not usually edition svg lol if I do I go directly to the code - You can give me PNG files too if you get them I'll hardcode them!

**Comment by WhyldWanderer** [comment]
@mateodaza @divine-comedian..
I think you should be able to retrieve them through coingecko
![image](https://user-images.githubusercontent.com/74267818/114081531-e7084900-9869-11eb-904c-fd80666bd653.png)

**Comment by divine-comedian** [comment]
@mateodaza  here's a couple pngs for the most common ones we can expect
[xdai token photos 50px.zip](https://github.com/Giveth/giveth-2/files/6287077/xdai.token.photos.50px.zip)

**Comment by mateodaza** [comment]
GREAT! Will add them up - thank you man

**Comment by divine-comedian** [comment]
xDAI tokens are looking hella slick!

![image](https://user-images.githubusercontent.com/67759413/114576363-1099e980-9c49-11eb-9a0a-305085b745b6.png)

MATIC looks like it calmed down as well. 
![image](https://user-images.githubusercontent.com/67759413/114576459-2a3b3100-9c49-11eb-8aff-496a58e02c6f.png)
