### ISSUE TITLE
As a user I want to edit my project update

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-2#624]
## 📋 Anything to add?
Hi there, I made a big embarrassing typo on my project update and how do I fix it! 
It would be nice to be able to edit and delete project updates and also be able to go right into project updating from the 'my projects' page.
![image.png](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/826f7804-27ac-4ea6-925f-c0680822abcd)

Also maybe more tricky would be able to use markdown in my project description and project updates text fields. 
![image.png](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/561770ab-df2c-4d9c-9987-e9963f123a85)

**Comment by laurenluz** [comment]
https://github.com/Giveth/giveth-next/issues/44
