### ISSUE TITLE
Segment - Donation received track event

### ISSUE THREAD

**Issue by willyogo** [Giveth/giveth-2#638]
Whenever a user donates to a project, the 'donation received' event is triggered with the projects UserID and relevant details about the donation included as properties (asset donated, amount donated, project name, project URL)

**Comment by divine-comedian** [comment]
@willyogo @jamespfarrell  Currently there is no separate event tracked for 'user donating to project' and 'project being donated to' is it just one event with all the info. Is this the intended function? Please refer to https://github.com/Giveth/giveth-2/issues/637 for updates on user testing for this feature

**Comment by jamespfarrell** [comment]
From my perspective when something happens we only raise that event once. We can react to that event in 2 different ways, but that should happen on the segment side. 

We would only have 2 different events if completely different data was needed for the 2 things you reference, and even then we would likely keep one event with 2 types of data.

**Comment by willyogo** [comment]
In order to send projects an email when they receive a donation, we need to trigger a segment event with the userID of the project. It can have all of the same properties as the 'Made Donation' event, but the userID should be the project owner's rather than the donors. We currently have both the `Project Updated - donor` and `Project Updated - project` events, can we do the same thing here?
