### ISSUE TITLE
Revise Text on Giveth Project at Giveth.io

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-2#639]
Text is outdated..  featured blurb/first sentence references v2.giveth.io

![image](https://user-images.githubusercontent.com/39466970/111042330-be6b6b80-83f1-11eb-860a-8bf01db021a7.png)

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by laurenluz** [comment]
Notes from dev call 2021-03-14
@Danibelle to write updated text and pass to
@jamespfarrell to change in db

**Comment by Danibelle** [comment]
The Future of Giving is Now! 

We have softly launched our second dApp from the Giveth Community of Makers, this free, open-source, and decentralized application for peer-to-peer donations you are using right now.  

💜 Donations such as yours are our primary source of funding and are deeply appreciated! 

In the current evolution of Giveth we're building upon firsthand experience gained through developing, maintaining and improving our original flagship dApp (live at beta.giveth.io). For 3+ years, all funding for Giveth has been tracked transparently, securely and accountably using the full-featured version with DAC’s, Campaigns and Milestones.

This new dApp is starting out with a simple purpose: 
💜 For Givers: Offer the best experience for anyone looking to donate to a cause, whether with crypto or a credit card. 
💜 For Makers: Enable project creators anywhere in the world to start accepting donations in a few minutes, with zero fees and zero censorship. 

We know that the future is what we make it, and at Giveth everyone is a Giver AND a Maker..
Your questions, suggestions and preferences are needed to guide the team in deciding what features and functionality to build next. 

Ways to contribute:
Donate today and feed the team!
Click the “Feedback” button to submit your ideas!
Join the conversation on Discord so we can welcome you personally to the Future of Giving!

**Comment by divine-comedian** [comment]
@jamespfarrell  @Danibelle text appears not to have been updated yet on giveth.io is the text finalized? orr...?

![image](https://user-images.githubusercontent.com/67759413/111534030-e33b4800-873d-11eb-9432-4b57c6588efb.png)

**Comment by Danibelle** [comment]
I rewrote it and just put the comment up this morning .. might have missed James' db update window... 

If I heard correctly this is hard-coded and can't be edited on the dApp.

**Comment by Danibelle** [comment]
Make me an owner so I can dooooo it!!
@jamespfarrell

**Comment by Danibelle** [comment]
OK project shows up in my list now! And I edited it!
But the edits don't show up right away.

If edits have a delay we should give a pop up that says your changes have been received and will show up in/after XXXX

**Comment by Danibelle** [comment]
I'm happy, thank you @jamespfarrell !
Closing issue.
