### ISSUE TITLE
Segment issue on saveDonation mutation: 'Your message must be <32kb'

### ISSUE THREAD

**Issue by mateodaza** [Giveth/giveth-2#640]
## 📋 Anything to add?

![image.png](https://images.zenhubusercontent.com/5f7dde8da5e87776be5215af/3b3b13e3-4172-4a34-a203-98d41db5bbb0)

## ⏰ Urgency/Deadline/Blockers?
Blocker of main process, pretty urgent

**Comment by jamespfarrell** [comment]
I believe this will be resolved since we removed the image from the project, let's re-open if we see it again.
