### ISSUE TITLE
Tell the user that they need to sign in as opposed to just having a spinning wheel

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-2#642]
## 📋 Anything to add?

This is a common issue, metamask asks for the user to sign but sometimes, for various reasons, the pop up doesnt pop quite enough ;-) and that little number on the fox only is noticeable to the most savvy of users.

Ideally there would be some good text below the spinning wheel that says something like "Waiting for verification from your favorite crypto wallet" 

<img width="1108" alt="Screen Shot 2021-03-14 at 12 39 43 PM" src="https://user-images.githubusercontent.com/14945613/111081022-8f441f80-8501-11eb-9d34-7c6299ffa1bd.png">

## ⏰ Urgency/Deadline/Blockers?

NONE

## ❓ Why is it important?

User confusion

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by markoprljic** [comment]
@MerlinEgalite Wanna add a modal saying Metamask wallet loading and putting the spinner there. We have existing modal views that can be reused.

**Comment by MerlinEgalite** [comment]
<img width="1440" alt="Screenshot 2021-04-16 at 17 41 28" src="https://user-images.githubusercontent.com/44097430/115056612-5d98ec80-9ee3-11eb-858a-19f324a68cd7.png">

@markoprljic 
What wording do you want on the popup? And tell me if you want to make some changes on the design too.

**Comment by markoprljic** [comment]
Looking good.

I'd change the text to read:

Title: Opening Metamask ...
Subtext: Metamask should open in a moment, please confirm your sign in.

Maybe someone could help with the language here? @laurenluz @divine-comedian ?

**Comment by laurenluz** [comment]
What about this....

Title: Connecting to Metamask
Subtext: Please confirm sign in through your MetaMask popup window.

**Comment by markoprljic** [comment]
Yes!

**Comment by MerlinEgalite** [comment]
Good! Then we stand for @laurenluz 's wording? @markoprljic @divine-comedian

**Comment by markoprljic** [comment]
Yes, go! Close! 😁

**Comment by divine-comedian** [comment]
any updates here? testing on staging, not signed in yet with MM. 
I still see the spinning wheel, there is no popup as proposed prompting me to check my metamask.

![image](https://user-images.githubusercontent.com/67759413/117469581-e5db4200-af23-11eb-9e80-fbd33c5ab439.png)

@MerlinEgalite

**Comment by MerlinEgalite** [comment]
Perhaps it's not on staging.. @mateodaza did you merge it from develop to staging?

**Comment by laurenluz** [comment]
this is fixed on live

![image](https://user-images.githubusercontent.com/75490971/121407253-5955e200-c91c-11eb-8c30-a6ee35a13a01.png)
