### ISSUE TITLE
Error updating project profile - is this supposed to be an email field?

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-2#644]
Trying to change my last name, and get this error:

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/fed0257e-8dbc-4b61-bdd7-1a036d2ec27d)

It says "email" in the error so then I tried to put in an email address to see if maybe the field titled wrong, but I got the exact same error.

**Comment by laurenluz** [comment]
I'm getting the same error when I try to update any of the fields - FYI

**Comment by divine-comedian** [comment]
i tried reproducing Lauren's error, I can go in on a fresh profile and add info no problem. However when I want to edit that info things start getting funny. I get an error right away if I try to change anything in the email field, says invalid address and it will autofill with old email info and undo any changes I made to the other fields.
![image](https://user-images.githubusercontent.com/67759413/111489899-f2f06780-8710-11eb-9c91-fa6c96b4250c.png)

![image](https://user-images.githubusercontent.com/67759413/111490534-7dd16200-8711-11eb-820d-e0200f83a13f.png)

I try to change my name or other info and it appears on my profile but when I go to edit my profile again it's been autofilled with my old info. 

![image](https://user-images.githubusercontent.com/67759413/111490651-93468c00-8711-11eb-93fc-ffde66a1bd04.png)

**Comment by laurenluz** [comment]
Just want to add to this... I also can't seem to delete info from my profile. Like if I want it not to show my last name for example... I go in, delete it, hit "save", get the message "your profile has been updated successfully"... but it doesn't change. After refresh too, my last name is still there

![image](https://user-images.githubusercontent.com/75490971/112203040-b2dd2900-8bd7-11eb-9540-b61f5c70235c.png)

![image](https://user-images.githubusercontent.com/75490971/112203077-bd97be00-8bd7-11eb-8405-a338eb8d6ab6.png)

**Comment by mateodaza** [comment]
Thanks guys for the reports! - I'm working on it :)

**Comment by divine-comedian** [comment]
Awesome work, some of these issues seem to be resolved. 
I tested: 
 - Updating all fields. Works fine and updates correctly without having to refresh
 - Leaving all fields or some fields blank. Updates correctly and throws warning to require at least one field to be filled in. Updates correctly without refresh
 - Leaving some fields empty, updating others - Profile updates correctly without refresh and repopulates info correctly in text fields if I go in again to update profile. 
 
 **BUT ONE MORE THING**
 The name at the top of the update profile field does not update with the rest when I put in new info. It does however update correctly after a page refresh. 
 
 
![image](https://user-images.githubusercontent.com/67759413/112655191-866b1c00-8e26-11eb-9232-4b9a3714787a.png)

**Comment by mateodaza** [comment]
working on develop branch, coming next update

**Comment by divine-comedian** [comment]
the last issue here seems to be working now - name changes once I update the field and it no longer requires a page refresh, **Very Nice!** 
![image](https://user-images.githubusercontent.com/67759413/113428645-28e64a80-93a5-11eb-8379-8f3a5c159a9c.png)
