### ISSUE TITLE
Add "search" function to projects page. Also "Filter" and "Sort"

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-2#645]
## 📋 Anything to add?
As a user, would be really useful to search for a particular project

Related: would be amazing to allow the user to "filter" or "sort" projects (e.g. by date added, number of likes, number of donations, category, etc.)

This is related to these issues about filtering and sorting: #591 #635

## ⏰ Urgency/Deadline/Blockers?
Nice to have

## ❓ Why is it important?
As it is now, on staging with only 25 projects it's already pretty tedious to scroll and hit "see more project" over and over to find the one I want to donate too.

**Comment by jamespfarrell** [comment]
https://github.com/Giveth/giveth-2/issues/31

**Comment by divine-comedian** [comment]
Looking really good at the base level it seems to work as intended. Some Feeback - @mateodaza 

In the category list it would be good to have a side scroll bar on the list itself. I have to actually scroll down the whole page to view the list. 

![image](https://user-images.githubusercontent.com/67759413/113430487-436df300-93a8-11eb-9fd2-5f7cddc76e8c.png)


**Also** - I would avoid mentioning 'Quality Score' until we have the criteria set and documented somewhere publicly @jamespfarrell  thoughts? 

lastly, the font in the search bar is different than the font in the other text fields -for example the profile text input fields. 

![difffontsgiveth](https://user-images.githubusercontent.com/67759413/113431138-49180880-93a9-11eb-9670-b1154dfb1a0d.png)

**Comment by mateodaza** [comment]
awesome feedback, makes all sense

**Comment by divine-comedian** [comment]
We have scroll bars! The font looks fixed and we changed our wording to 'Default' instead of 'Quality Score'. This works fantastic, nice job Mateo! 

![image](https://user-images.githubusercontent.com/67759413/113629942-1d10b780-9635-11eb-9b5c-21184c9b6aa0.png)

**Comment by Danibelle** [comment]
I have been testing the sort and filter on both staging and prod, finding these issues on both:
https://github.com/Giveth/giveth-2/issues/749
https://github.com/Giveth/giveth-2/issues/750
