### ISSUE TITLE
Projects page not correctly displaying projects - number of projects is wrong and Giveth doesn't show up

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-2#646]
## 📋 Anything to add?

It says "PROJECTS (25)" - when I can count 27 projects on the page...
Also Giveth does not show up on the projects page at all, even if I go all the way to the bottom hitting "Show more projects"

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/9a048a12-c592-47a2-abf1-c74ceafceeee)

**Comment by laurenluz** [comment]
fixed!

**Comment by laurenluz** [comment]
oh no... this is happening again now. I count 24 projects...

![image](https://user-images.githubusercontent.com/75490971/111509498-65ae1280-8712-11eb-8504-3a809ac22edc.png)

**Comment by divine-comedian** [comment]
I loaded up all the projects and counted 35 which matched the number in the corner parenthesis.. looks to be good except..

![image](https://user-images.githubusercontent.com/67759413/111634475-ef221b00-87cc-11eb-8720-d2db87b7a8b1.png)
<br>
When you first load the page it show's up **(38)** very briefly then goes to 

![image](https://user-images.githubusercontent.com/67759413/111634545-0234eb00-87cd-11eb-8b07-82f505311cee.png)
