### ISSUE TITLE
Allow user to crop image to choose which part of the image to include in the project banner

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-2#647]
## 📋 Anything to add?
If the user uploads a portrait-oriented image, would be useful to allow the user to crop the image so it appears pleasingly on the project banner. Not like this one which was support to a picture of my dog... We have this as a feature in Giveth TRACE
**![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/dfcc48ef-93eb-4e3c-9095-78ffd75e267a)**

**Comment by markoprljic** [comment]
Related https://github.com/Giveth/giveth-2/issues/764

**Comment by positonic** [comment]
I got feedback from a user that this was a problem for them, and I saw that it cut off the heads of people

**Comment by markoprljic** [comment]
When user uploads image from the computer we want to allow them to crop, scale, position the image.
I created a mockup to see how it will fit the flow and show the general design direction (does not have to strictly follow it).

![Image 2021-04-26 at 4 52 50 pm](https://user-images.githubusercontent.com/5704285/116104039-6bebc300-a6b0-11eb-82d3-13e8b6e004dd.jpg)

**Comment by laurenluz** [comment]
@markoprljic that looks really good. Just wondering though... should we have two cropping options? because we have the wide/short image for the project banner on the project's own page... and then the less wide image for the project on the "projects" page.

Maybe we can have like a crop within a crop? like two concentric rectangles that are labelled indicating where they will be?

![image](https://user-images.githubusercontent.com/75490971/116121918-578ed280-a67e-11eb-87e7-bf95b06a07ce.png)
![image](https://user-images.githubusercontent.com/75490971/116121869-4c3ba700-a67e-11eb-9dc2-9853e44abf18.png)

**Comment by markoprljic** [comment]
I don't think we should be adding any advanced image editing options other than just cropping the main project banner. The project card image should automatically be cropped.

**Comment by markoprljic** [comment]
Design here https://github.com/Giveth/giveth-2/issues/803
