### ISSUE TITLE
Can't make a profile.. maybe because i didnt want to include a website?

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-2#648]
## 📋 Anything to add?

I fill it in like this
![Screen Shot 2021-03-14 at 7 43 35 PM](https://user-images.githubusercontent.com/14945613/111090538-5b342300-8530-11eb-97b9-496126a31315.png)

And i get this
![Screen Shot 2021-03-14 at 7 43 40 PM](https://user-images.githubusercontent.com/14945613/111090536-596a5f80-8530-11eb-9692-8f92817a5641.png)

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by GriffGreen** [comment]
No luck on adding the website either :-/

**Comment by mateodaza** [comment]
Oh now the email field is required, that's why it's not letting you pass - I will update the front end first thing tomorrow. Glad you noticed it!

**Comment by divine-comedian** [comment]
I just created a fresh account with metamask, no problem filling out my profile without an email or website.

![image](https://user-images.githubusercontent.com/67759413/111503387-16211400-871d-11eb-9c1e-f900292fd0fd.png)
