### ISSUE TITLE
Unable to heart projects

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-2#649]
I am unable to heart projects on staging.
Whether I am on the projects page or in the project description page, it makes no difference.

**Comment by WhyldWanderer** [comment]
signed out, cleared cache, and signed back in and am now able to heart projects.

**Comment by divine-comedian** [comment]
hearts look to be working fine for me, except that they are a bit slow to show up. 

![image](https://user-images.githubusercontent.com/67759413/111505005-8c724600-871e-11eb-9972-a0ec57d797ad.png)

![image](https://user-images.githubusercontent.com/67759413/111505100-a744ba80-871e-11eb-970b-120a71e1237b.png)
