### ISSUE TITLE
Guidelines for testers

### ISSUE THREAD

**Issue by jamespfarrell** [Giveth/giveth-2#650]
For bugs, please use the 'Bug' label, and put the issue in the New Issues column.

## Test cases:

In order to make sure that we have full test coverage we will define user stories that define certain roles and actions that different users take:

An example of a formal test case template would look like this:
![image](https://user-images.githubusercontent.com/10499048/111191279-308dad00-85b8-11eb-910b-537ab3d35f6f.png)

Test cases.

### Project owner

- Create project
- Edit project
- Deactivate / reactivate

### Donors

Logged in
- Metamask
- Torus
- 
Not logged in

**Comment by laurenluz** [comment]
Ok so some more test cases/flows:

Create project
- project details
- upload image / image formatting
- location selection / global impact
- google maps selection
- check that projects are all listed in "my projects"
- check that projects show up on homepage
- deactivate/reactivate project

Edit Project
- Change photo
- Change text fields
- Check that updates are applied

Edit Profile
- Name, Location, Website
- Email ?

Donor
- donate in different tokens: ETH, ERC20, Mainnet, xDai
- donate with alternate wallets (other than sign in)
- check that funds leave wallet
- check that funds received/tracked by project

General
- "Liking" projects
- Sharing via Social
- All links on homepage
- Signup for newsletter
- "My wallet"
- Report a Bug
- Sign in/sign out

**Comment by laurenluz** [comment]
Hm... so I created something rough in the Notion:

https://www.notion.so/giveth/c02da68707974771948ac8da25ed465e?v=86ca8990bfe049ed91e6e71f7297d5be

Open to feedback/additions

**Comment by divine-comedian** [comment]
**FEEDBACK FOR GIVETH TESTING GUIDELINES**
**For Project Creators**
updated donation address
choose category
publish update
**For Donors**
view donations made (correct $$ amount, correct currency type)
**Explorer**
Projects appear in projects list

**Comment by laurenluz** [comment]
@jamespfarrell & @laurenluz to bring this to a final state... assign different flows to individual testers, ensure that we have organized, thorough, testing

**Comment by positonic** [comment]
Mitch, I assigned you to this, since you mentioned wanting to review it

**Comment by laurenluz** [comment]
@divine-comedian I summarized our testing guideline issues into hackMD so we can update what we have on the giveth docs: https://hackmd.io/17WUHH9MQYufyP4cLQ81Gg?both

Basically, we discussed, then I made that notion doc and James improved upon it all by splitting it up into GitHub issues #798 #799 #800 that can be assigned tested, closed and then reopened with each corresponding each sprint.

Merlin has been working on automated tests and I think has Create Project pretty down, doesn't think he can do it for Donor and will be able to partially automate the General Scenario.

Let me know if you want to discuss further

**Comment by divine-comedian** [comment]
Document is live on https://docs.giveth.io/docs/testing-guidelines/

**Comment by laurenluz** [comment]
Cool... should we have someone review this? Or can we close the issue? @jamespfarrell
