### ISSUE TITLE
FIX ME ASAP: Signed up to newsletter - received super outdated email

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-2#651]
## 📋 Anything to add?
I just put my email into the "sign up for our newsletter" field on staging and got this email. I tested on giveth.io and also got the same result.
This is super duper outdated, and we should really fix it ASAP.

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/ee22b9ba-9b04-48f7-829a-ec636c2d6cd4)

This was the entry field:
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/3f4423ef-4d60-4111-b348-c7f533fd8193)

**Comment by geleeroyale** [comment]
great find @laurenluz - totally agree

**Comment by geleeroyale** [comment]
Willy deactivated sending - I will close this in favor of building proper email journeys
