### ISSUE TITLE
Need to fetch hearts by ajax after page load

### ISSUE THREAD

**Issue by jamespfarrell** [Giveth/giveth-2#654]
I think we can go live without this, but labelling at critical for attention...

First load
![image.png](https://images.zenhubusercontent.com/5807a7a095e42b6c5baabbd3/985dc37c-b71c-4eb2-8ee1-5d26b1467387)

Click heart:
![image.png](https://images.zenhubusercontent.com/5807a7a095e42b6c5baabbd3/f2953b64-38ae-4b10-bedf-f1daa0f89a1d)

Refresh page:
![image.png](https://images.zenhubusercontent.com/5807a7a095e42b6c5baabbd3/ff823233-ae4e-428b-aa24-dbc549bb1aac)

**Comment by mateodaza** [comment]
This is solved, just a bit slow :(
I wanna look for a way to do it better

**Comment by divine-comedian** [comment]
### TESTED
Hearts are working fine! yes they load a bit slow but they do appear correctly after refresh.
 - tested on brave/torus clean cookies and cache 
![image](https://user-images.githubusercontent.com/67759413/111676534-a5e5c180-87f4-11eb-9884-a1470c9be426.png)
