### ISSUE TITLE
As a user I don't know what these logos are, and need more info...

### ISSUE THREAD

**Issue by jamespfarrell** [Giveth/giveth-2#655]
Its says click there to start raising funds, but then I see this...

If I don't know about crypto it's not clear to me that I can create a wallet with an email account using Torus...

I just see 2 logos I don't know...

![image](https://user-images.githubusercontent.com/10499048/111234741-83368b80-85ef-11eb-80d0-84e9b86a4a7b.png)

Can we improve this?

**Comment by markoprljic** [comment]
@jamespfarrell Is this more clear now? 
Idea is to show upfront the options Torus offers but make all of them when clicked just open the Torus popup.

![Image 2021-03-25 at 8 29 20 pm](https://user-images.githubusercontent.com/5704285/112532286-f2a73a80-8da8-11eb-8968-000ba76d303a.jpg)

**Comment by GriffGreen** [comment]
love it

**Comment by WhyldWanderer** [comment]
I just received first time user feedback stating that this was also confusing for them and then I found this issue.
Awsome to know that its already in the works!

**Comment by markoprljic** [comment]
So I'm seeing that we need to focus on Web2 mental models first and Web3 second, meaning we should offer a traditional sign up / Sign in process with the addition of Web3 capabilities (wallet connect).  

We could potentially swap the position of sign in options and highlight the traditional options. 

Example Audius:

![Image 2021-04-11 at 1 04 10 pm](https://user-images.githubusercontent.com/5704285/114301922-1798ee80-9ac7-11eb-8a4a-c64da8565dbe.jpg)

**Comment by GriffGreen** [comment]
<img width="701" alt="Screen Shot 2021-04-14 at 8 28 25 AM" src="https://user-images.githubusercontent.com/14945613/114736969-ddd61b00-9d46-11eb-9bdc-b54f09bcbf12.png">

**Comment by markoprljic** [comment]
@mateodaza Let's swap positions for sign in options like shown below:

![Image 2021-04-15 at 8 26 31 am](https://user-images.githubusercontent.com/5704285/114823854-59c27880-9dc4-11eb-863d-5495250dd50c.jpg)

Make the whole upper section trigger Torus and user will select the sign in option there. 

![Image 2021-04-15 at 8 29 11 am](https://user-images.githubusercontent.com/5704285/114824479-377d2a80-9dc5-11eb-9b47-95a012be4e34.jpg)


Show Metamask option regardless of having it installed or not. If not installed redirect to download Chrome extension. 

![Image 2021-04-15 at 8 31 59 am](https://user-images.githubusercontent.com/5704285/114824487-3b10b180-9dc5-11eb-9f73-7d6277842528.jpg)

**Comment by mateodaza** [comment]
Gotcha

**Comment by laurenluz** [comment]
oooh I love the new UI looks great:

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/5ebbe138-6eee-4b01-84b8-cf83065511fd)

I tested by clicking all the buttons, found an issue:

the mail and twitter buttons:
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/a7a145b0-3f58-4977-8e20-3a7d3bb57f1d)

lead to this
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/01d41047-cfe2-4358-8d0b-1c7f328c0e6e)

also, I think it's redundant to have a google and mail as two options if they will both lead to gmail? or is the mail going to go somewhere else...?

the other buttons work as expected

**Comment by mateodaza** [comment]
Not broken, torus doesn't allow direct login with e-mail and twitter - It's redundant but it's all we are able to do so far

**Comment by mateodaza** [comment]
Related to this, discussing with @laurenluz, we got the idea to remove e-mail and twitter individual options and let the user choose another option that says 'see more options' and then show the general torus popup

If we show it again the UX would feel really bad for the user, a bit redundant to click twitter and then again being asked.

We can also ask torus team how long would they take them to add twitter as a direct option but that's not a fast solution

@markoprljic let me know what you think, you can try it out already on [staging](http://staging.giveth.io/)

**Comment by laurenluz** [comment]
So this appears to be the same... email and twitter are still linking to the torus window. Are we planning to change this? @markoprljic

**Comment by markoprljic** [comment]
> So this appears to be the same... email and twitter are still linking to the torus window. Are we planning to change this? @markoprljic

Yes because it was a technical issue of linking those directly. 
I don't think it is redundant and bad to have these options visible and user having to click again. The purpose of this is to put those option in front of them to make them aware they exist.

**Comment by divine-comedian** [comment]
Are there any planned UI updates that testers should know relating to this issue? 
Current pop-up looks like - 
![image](https://user-images.githubusercontent.com/67759413/117473333-d6f68e80-af27-11eb-82b2-e8a2fd32e394.png)

Clicking on email or twitter produces: 
![image](https://user-images.githubusercontent.com/67759413/117473438-f8f01100-af27-11eb-8a74-72ee83881251.png)

@markoprljic @mateodaza  

Or is this how we intend it to work?

**Comment by laurenluz** [comment]
This is how it is intended to work. Look at Marko's reply to me above

**Comment by laurenluz** [comment]
@markoprljic - can we close this issue?

**Comment by markoprljic** [comment]
> @markoprljic - can we close this issue?

I give you that pleasure :)
