### ISSUE TITLE
My Account / My Donations - Cannot click Project to open

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-2#659]
As a donor, when viewing my donations I want to click on the project name to open it, find updates etc.

![image](https://user-images.githubusercontent.com/39466970/111485384-d0038a80-86f3-11eb-990f-e656f79431a9.png)

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by WhyldWanderer** [comment]
Tested and fixed! related to issue https://app.zenhub.com/workspaces/giveth-2-5ecaa273967d386713036ca4/issues/giveth/giveth-2/711
