### ISSUE TITLE
My Account / My Donations - Add Donate Button

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-2#660]
In My Account, the view does not change from My Projects (Maker View) to My Donations (Giver View)..
As a Donor if I am viewing my Donations, I want to see a button to Find A Project / Donate, not just "Create a Project".
If it stays the same, we should also have a Donate Button up next to "Create A Project" on both views..

![image](https://user-images.githubusercontent.com/39466970/111486124-73549f80-86f4-11eb-96c8-a8ecfec27e7c.png)

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by Danibelle** [comment]
I was expecting the view to change when I moved from My Projects (Creator view) to My Donations (Donor View) ..
I want to find more projects to support from this page just like I can Create a Project from this page.

![image](https://user-images.githubusercontent.com/39466970/113194910-826c3f00-9216-11eb-8a98-cb2100277fdb.png)

**Comment by markoprljic** [comment]
Ah, now I see where the confusion came from. I think I need to redesign this section a bit so that there is no confusion about this. 

You're not supposed to donate from this page anyway, it is your account where all projects and donations live (now I noticed we need to separate donations to my projects and donations user donated to other projects), also I think we should change the labeling of sections, instead of My Donations to be just Donations or Donation History.

**Comment by MerlinEgalite** [comment]
Well I implemented Dani's suggestions before you message @markoprljic  😅...
Not it works like that:
If on the "My Projects" section the CTA is "Create a Project"
If on the "My Donations" section the CTA is "Donate"

I can update it once you've a new design?

**Comment by markoprljic** [comment]
Thanks Merlin, appreciate your responsiveness :) 
Leave it for now, but in the future we should first consult before any user feedback is implemented ad-hoc. 
I'll be working on changes for this section anyway, once this is done I will let you know.

**Comment by MerlinEgalite** [comment]
Yes get it and sorry I thought it was legitimate to implement it as it was Dani's suggestion!

**Comment by WhyldWanderer** [comment]
I see the switch has been made/
![image.png](https://images.zenhubusercontent.com/5ffdde8079760c4346381d45/c22ed85a-d4d8-4568-bda3-6c88e1184de4)
Moving this issue to done.
