### ISSUE TITLE
Make the default donation gas fee for xDai 2 gwei instead of 20

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-2#668]
## 📋 Anything to add?

I'm down with being higher than 1 gwei... but 20 is much higher than is needed

<img width="506" alt="Screen Shot 2021-03-21 at 11 53 09 AM" src="https://user-images.githubusercontent.com/14945613/111913483-9a9dca80-8a6e-11eb-97cf-74ddacb45481.png">

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by MerlinEgalite** [comment]
This is a the value returned by `getGasPrice`. But it seems that it reflects the gas Price on the mainnet and not xDai. I don't know why. Should we fix the gas Price on xDai @GriffGreen ?

**Comment by WhyldWanderer** [comment]
It seems to be working correctly however its set to 1 and not 2 as the issue states.

![image.png](https://images.zenhubusercontent.com/5ffdde8079760c4346381d45/7efbf5e7-7db0-4f21-b759-e95cc7bfef57)

**Comment by divine-comedian** [comment]
@MerlinEgalite  still no change in the default GWEI price, testing on staging with clean cache and cookies - 
![image](https://user-images.githubusercontent.com/67759413/114308294-4c9a4680-9ab1-11eb-9c24-0b677d9bc913.png)

**Comment by mateodaza** [comment]
It's not merged to staging yet - I noticed there's the PR, I'll check
