### ISSUE TITLE
Work on Copy for "What is Giveth"

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-2#67]
Edit all the text make sure that Kris is ok with it :-D

https://docs.google.com/document/d/1noGXWxVT_nzoGv_0L0gz-XOuowjm6w3Q2_yn7zNHsrk/edit?usp=sharing

**Comment by willyogo** [comment]
Issue moved to [Giveth/planning #10](https://github.com/Giveth/planning/issues/10) via [**ZenHub**](https://www.zenhub.com/)
