### ISSUE TITLE
Make PAN on xDai a default option - but not THE default option

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-2#670]
## 📋 Anything to add?

<img width="351" alt="Screen Shot 2021-03-21 at 12 00 55 PM" src="https://user-images.githubusercontent.com/14945613/111914820-ee5ee280-8a73-11eb-846a-5841af955bf3.png">

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by WhyldWanderer** [comment]
Hooray for donations in PAN! Its working..
![image.png](https://images.zenhubusercontent.com/5ffdde8079760c4346381d45/78236138-6d60-4df2-8c9b-97aa12a3ef8b)

**Comment by GriffGreen** [comment]
THE default option should be xDai... but Pan and HNY should be in the drop down

**Comment by MerlinEgalite** [comment]
Will change that!
