### ISSUE TITLE
Better communicate to the user that donations on xDai exist

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-2#671]
## 📋 Anything to add?

I think donating on xDai can be our main feature... maybe even a default... it may be worth getting some more awareness around it... telling people that they can save money on fees by donating with xDai...

Especially for donations that are less than $50... it would be great to notify the giver that they can save fees with xDai.

But this might need more thought...

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by markoprljic** [comment]
Few options we can do to raise awareness of the xDAI networks support:

1. Include a notice on the Donation page itself (if a user is connected to Mainnet)

![Image 2021-03-25 at 4 12 54 pm](https://user-images.githubusercontent.com/5704285/112496400-ffb23280-8d84-11eb-8d16-2d65a4d1a2bf.jpg)

2. Include a banner on the Homepage and Projects page (user should be able to permanently hide the notifications banner) 

![Image 2021-03-25 at 4 46 42 pm](https://user-images.githubusercontent.com/5704285/112501778-cfb95e00-8d89-11eb-8e42-2ca188fdf82c.jpg)

**Comment by mateodaza** [comment]
I like this, excellent idea!

**Comment by divine-comedian** [comment]
Image banner loads after loading with a fresh cache &  cookies on a new window, looks great! 

![image](https://user-images.githubusercontent.com/67759413/113429056-e5401080-93a5-11eb-9dc5-a1e1b846ea72.png)

and also here - 
![image](https://user-images.githubusercontent.com/67759413/113429192-1caebd00-93a6-11eb-95b2-bcc27f893e9a.png)
