### ISSUE TITLE
Donation type drop down menu in project donations

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-2#678]
From the project donations page I hover over the text on the left **All Donations** a drop down menu appears and I try to move my cursor down over it and the drop down menu dissapears. I can catch the drop down menu if i scroll down using my mouse wheel but if I move my cursor down with my mouse or touchpad it doesn't work.

 Also the small arrow to the right of the 'All Donations' text is a bit far away and not horizontally aligned, coincidence!?!?
tested on brave and firefox clean cache and cooks
![image.png](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/140cd9aa-39a0-47c0-9413-106eba292783)

**Comment by divine-comedian** [comment]
works like a charm! good work mateo
brave browser on clean cache and cookies
![image](https://user-images.githubusercontent.com/67759413/112314213-238b5080-8c7f-11eb-9ea5-4b42c2b578b6.png)

**Comment by laurenluz** [comment]
Since we don't have Fiat donations as an option right now, I think it makes sense to remove this until we do... Otherwise it's pretty confusing to the user.

@mateodaza
