### ISSUE TITLE
Update the Launch Popup Text!

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-2#679]
Officially moving out of "Soft Launch" tomorrow!

Let's change the popup text from:
**Soft Launch Mode**
Share your feedback or report
an issue

to:
**MVP dApp Live Now!**
How can we be better? Report
an issue or request a feature:

![image](https://user-images.githubusercontent.com/39466970/112192681-6cca9a00-8bc4-11eb-9e6a-78b17b24f490.png)

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by geleeroyale** [comment]
I am thinking about how to optimize this element as well - this popup is the most annoying element for me on the page tbh. Maybe we should hide it behind a github logo button that then shows this popup?

**Comment by divine-comedian** [comment]
I find MVP is a confusing term, I'll be honest, I had to look up what the hell MVP meant. If the intention is to make the dapp, simple and easy to use I don't feel like nuanced marketing abbreviations make a lot of sense. My suggestion would be something simpler like "Give(th) Feedback" **AND ALSO -** 
<BR>
There's also a softLaunch pop-up that appears on staging. Might seem a bit redundant if we're having this other pop-up for issue reporting.

![image](https://user-images.githubusercontent.com/67759413/112309316-9691c880-8c79-11eb-9e4a-2a246e36cc47.png)

**Comment by mateodaza** [comment]
> I am thinking about how to optimize this element as well - this popup is the most annoying element for me on the page tbh. Maybe we should hide it behind a github logo button that then shows this popup?

@markoprljic what's your opinion here?

**Comment by markoprljic** [comment]
I agree with @divine-comedian MVP will be confusing for the general public. 

I suggest:

- Remove Soft launch toast message (if it's there)
- Use the floating element to gather user feedback

Title: Tell us what you think
Body: How can we be better? Report an issue or request a feature.
Button: Give Feedback

**Comment by divine-comedian** [comment]
Looks like this got pushed right to live. but not to staging. I'll mark it as resolved but for consistency we should push it to staging as well @mateodaza 
## LIVE
![image](https://user-images.githubusercontent.com/67759413/112652388-bfee5800-8e23-11eb-9500-26577997ff23.png)

## Staging 
![image](https://user-images.githubusercontent.com/67759413/112652501-da283600-8e23-11eb-8da1-00471b4cca2f.png)
