### ISSUE TITLE
Automate Issue Reporting/Feature Requests to GitHub with a form

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-2#681]
## 📋 Anything to add?
Creating a project is easy, donating is easy..  providing feedback should be easy too!

Let's put a data collection form in front of GitHub to collect useful data to analyze, while protecting users from exposure to GitHub if they don't need it (with a button for GitHub available to advanced users).

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by geleeroyale** [comment]
Cross referencing this issue from **giveth-planning**

https://github.com/Giveth/giveth-planning/issues/177

**Comment by laurenluz** [comment]
WIP as part of https://github.com/Giveth/giveth-planning/issues/177
