### ISSUE TITLE
add Giveth on the homepage? :)

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-2#682]
## 📋 Anything to add?

Top left there's now a double 'future of giving' and no mention of what we are, namely giveth :) 

Would propose to replace 'future of giving' next to logo by Giveth.

see screenshot

![image](https://user-images.githubusercontent.com/6533925/112196291-2a787b80-8c0b-11eb-8fc0-e45b6ecce506.png)

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by divine-comedian** [comment]
looks hella clean. I see it's been pushed already to staging and LIVE. redundancies no more! 

![image](https://user-images.githubusercontent.com/67759413/112655745-1a3ce800-8e27-11eb-91f7-6d64a90414c9.png)
