### ISSUE TITLE
Change order of explanation for consistency

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-2#683]
## 📋 Anything to add?

In the text you talk about it in the 'DAC' order, illogical to reverse it just below like currently done

![image](https://user-images.githubusercontent.com/6533925/112196539-6dd2ea00-8c0b-11eb-9451-806c4ad692e3.png)

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by divine-comedian** [comment]
ahhh.. D .. A... C... it all comes together now. looks good.

![image](https://user-images.githubusercontent.com/67759413/112319183-2fc5dc80-8c84-11eb-9498-523006044a7b.png)
