### ISSUE TITLE
Consistency in usage capitals

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-2#684]
## 📋 Anything to add?

Would propose without? Only here one P capitalized 

![image](https://user-images.githubusercontent.com/6533925/112196742-a1157900-8c0b-11eb-974e-3a1bae7d7086.png)

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by divine-comedian** [comment]
positively Perfect. - looks good - 
![image](https://user-images.githubusercontent.com/67759413/112313226-01450300-8c7e-11eb-8b4b-cfe828be382a.png)
