### ISSUE TITLE
Mobile - Fix 3rd project's title 'Help the Patagonia'

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-2#686]
## 📋 Anything to add?

Help the Patagonia -> Help Patagonia

## ❓ Why is it important?

This is the first thing people see scrolling thru the updated site - not great to start with a project with a typo 

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by jamespfarrell** [comment]
done

**Comment by jamespfarrell** [comment]
done on live
