### ISSUE TITLE
User's public route is showing wrong projects 

### ISSUE THREAD

**Issue by mateodaza** [Giveth/giveth-2#693]
## 📋 Anything to add?
also there's no picture there 

## ⏰ Urgency/Deadline/Blockers?

pretty urgent

**Comment by divine-comedian** [comment]
@mateodaza  can you clarify what you mean by user public route?

**Comment by mateodaza** [comment]
User's public profile, for example this is Dani's https://giveth.io/user/0x5d28fe1e9f895464aab52287d85ebff32b351674

**Comment by divine-comedian** [comment]
On staging I'm able to find my profile using the public route URL - tested on Brave in incognito mode
![image](https://user-images.githubusercontent.com/67759413/113184661-76d34500-9223-11eb-9713-3bc8ece4fc17.png)
