### ISSUE TITLE
View donations page doesnt work - loged in with metamask with griff.eth

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-2#695]
## 📋 Anything to add?

https://giveth.io/account/?view=donations

I just get a blank page

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by divine-comedian** [comment]
I haven't made any donations but my page seems to load correctly on giveth.io using metamask on mainnet. 

![image](https://user-images.githubusercontent.com/67759413/112651194-8c5efe00-8e22-11eb-9336-cf43904b7752.png)


@GriffGreen is this specifically an ENS problem?

**Comment by laurenluz** [comment]
works fine on live

![image](https://user-images.githubusercontent.com/75490971/114788842-6c469e80-9d3f-11eb-8a3b-2b324260c234.png)
