### ISSUE TITLE
When I Created a project with a different address, the website flashed my other address at me and it was scary

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-2#697]
## 📋 Anything to add?

When I created a project it autofilled my address in, but i wanted to use a different address, so I added the new address and then clicked to move forward.... and thats when it happened...

A quick flash of my other address in the address field. 

My heart dropped, I nearly wet my pants.

But before the flow could go, the next screen showed the correct address and i was relieved i didnt relieve myself..

Thx for the roller coaster ride... :-D

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by laurenluz** [comment]
this description is hilarious 🤣

**Comment by laurenluz** [comment]
I think now it's just set to not autofill at all, right? @mateodaza 

If so, it's working just fine...
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/7d41c088-9b11-4408-ae72-6ebd1384cd1b)
