### ISSUE TITLE
Improve xDAI support: Provided chain "1" must match the active chain "100"

### ISSUE THREAD

**Issue by sembrestels** [Giveth/giveth-2#698]
## 📋 Anything to add?
The error appears when somebody is connecting from xDAI (chainId 0x64) in both projects page and when you already have donated and try to "register an account".

## ⏰ Urgency/Deadline/Blockers?
We can't say giveth has support to xDAI until this problem is not soved.

## ❓ Why is it important?
In order to support 1hive community tokens (HNY and AGVE), we need this feature. 

## 🤼‍ Reviewer

@sembrestels

## 🔗 Work doc - inspirational links

None.

**Comment by mateodaza** [comment]
Yes! You are right - Relates to #621

**Comment by mateodaza** [comment]
It's working now :)
