### ISSUE TITLE
IMO I would remove the "Total Value of Assets in Wallet" feature on the profile page

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-2#699]
![Screen Shot 2021-03-24 at 10 12 24 AM](https://user-images.githubusercontent.com/14945613/112334783-fa3ce580-8cbb-11eb-8b92-3d58eae4fd25.png)

It gives the wrong value on xDai... it might be easier to just remove it

**Comment by markoprljic** [comment]
I agree, this was supposed to be a metric of all donations received through Giveth and NOT assets value in the wallet user has connected. 

@mateodaza Let's remove this box from My Account page.

**Comment by divine-comedian** [comment]
No more total assets shown on the my account page. issue fixed as described. tested on brave w/ clean cache and cookies.
![image](https://user-images.githubusercontent.com/67759413/113509526-1e9e8a80-9524-11eb-9cac-dad1958707ae.png)
