### ISSUE TITLE
Network ID error when using connecting with MetaMask and xDai Network enabled

### ISSUE THREAD

**Issue by andogro** [Giveth/giveth-2#700]
## 📋 Anything to add?

If my MM is connected to the xDai chain and I try to connect the wallet , I receive an error message 'Provided chainID "1" must match the active chainId "100" and account is not connected. 

<img width="1548" alt="issue-2" src="https://user-images.githubusercontent.com/14284654/112336370-a5c94400-8c82-11eb-8001-9f420df091e0.png">

## ❓ Why is it important?

Causes UX issue for xDai users

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by andogro** [comment]
See now this is already reported on #621

**Comment by mateodaza** [comment]
This is done now :)
