### ISSUE TITLE
Add "Sign in" / "Connect" button to donation page

### ISSUE THREAD

**Issue by sembrestels** [Giveth/giveth-2#701]
## 📋 Anything to add?
The error that appears when you try to donate with a metamask not connected is:

> The send transactions "from" field must be defined!

## ⏰ Urgency/Deadline/Blockers?
It's easy to solve, and quite important.

## ❓ Why is it important?
It's a major UX stopper for anyone to donate

## 🎉 Subtasks

- [ ] Add a "Sign in" button in the top right corner as in any other page
- [ ] Change the error message to something like "You must be connected in order to do a donation"

## 🤼‍ Reviewer

@sembrestels

**Comment by mateodaza** [comment]
You can donate without being logged in, the error was happening because of a problem with our xDAI node - closing it
