### ISSUE TITLE
On xDAI network, equivalent USD value is calculated as if the xDAI is ETH

### ISSUE THREAD

**Issue by sembrestels** [Giveth/giveth-2#704]
## 📋 Anything to add?
In the https://giveth.io/account page it consider my xDAI as ETH, and does a misleading conversion to dollars.

## ⏰ Urgency/Deadline/Blockers?
Not so much urgent.

## ❓ Why is it important?
It is important to support xDAI as well as other chains correctly.

## 🤼‍ Reviewer

@sembrestels

**Comment by laurenluz** [comment]
@mateodaza I just got this same feedback from ygg - check it out... The value in $ is calculated as if my 32 xDAI is 32 ETH

![image](https://user-images.githubusercontent.com/75490971/112400257-991e0d80-8ccd-11eb-9801-7b7c6d2ce7cf.png)

**Comment by GriffGreen** [comment]
I say, enjoy your new found riches, what the issue?!?!?

**Comment by mateodaza** [comment]
Giveth making it rain since day zero 🥳 hahaha -  out of joke I'll get on it

**Comment by divine-comedian** [comment]
still showing up on giveth.io 

![image](https://user-images.githubusercontent.com/67759413/113439302-4ffa4780-93b8-11eb-8bb3-0a3e94a345f3.png)

the wallet balance doesn't show up at all on staging

**Comment by mateodaza** [comment]
live isn't up to date yet, coming on monday I believe

**Comment by divine-comedian** [comment]
I think this issue is resolved since we removed the wallet balance window completely from 'my account', correct @mateodaza ?
