### ISSUE TITLE
After successful donation the "Donation in progress" toast message does not go away

### ISSUE THREAD

**Issue by markoprljic** [Giveth/giveth-2#705]
## 📋 Anything to add?
![Image 2021-03-24 at 7 32 07 pm](https://user-images.githubusercontent.com/5704285/112365265-beb01480-8cd7-11eb-8d0c-fd74097fafa8.jpg)

**Comment by MerlinEgalite** [comment]
Do you still have the issue @markoprljic?
I don't have the issue...

**Comment by markoprljic** [comment]
Tested on staging, seems to be ok now.
