### ISSUE TITLE
Allow right click on project card "Learn more" button to open in new tab

### ISSUE THREAD

**Issue by markoprljic** [Giveth/giveth-2#707]
## 📋 Anything to add?
![Image 2021-03-24 at 7 35 45 pm](https://user-images.githubusercontent.com/5704285/112365653-32522180-8cd8-11eb-9ce1-38608dc1d8cb.jpg)

**Comment by WhyldWanderer** [comment]
Tested... its working!
![image.png](https://images.zenhubusercontent.com/5ffdde8079760c4346381d45/a691dd42-49c3-47a1-871a-a719d856dd02)
