### ISSUE TITLE
MyWallet link goes to Etherscan error page

### ISSUE THREAD

**Issue by andogro** [Giveth/giveth-2#708]
## 📋 Anything to add?

<img width="1378" alt="giveth-error1" src="https://user-images.githubusercontent.com/14284654/112366278-3a8d6b00-8c9e-11eb-95b8-c1d33289c4e4.png">

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by WhyldWanderer** [comment]
Its working for me with two different accounts. I think this issue is resolved
