### ISSUE TITLE
Under my account selecting crypto on drop down doesn't show xDai

### ISSUE THREAD

**Issue by jamespfarrell** [Giveth/giveth-2#712]
Under my account selecting crypto on drop down doesn't show xDai

![image](https://user-images.githubusercontent.com/10499048/112453975-8270c880-8d58-11eb-9a2a-d11bd9fb1b25.png)

**Comment by mateodaza** [comment]
That dropdown currently shows either crypto or fiat, we could show all available tokens and give the option to filter according to that - I think that'd be cool

**Comment by MerlinEgalite** [comment]
Should we close this issue or reformulate it?

**Comment by laurenluz** [comment]
So the drop down filter was fully removed then? 

The search function is not working properly on this page, btw...
![image](https://user-images.githubusercontent.com/75490971/118301302-21d05300-b4a0-11eb-8af3-8ad59d864244.png)
