### ISSUE TITLE
Refactor Donations page (Cryptocurrency option)

### ISSUE THREAD

**Issue by markoprljic** [Giveth/giveth-2#714]
## 📋 Anything to add?

New design proposal for the Donation screen (Cryptocurrency tab)

![Image 2021-03-25 at 4.12.54 pm.jpg](https://images.zenhubusercontent.com/5cc090818b624e26c3734d75/edc28eec-3d59-4ec9-af9f-f22222db2ec8)

![Image 2021-03-25 at 7.04.08 pm.jpg](https://images.zenhubusercontent.com/5cc090818b624e26c3734d75/f78c8719-e8d2-47fd-ae22-c291d276f4dc)

1. Make the input field 100% width of the tabs on top
2. Include token icon and symbol on the right side of the input
3. Change price breakdown info as shown in the example above
4. Include Network fee **tooltip** to inform user why the fee is charged, include $ and ETH value of the gas fee
5. If user is on Mainnet, include info to change to xDAI to save on fees
6. Make the Donate button wider

**Comment by markoprljic** [comment]
@mateodaza Could this issue be something for @MerlinEgalite?

**Comment by MerlinEgalite** [comment]
with pleasure if @mateodaza you are ok!

**Comment by markoprljic** [comment]
Worth noting @MerlinEgalite that there is another connected issue that I believe @mateodaza is working on https://github.com/Giveth/giveth-2/issues/623

I suggest you two sync and we can close both at the same time.

**Comment by markoprljic** [comment]
Figma source file for the above design https://www.figma.com/file/FBqHg0UfeuaIueDEZG0tBS/Giveth.io?node-id=4932%3A93

**Comment by markoprljic** [comment]
@MerlinEgalite One small addition I just made is the information about how much funds user has in their connected wallet based on the token selected in the list. See the screenshot below...

![Image 2021-03-27 at 6 51 16 pm](https://user-images.githubusercontent.com/5704285/112729663-aa655500-8f2d-11eb-967f-922d70807338.jpg)

**Comment by MerlinEgalite** [comment]
Oh didn't see that, sure I can add it @markoprljic !

**Comment by WhyldWanderer** [comment]
All of the things on Markos list above have been checked off except for number 2. Include token icon and symbol on the right side of the input.

Other than that, its looking great!

**Comment by divine-comedian** [comment]
@MerlinEgalite see comment above! ^ 

![image](https://user-images.githubusercontent.com/67759413/114575953-ad0fbc00-9c48-11eb-97a3-76a6adad621f.png)

**Comment by MerlinEgalite** [comment]
<img width="531" alt="Screenshot 2021-04-14 at 09 58 16" src="https://user-images.githubusercontent.com/44097430/114683526-638aa400-9d10-11eb-8261-670625ddcae5.png">

Is it good like that?
