### ISSUE TITLE
Tried to donate twice - didn’t get there

### ISSUE THREAD

**Issue by imtien** [Giveth/giveth-2#715]
## 📋 Anything to add?   I tried to donate to Diamante Luz projects.  Via links sent out by trusted sources.  Those links sent me to the Diamante Luz donate portal.   Then when clicking donate - sent me to meta mask with net - then I can’t find Diamante Luz because it’s not listed in the projects.  

When I get to the bottom of the page of projects to the “show more” tab.  It just shows the same ones over and over.  

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by mateodaza** [comment]
Hello!! The Diamante project is showing up there but I noticed there's a problem that when you are loading projects, the new ones load to the top of the list - anyone can easily miss it. 

Thanks for bringing up this issue, we'll improve the UX on this aspect

**Comment by laurenluz** [comment]
This should be fixed now with the fixes on the sort/filter/serach function.
