### ISSUE TITLE
"Be the first to support this project" CTA for projects with zero donations 

### ISSUE THREAD

**Issue by markoprljic** [Giveth/giveth-2#717]
## 📋 Anything to add?
Similar to the example below 

![Image 2021-03-26 at 4.55.49 pm.jpg](https://images.zenhubusercontent.com/5cc090818b624e26c3734d75/799161e3-dcf5-4dbf-abeb-7325a9f9807e)

Additionally, issue NFT badge for first supporters.

**Comment by markoprljic** [comment]
![Image 2021-03-31 at 4 26 27 pm](https://user-images.githubusercontent.com/5704285/113160522-dc342f80-923d-11eb-92f5-2eeae0ca2364.jpg)
This lives on project details page in the sidebar.

**Comment by laurenluz** [comment]
yeah, it's good. text is updated and not GIVing away anything ;)

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/6e796d29-ef2c-4225-821f-13eb09146193)
