### ISSUE TITLE
Total donations is WAY OFF!

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-2#718]
<img width="506" alt="Screen Shot 2021-03-26 at 2 49 34 PM" src="https://user-images.githubusercontent.com/14945613/112685550-05874100-8e75-11eb-936a-069adf0dee6a.png">

we have a 1 HNY donation which is like $1000

**Comment by divine-comedian** [comment]
Testing a couple projects on staging. Looks like the values add up correctly. I added up all the ETH donations and got the correct difference, assuming the 10 cents difference is reflected from the 0.1 xDAI donation.

![image](https://user-images.githubusercontent.com/67759413/114070830-6dbf2500-986e-11eb-8356-7ba1e075dfa5.png)

I tested a project with no donations and made a small xdai donation to it.. the donation shows up but the amount does not 

![image](https://user-images.githubusercontent.com/67759413/114071278-ef16b780-986e-11eb-8a17-f22b76e66a06.png)

I tried going back to the first project, I donated a tiny bit of Honey to see if the price updated, no movement yet. Both this and the previous transaction have several hundred confirmations.. 

![image](https://user-images.githubusercontent.com/67759413/114073328-2c7c4480-9871-11eb-992d-ced6c800f8f5.png)

I cleared cache and cookies after making donations, checked again, still no updates.

**Comment by divine-comedian** [comment]
still none of my xdai donations are having their price shown and are not updating the total donations on the project. the donation shows up on the project page and my donations page but their is no price $ attached to it. 

![image](https://user-images.githubusercontent.com/67759413/115727024-3dd54e80-a351-11eb-9a78-ff0bee2a1843.png)

**Comment by positonic** [comment]
This was a bug, now fixed

**Comment by divine-comedian** [comment]
I just tried making another xdai donation with a clean cache on a new project with no donations yet. I still don't have my xdai donations show up under **total funds raised**. 
@jamespfarrell 
![image](https://user-images.githubusercontent.com/67759413/116455679-5bae2200-a82f-11eb-9db2-906421c74ef7.png)

**Comment by positonic** [comment]
This should be resolved
