### ISSUE TITLE
Invert 2 texts for donation CTO?

### ISSUE THREAD

**Issue by MerlinEgalite** [Giveth/giveth-2#723]
@markoprljic should we invert the two texts so that the main CTA is Donate?
It could ease the donation process

<img width="478" alt="Screenshot 2021-03-28 at 16 58 13" src="https://user-images.githubusercontent.com/44097430/112758569-6cc90080-8fef-11eb-91fc-93e64f369428.png">

**Comment by markoprljic** [comment]
No because we decided not to be too aggressive with it. Originally I designed it the way you're proposing but donors would most likely want to read more about the project and then donate.
