### ISSUE TITLE
Hide Torus from the users, highlighting our preferred login instead

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-2#724]
From Jeff:

Is it possible to get "Sign in with google" instead of the torus symbol on the Giveth site too?  Takes one less click away from the user having to figure out how to sign in!

<img width="354" alt="Screen Shot 2021-03-28 at 11 43 47 AM" src="https://user-images.githubusercontent.com/14945613/112760172-6722e900-8ff6-11eb-9b43-e65cbf150e92.png">

**Comment by mateodaza** [comment]
So, we'd remove all other ways to login and only leave google as an option?
