### ISSUE TITLE
Ensure projects can only use Externally owned accounts, not smart contracts

### ISSUE THREAD

**Issue by jamespfarrell** [Giveth/giveth-2#727]
There's no guarantee that a smart contract wallet exists on xdai, so we lock it down for now.

**Comment by laurenluz** [comment]
Tested with Mateo's YAY token contract address, the project didn't go to completion (YAY) and I got a popup (YAY) but then I got stuck on the infinite spinning wheel

popup success:
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/bf361cee-a9aa-49ae-a5f6-50d5af52fa4a)

spinning wheel:

**Comment by laurenluz** [comment]
Ok tested, with another smart contract, this one: https://etherscan.io/address/0x06fd90bA5b63d8BFc7B9d7EEA8E26Ac522A1c772#code

And I was able to make a project... no popup, and was able to submit with no issues... Did we decide to disallow all contracts? or are we allowing them if they exist on both chains? @jamespfarrell 

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/daeb257d-5552-435f-a2dd-b392e8c6ae34)

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/210e687f-453a-47d0-a1ac-37b72e5eb23c)

Bit of a conflict in message between this issue and #722

**Comment by laurenluz** [comment]
pretty sure this contract address is only on mainnet, and not xdai. It's @Danibelle 's

**Comment by mateodaza** [comment]
Just integrated it on staging for testint!

**Comment by divine-comedian** [comment]
Testing it out I try to make a project using a smart contract - 0x109b588A4f2a234e302c722f91fe42c5ab828A32

It won't let me make a project with a smart contract address on mainnet

![image](https://user-images.githubusercontent.com/67759413/115743880-1043d180-a360-11eb-9001-b9b6969506bf.png)

Alternatively I tried taking a smart contract address on xDAI and make a project with it as the receipient address 
using this address - 0x0B21081C6F8b1990f53FC76279Cc41ba22D7AFE2

Again I am prevented from doing so.

![image](https://user-images.githubusercontent.com/67759413/115744337-7af50d00-a360-11eb-9851-c53760425baf.png)

Those are examples, I went out and tried about a half dozen other smart contracts on both xdai and mainnet and was effectively blocked from using the addresses to make a project on giveth.io 

To me this issue looks to be solved! 
Brave Browser clean cache and cookies
