### ISSUE TITLE
Commons Simulator Project link leads to blank page

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-2#730]
I followed a link posted by @laurenluz in the CS DDev telegram channel and got this:
![image](https://user-images.githubusercontent.com/39466970/113056178-51313780-9160-11eb-8f17-fb79f8a46857.png)

Cleared cache and tried again with same result :(

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by Danibelle** [comment]
Ok it looks like the punctuation doesn't translate into Telegram unless you copy the link with the / at the end..
I think this is a working as designed, but something to be aware of..  !!! ;)

**Comment by jamespfarrell** [comment]
Someone updated the title of the project. The slug in the url is based on the title so the url of the project changed which is why we have a 404 errror. My feeling is that editing the project shouldn't update the slug and that it can't be changed by the user... what do you think about this?

**Comment by Danibelle** [comment]
Are you sure that's the issue, for one..
Because we had two simultaneous things happen.. first the error because the Project Name had an exclamation point, which did not translate when pasting the URL into a chat (telegram).  If I added the punctuation to the URL in my browser, it worked.
But to eliminate confusion, Lauren ALSO changed the project name.

Regardless - here's my answer..  Yes AND, please! GitCoin does it, so can we:
Gitcoin allows the old one to stay, and ADDS the new one..  we changed Giveth 2 to Giveth.io ..
Both work now..
https://gitcoin.co/grants/795/giveth-20
https://gitcoin.co/grants/795/givethio
...
Can we use their code? :smile:

**Comment by positonic** [comment]
I am making the change such that we don't update the slug when the title is editted. I am creating the capacity for the front end to call with a new slug specifically, and this will be added later, as Mateo's secret project could render any other fixes on this right now redundant.
