### ISSUE TITLE
When donating (with metamask set to the wrong chain) it looks weird

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-2#732]
<img width="1003" alt="Screen Shot 2021-03-31 at 8 23 50 AM" src="https://user-images.githubusercontent.com/14945613/113151264-32e93b80-9235-11eb-8db0-953a6a5666da.png">

I think we need a chain ID check... if its not set to ETH or xDai, then we have to tell them that they need to switch networks... and we def don't want to show the gas price like its the gas fee!

10 Gwei, IN MY DREAMS!!!

**Comment by markoprljic** [comment]
This is solved with this new UI design.

![Image 2021-03-31 at 4 43 54 pm](https://user-images.githubusercontent.com/5704285/113163290-52399600-9240-11eb-82d7-828832d9d483.jpg)

**Comment by GriffGreen** [comment]
I reopened because it is a slightly different issue.

Your Design addresses the scenario when the user is on ETH...

This is issue is for when the user is on a different chain entirely, I am on BSC for instance.

**Comment by mateodaza** [comment]
On it! - I used to have that check, something got lost in time

**Comment by divine-comedian** [comment]
exploring a bit here.. once I log in I can still switch to other chains and I can try to donate - 
I get the insufficient funds pop-up if I try to donate on an unapproved network 
![image](https://user-images.githubusercontent.com/67759413/113438468-9e0e4b80-93b6-11eb-8653-1fe061e1ab9a.png)

Which is not the same as when I try to log in while on the wrong network 

![image](https://user-images.githubusercontent.com/67759413/113438544-c433eb80-93b6-11eb-8e22-3d027911f1ee.png)


Is there a way to show different pop-ups on the donate page so the user can distinguish whether they have an insufficient funds problem or a wrong network problem? @mateodaza

**Comment by divine-comedian** [comment]
On the donation page I try to donate with more funds than I have and I receive the appropriate NSF pop-up 
![image](https://user-images.githubusercontent.com/67759413/113629213-1afa2900-9634-11eb-8dc9-bf64aff63232.png)

If I try to donate on an unapproved network -BSC for example - I get the appropriate 'change network' pop-up. 
![image](https://user-images.githubusercontent.com/67759413/113629350-539a0280-9634-11eb-9882-d65b71ce60e6.png)

looks good!
