### ISSUE TITLE
Reprioritize the focus for the Gas design

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-2#734]
<img width="594" alt="Screen Shot 2021-03-31 at 10 45 06 AM" src="https://user-images.githubusercontent.com/14945613/113173024-4d2d1480-9249-11eb-91df-4353d37b0087.png">

A lot of people don't know GWEI

Can it be :

215 GWEI (Small) $50.31 (Small) .013 ETH (Big)

**Comment by MerlinEgalite** [comment]
Yeah I'll make the changes!

**Comment by divine-comedian** [comment]
Testing on staging, clear cache and cookies.. looks to match up with marko's UI proposal on mainnet

![image](https://user-images.githubusercontent.com/67759413/114074657-9a753b80-9872-11eb-9b39-d4acbc3ec733.png)

**and similarily on xDAI**

![image](https://user-images.githubusercontent.com/67759413/114074978-00fa5980-9873-11eb-8454-70a414c38c26.png)

**Comment by markoprljic** [comment]
The total doesn't seem to be calculated correctly tho?

**Comment by MerlinEgalite** [comment]
Good catch @markoprljic but there is an issue: here we are on xDai so we can easily sum the two numbers. But what if the user donates PAN? In what token/USD we should show the total amount?

**Comment by markoprljic** [comment]
You're right. Maybe we shouldn't calculate the sum altogether since we can't that way for all other tokens.

**Comment by MerlinEgalite** [comment]
So we leave that like this or do you have something else in mind?

**Comment by markoprljic** [comment]
I'm thinking about removing the line and total value, keeping just donation and fee

**Comment by MerlinEgalite** [comment]
Or we can keep the line, remove the Total Donation Amount above the line and put it behind ? I like the fact we emphasise what the user is giving

**Comment by markoprljic** [comment]
I'm not sure I'm following.

**Comment by MerlinEgalite** [comment]
<img width="572" alt="Screenshot 2021-04-11 at 09 14 16" src="https://user-images.githubusercontent.com/44097430/114297093-ffb57080-9aae-11eb-8a0b-0907591e6fde.png">
 
 Like that

**Comment by markoprljic** [comment]
I get it. But no need for the line IMO.

**Comment by MerlinEgalite** [comment]
yes you're right! I can implement it if you're confortable with that!

**Comment by markoprljic** [comment]
Yes, let's do that.

**Comment by MerlinEgalite** [comment]
![Uploading Screenshot 2021-04-11 at 10.06.55.png…]()

**Comment by markoprljic** [comment]
Perfect

**Comment by laurenluz** [comment]
The gas $ value isn't being calculated correctly on live (mainnet and xdai)

xdai
![image](https://user-images.githubusercontent.com/75490971/115281992-e479df00-a106-11eb-935a-8ddc02a1f654.png)

mainnet
![image](https://user-images.githubusercontent.com/75490971/115282103-06736180-a107-11eb-9289-39efba60e065.png)


(same is true on staging)

**Comment by MerlinEgalite** [comment]
For xDAI this is normal as the amount of xDai i son tiny that it rounded to $0.00 (dollar has only 2 decimals). But maybe we can remove it on xDAI or show the xDai amount like $0.000042. What do you prefer @laurenluz ?

**Comment by laurenluz** [comment]
no no, but look... it is not correctly calculating on Mainnet either. It is always just saying $0.00..... 0.005 ETH is at least $10.

also maybe I'm wrong, but I think on xDAI too, that's not right... I put in 10 trillion HNY which is like 7 quadrillion dollars?? is the fee really less than a penny to donate 7 quadrillion dollars worth on xdai?

**Comment by laurenluz** [comment]
and hmm... i think it is ok to leave the dollars at two decimal places. But perhaps we can add the text "less than" if it is showing less than $0.01? So they know it has a value still?

**Comment by MerlinEgalite** [comment]
Sure there is an issue yes 

Fees do not depend on the amount you move: you just pay for the gas used for an ERC20 transaction whatever the amount and the receiver. So for sending 10 trillion HNY or just 1 HNY, you'll pay the same fee.

Yes good idea, I'll change it!

**Comment by laurenluz** [comment]
Ok great - thanks for clarifying Merlin!
