### ISSUE TITLE
Blog posts should be updating at website bottom

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-2#735]
We have more current stories to share since the ones that appear here.. is this a feed or are these stories coded and need to be updated manually?

![image](https://user-images.githubusercontent.com/39466970/113195273-eee73e00-9216-11eb-94c9-db3d84b294e6.png)

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by geleeroyale** [comment]
It takes until the next time the application runs a build - then new stories are fetched. This issue is fixed on main deployment (if 30th March is the most current article)
