### ISSUE TITLE
Hello. I'm supporting social good projects by listing them on Giveth to raise funding. Clients all want to load video. Will this become available? Thanks!

### ISSUE THREAD

**Issue by jonimadere** [Giveth/giveth-2#739]
## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by mateodaza** [comment]
Helloo! Yess totally, we have it on our roadmap #441 coming soon

Thank you a lot for the feedback 💜

**Comment by jonimadere** [comment]
Hello! Fantastic. Thank you.

**Comment by jamespfarrell** [comment]
This is a duplicate issue, please track this issue here -https://app.zenhub.com/workspaces/giveth-2-5ecaa273967d386713036ca4/issues/giveth/giveth-2/441
