### ISSUE TITLE
Cannot donate on live with Torus

### ISSUE THREAD

**Issue by jamespfarrell** [Giveth/giveth-2#741]
![image.png](https://images.zenhubusercontent.com/5807a7a095e42b6c5baabbd3/10c721db-f39e-4d62-a0f3-ddc88988d240)

**Comment by jamespfarrell** [comment]
I believe either I accidentally close this:
![image](https://user-images.githubusercontent.com/10499048/113413710-8eddcc80-93bb-11eb-848c-571ddf45fb5b.png)

Or it didn't display first

**Comment by positonic** [comment]
Can't reproduce.. I will keep my eyes open for it re-appearing
