### ISSUE TITLE
Add "copy link" option to share pop-up on projects

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-2#744]
When I click the Share icon (next to the heart) and get the 3 social media options, I want to have a Link option to easily get the projects link for sharing in other places!

![Screenshot_20210402-173223_Chrome.jpg](https://user-images.githubusercontent.com/39466970/113458917-94e2a600-93d9-11eb-9099-a35c6f80c335.jpg)

**Comment by laurenluz** [comment]
![image](https://user-images.githubusercontent.com/75490971/121415373-e735cb00-c924-11eb-9fb7-dd8bd2c9c559.png)
