### ISSUE TITLE
Sort Function only works on the first set of projects shown?

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-2#749]
When I select "hearts" from the sort filter, it rearranges those I can see..
But when I click "more projects" ..  the additional projects shown have more hearts than some presented in the first page.

First three:
![image](https://user-images.githubusercontent.com/39466970/113614405-4ca8cb00-9607-11eb-80c8-614c4a9a1bae.png)

When I click "Show More Projects" the filter resets to Default, and I have to choose it again, Next set:
![image](https://user-images.githubusercontent.com/39466970/113614541-81b51d80-9607-11eb-876a-a51c69b52b12.png)

The next time I click "Show More Projects" a bunch of projects with lots of hearts appears.. but I have to scroll aaallll the way up, and change my sort filter a 3rd time..  I'm feeling challenged now, and wonder how many more projects are buried that I will have to repeat this process to find!
![image](https://user-images.githubusercontent.com/39466970/113614676-ad380800-9607-11eb-8669-fd99c2a1a8a1.png)

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by Danibelle** [comment]
This happens with the Categories too..  I pick Technology, scroll to bottom where it says Load More, then get projects about cats.

**Comment by laurenluz** [comment]
This is still happening, even though we have infinite scroll. When I open the projects page... and sort by likes, I get this:

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/a310b4f1-5e32-4e7c-81cd-74b8eb4091da)

Then I scroll down and back up, and the top looks like this:

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/aac7a8b9-2bd7-4f26-b06b-62aa744abb52)

**Comment by divine-comedian** [comment]
@Danibelle  I think the original problem was related to the other issue of quality score not being updated for projects created past the quality score implementation. 

Testing out lauren's issue - On a clean cache and cookies, fresh page load. I select sort by hearts and It appears to sort correctly - 
![image](https://user-images.githubusercontent.com/67759413/114186300-ad404c80-9914-11eb-84fc-46df23bf014d.png)

I scrolled all the way down, then back to the top, projects still seem to sort correctly.
![image](https://user-images.githubusercontent.com/67759413/114186590-08723f00-9915-11eb-8eff-c9393272a57d.png)

Referencing Dani's issue even with the infinite scroll when I sort by 'Default' we get a couple good projects at the top, some empty test projects and then higher quality projects all mixed up near the bottom. This is all related to updating quality scores? @jamespfarrell 
![image](https://user-images.githubusercontent.com/67759413/114187572-255b4200-9916-11eb-8799-d3234a6d83b7.png)

**Comment by laurenluz** [comment]
ooh testing on live and I'm seeing the same issue that Mitch mentioned... When I sort by hearts, everything is fine. When I sort by default there are some "early adopters" near the bottom... assuming because of the quality score being implemented afterwards. Can we manually update this somehow? @jamespfarrell @mateodaza 

This is like half way down the projects page, sorting by default... the Commons Stack is apparently not as high quality as "James - test" 

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/714051fd-35f3-4052-ad29-d7487f2b488c)

**Comment by mateodaza** [comment]
The sorting is fine, interestingly enough James project quality score is 40, when commons stack is 30 - not sure why but I'd like to see what happened there @jamespfarrell

**Comment by laurenluz** [comment]
The Commons Stack should have a quality score of 100 (the maximum) because it has 20 hearts and each heart is worth 10... it also has a picture and description more than 100 characters.

So the score is not being calculated correctly. 

https://docs.giveth.io/guides/qualityscore/

**Comment by divine-comedian** [comment]
retroactively updating the quality score was something James and I had tried to work on together but it's been hard to schedule.

**Comment by WhyldWanderer** [comment]
It seems infinite scroll implementation has fixed this issue.
I am able to sort correctly on live and staging.
