### ISSUE TITLE
Search Function not returning results

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-2#750]
I type "Diamante" and nothing happens, hit enter, nothing, click the magnifying glass, still no results.
I filter on most raised, most hearts, scroll and scroll and still no.
Had to click Load More 6 times for this project to show up, and it has hearts and donations.
![image](https://user-images.githubusercontent.com/39466970/113617566-55030500-960b-11eb-8268-8cdd711da6ce.png)

I type commons, and get a bunch of projects.. but not this one, which I only found by clicking "Load More" 6 times..
https://giveth.io/project/commons-stack:-iteration-0

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by laurenluz** [comment]
This is working fine now 🤔 
![image](https://user-images.githubusercontent.com/75490971/114793081-d4e54980-9d46-11eb-9a35-96f2ed7f4a8e.png)
