### ISSUE TITLE
I want to check my xDAI donations on blockscout

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-2#756]
I'm checking up on my donations on my account, If i click the link to view a donation transaction I made on xDAI it takes me to the etherscan.io page when it should take me to blockscout. 

![image](https://user-images.githubusercontent.com/67759413/114073133-efb04d80-9870-11eb-8f5f-284858eacf33.png)

**Comment by laurenluz** [comment]
This is still going to etherscan @MerlinEgalite 
![image](https://user-images.githubusercontent.com/75490971/114912887-c5650f80-9ddd-11eb-9fc2-b16448bc3633.png)

**Comment by MerlinEgalite** [comment]
Did you tried on staging? 
It works on staging for me 😶

**Comment by laurenluz** [comment]
I'm on staging!
![image](https://user-images.githubusercontent.com/75490971/115064401-1c381b00-9eaa-11eb-9aad-3ffa35004663.png)
![image](https://user-images.githubusercontent.com/75490971/115064446-29550a00-9eaa-11eb-938d-8cb6b8d9e9a5.png)

**Comment by divine-comedian** [comment]
looks to be working - clicking the show transaction link from `my donations` will take me correctly to etherscan or blockscout depending if it was made on mainnet or xdai.
![image](https://user-images.githubusercontent.com/67759413/117464805-048b0a00-af1f-11eb-82b6-0def14737309.png)

![image](https://user-images.githubusercontent.com/67759413/117464916-1ff61500-af1f-11eb-9dd7-5b7554c85f9d.png)

nice work!
