### ISSUE TITLE
Update "About Us / Team" Section of Giveth.io

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-2#772]
It would be great if this page had a more accurate representation of our Team...

Delete Ben
Delete Bryan (?)
Add Ashley (Community Management)
Add Forest (Project Management)
Change Lauren Title (Communications)
Add Merlin (?)

Re-order contributors... either Alphabetical or According to Seniority

Also perhaps it makes sense to have the TRACE team on TRACE, and the giveth.io team on giveth.io?
Or include the whole team on both? Or Just change Amin's title to like... "Development Consult" or "dApp Development Bridge"

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/707cde4e-3636-4ede-8386-8028a17ccf91)

**Comment by geleeroyale** [comment]
I think we came to the agreement to not delete people from the team as they all had valid contributions - we could deprecate their role to *something something contributor* tho
