### ISSUE TITLE
The statement "You only are able to see the MetaMask login option if you have MetaMask installed" is false

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-2#774]
I've heard this so many times in our calls... That you should only be able to see the "login with MetaMask" option if you have a MetaMask browser extension, but I just tested it and it's not true.

I tested on Firefox and Chrome and on giveth.io and staging. It always gives me the MetaMask option and when I click it it opens up a new tab so that I can install the browser extension.  

So the question is: Should we give non metamask users the option to login w metamask (install it etc.)? Or do we want to remove that option?

I honestly think we should leave the option available but change the UI for login, as per #773 but then let it be known that Metamask is still always an option

@mateodaza @markoprljic @GriffGreen 

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/5a1eb480-29ac-4985-8d54-adb200ce65ea)

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/25962222-d724-485f-8f9f-951c59c0ca14)

**Comment by laurenluz** [comment]
there's already an issue for this: #655

**Comment by mateodaza** [comment]
happens that I forgot to add that with the new design haha, thanks for noticing

**Comment by markoprljic** [comment]
@mateodaza Please see my last update and comment in this issue https://github.com/Giveth/giveth-2/issues/655#issuecomment-820155130
