### ISSUE TITLE
Typo in Banner on Giveth.io homepage prompting users to use xDAI network, network spelled "netwok"

### ISSUE THREAD

**Issue by hannahjojo** [Giveth/giveth-2#778]
## 📋 Anything to add?
See screenshot. The blue/purple banner on the top spells network as "netwok" 
<img width="1305" alt="Screen Shot 2021-04-14 at 11 06 23 PM" src="https://user-images.githubusercontent.com/82562727/114816819-2d800b00-9d76-11eb-8592-f914d0680d21.png">

## ⏰ Urgency/Deadline/Blockers?
Somewhat urgent? 

## ❓ Why is it important?
So Giveth appears reliable and professional :-)

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by divine-comedian** [comment]
Spelling is fixed. Looks to be resolved. 
On staging with clean cache and cookies.
![image](https://user-images.githubusercontent.com/67759413/117469982-4c606000-af24-11eb-8f79-83ef1d607d06.png)
