### ISSUE TITLE
As a donor, I want to be able to change my donation wallet when using xdai chain

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-2#791]
This is already a feature when donating and logged in via metamask on mainnet
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/eaead2e9-4ddb-4185-9aef-fb31c3c53f9e)

but it would be nice if it were also possible on xdai. right now, when logged in w xdai, it looked like this:
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/a0b18216-11ab-4230-af40-c6cba89b658c)

@MerlinEgalite

**Comment by MerlinEgalite** [comment]
@mateodaza is there a reason why on xDAI this is not shown?

**Comment by divine-comedian** [comment]
on xdai I'm logged in with metamask and still not seeing any option to use another wallet. 

![image](https://user-images.githubusercontent.com/67759413/117468009-44072580-af22-11eb-9194-401bf4a8d6ca.png)
@MerlinEgalite 
are there any updates for this issue that testers should know about?
