### ISSUE TITLE
As a non logged in donor, I want to be able to donate (does not allow me to select or change a wallet, says "insufficient funds")

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-2#793]
Testing on live with brave private browser. There is no option below "donate" to change wallet, and when I click donate, rather than allowing me to choose a wallet, it says "insufficient funds"

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/00507d5b-01f4-4716-afe8-cc9b873b454e)

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/3295d265-fdc0-46b2-934c-4ed783c8fccf)

**Comment by mateodaza** [comment]
ok this one is urgent, will check now

**Comment by mateodaza** [comment]
It should be working soon, site is building :)
