### ISSUE TITLE
Beyond Tor.us wallets

### ISSUE THREAD

**Issue by jamespfarrell** [Giveth/giveth-2#80]
I think it would be better for us to be able to set up mult-sig wallets for projects, and I think that Gnosis safe is a strong candidate.

![image.png](https://images.zenhubusercontent.com/5807a7a095e42b6c5baabbd3/ea528348-4c6f-4800-887a-f9dea89c6bfe)

https://walletconnect.org/

**Comment by geleeroyale** [comment]
This has been implemented for donations. Not for handling the account (yet)
