### ISSUE TITLE
The pictures are not loading on the projects page

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-2#813]
It seems that the pictures are not loading on our main projects page on live...
It doesnt matter how long I wait.

![image.png](https://images.zenhubusercontent.com/5ffdde8079760c4346381d45/e006d53c-a0f4-4967-9083-07022b3067b5)

**Comment by geleeroyale** [comment]
I strongly suggest this was due to insufficient network bandwidth.

**Comment by divine-comedian** [comment]
+1 I'm still encountering this issue on Giveth.io LIVE. 

I find that every time I refresh the page more photos begin to show up

**Comment by WhyldWanderer** [comment]
This issue was fixed in the last sprint
