### ISSUE TITLE
It takes a lot of time to load the project owner name on the Project single page

### ISSUE THREAD

**Issue by markoprljic** [Giveth/giveth-2#817]
## 📋 Anything to add?

It takes about 10s or more to load the project owner/creator username. 
![Image 2021-04-27 at 3.21.25 pm.jpg](https://images.zenhubusercontent.com/5cc090818b624e26c3734d75/a00874a1-40ef-4f22-a5b0-aa7949b56777)

**Comment by laurenluz** [comment]
seems to be loading quickly now, I think this is resolved w next migration
