### ISSUE TITLE
Add a link to the Etherscan transaction 

### ISSUE THREAD

**Issue by positonic** [Giveth/giveth-2#823]
![image.png](https://images.zenhubusercontent.com/5807a7a095e42b6c5baabbd3/104b8740-27b1-434d-adae-9a211285b797)

**Comment by positonic** [comment]
@markoprljic not sure if you have redesigns done for these pages and / or if it includes this?

**Comment by markoprljic** [comment]
@jamespfarrell I mocked it up in My Account under My Donations, you can grab it there.

![Image 2021-05-03 at 3 51 04 pm](https://user-images.githubusercontent.com/5704285/116884806-7580a800-ac27-11eb-80ce-4f1d98762f69.jpg)

Figma source https://www.figma.com/file/FBqHg0UfeuaIueDEZG0tBS/Giveth.io?node-id=2673%3A0
