### ISSUE TITLE
Remove character limit on Project descriptions

### ISSUE THREAD

**Issue by markoprljic** [Giveth/giveth-2#825]
## 📋 Anything to add?
Few people reported that the character limit was a constraint and they abandoned the site after failed to create a project. 
Please remove the char limit on the Project description field.

**Comment by markoprljic** [comment]
Assigned you @jamespfarrell but if you think @mateodaza or @MerlinEgalite can/should do it please re-asign. Thanks.

**Comment by laurenluz** [comment]
related to #818

**Comment by MerlinEgalite** [comment]
@mateodaza did the change it's on the giveth-next but it seems it's not on staging yet

**Comment by mateodaza** [comment]
> @mateodaza did the change it's on the giveth-next but it seems it's not on staging yet

That's right, coming along with the rich text fix
