### ISSUE TITLE
Fix Safari issue due to Testing

### ISSUE THREAD

**Issue by MerlinEgalite** [Giveth/giveth-2#832]
![unknown.png](https://images.zenhubusercontent.com/5fdb9e1e84ca2e9f04757a4a/d0f80b1a-120d-43eb-9310-85e6d40a362a)

**Comment by laurenluz** [comment]
@MerlinEgalite is this done? can we close? or move to the next board?

**Comment by MerlinEgalite** [comment]
Yes
