### ISSUE TITLE
Create What's Dappened Medium Post #3

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-2#835]
Part of our series of dev update transparency posts for giveth.io

**Comment by laurenluz** [comment]
@jamespfarrell can you pull some of these metrics like the ones in https://github.com/Giveth/giveth-planning/issues/167  from the database for me so I can add them to the update post? 

number of donations
value of donations
average donation amount 

...for mainnet and xdai

**Comment by laurenluz** [comment]
@divine-comedian @WhyldWanderer @ForestSoleil @Danibelle - can one of your fine people please do QA. Assign yourself and comment if you're taking it on ;)

https://docs.google.com/document/d/1KbjJN0JX9AeCxKcDRaXRmxRkQnUuz5A61LqDmPSc1so/edit?usp=sharing

thanks @mateodaza for your technical 👀

**Comment by WhyldWanderer** [comment]
Looks great Lauren! I made few adjustments in the document.

**Comment by laurenluz** [comment]
https://medium.com/giveth/what-dappened-april-21-may-5-f918958e403e
