### ISSUE TITLE
Donate - Crypto

### ISSUE THREAD

**Issue by willyogo** [Giveth/giveth-2#84]
![Donate to Project  - 4](https://user-images.githubusercontent.com/26232238/90431139-cf374700-e085-11ea-984b-8a63dbfd8f7e.png)

As a user, I want to see the ETH address for a project so I can donate from an external wallet.

AC:
1. When a user clicks the ‘Donate’ CTA for a project they see this donation screen with the project’s ETH address and QR code
2. When a user clicks ‘copy address’ the address is copied clipboard
3. When a user taps an icon to share on social media, a new window to share on that social media platform is opened with the following copy pre-populated: (copy coming soon)
4. Donate screen looks good and works on all screen sizes
5. If a user clicks 'back' they are returned to the previous screen

**Comment by mateodaza** [comment]
I'm working on this from this [branch](https://github.com/Giveth/giveth-2/tree/dev/donate-with-crypto-flow) Also left a PR on [Impact Graph repo](https://github.com/topiahq/impact-graph/pull/9) so we can fetch a specific project given the ID. 
It's needed to be in there so we can close this issue, in particular to be able to retrieve all the project's info ( specially the wallet address )

**Comment by mateodaza** [comment]
#98
