### ISSUE TITLE
All my projects are gone ?

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-2#844]
Testing on staging in brave

I had 3 projects, signed in on staging... I edited one, the edit didn't stick, then I went to view my projects and all projects appear to be gone now

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/24bb8c46-c515-401a-a19a-0d038a84fd6f)

**Comment by mateodaza** [comment]
https://serve.giveth.io/graphql is down

**Comment by positonic** [comment]
Likely an issue with graphql being down, closing and keeping an eye out...\
![image.png](https://images.zenhubusercontent.com/5807a7a095e42b6c5baabbd3/807a881c-fe3a-40d0-bc44-ac76113e2aed)
