### ISSUE TITLE
Project "description too large" deletes all my info :( :( :( also it wasn't THAT large

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-2#846]
Testing on staging... I made a project with 1 photo (5.8 MB), 1 embedded video and just a very short amount of test (played with some formatting).

I clicked "next" and got the popup "description too large" (was it really too large?) and all my edits were completely deleted.

1. what is the limit on size for project descriptions? this should be made know to the user somewhere.
2. Content shouldn't be deleted when the user tries to submit a project with too large a description

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/2706bb33-e3ef-49a8-a7d0-5510b20696e9)

**Comment by mateodaza** [comment]
This should be working now

**Comment by laurenluz** [comment]
is there a limit to project description? I just make a project with a ton of photos and it worked super fine, but I'm wondering if maybe there's a disadvantage to having unlimited length/size.

https://next.giveth.io/project/how-many-photos-is-too-many-photos
