### ISSUE TITLE
successful donation page links to wrong block explorer

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-2#852]
## 📋 Anything to add?

I just successfully made a donation in xdai to a project, I'm on final page showing my successful donation and the link to view my transaction for the donation takes me to etherscan.io. My donation was in xdai so it should link me to my transaction on blockscout. 

Discovered it on LIVE and tested it on staging
brave browser
![image](https://user-images.githubusercontent.com/67759413/118146002-2d5a4600-b3dc-11eb-8980-971671adab3f.png)

**Comment by MerlinEgalite** [comment]
I guess this is because the changes I made where on the giveth-2 repo and not forked on giveth-next so I'll need to redo the changes... 😅

**Comment by mateodaza** [comment]
Oh no I'm sorry @MerlinEgalite maybe I missed that one while cherry picking 😬

I can check it out if you haven't, I also see there's a flex issue on the links

**Comment by MerlinEgalite** [comment]
No problem @mateodaza !

**Comment by MerlinEgalite** [comment]
Oh i get it, I think I've fixed on the donation list but not here i'll check!
