### ISSUE TITLE
user projects not showing up on their profile page

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-2#854]
Testing on next.giveth clean cache and cookies. 

I click on the author of a project and it takes me to their profile page and it says they don't have any projects.. which is impossible because I got to their profile via the link on their project.. 

![image.png](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/994f55e1-882f-4554-b3e4-cfae649596a0)

--- 
![image.png](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/a3f476e0-8d08-491f-b994-474f13266533)

--- 

My own projects however show in my profile page.. but some of the images are missing now..

![image](https://user-images.githubusercontent.com/67759413/118279874-9e136800-b499-11eb-80d9-a1767df22a5d.png)

**Comment by mateodaza** [comment]
This is fixed now
