### ISSUE TITLE
create project final confirmation page buttons look squished and text is mis-aligned

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-2#856]
Maybe this will change with the updated project creation flow but the start raising funds button is squished right against the bottom of the window, it should have a bit of a margin on it so it doesn't sit right on the bottom of the page. 

Also the text inside the small bullets for the project categories looks a bit funny, the text is too thin and is not centered in the middle of the 'bullet' or buttons..
![image.png](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/13c3e1d7-f833-4c26-9fd5-d080a8ef3ae4)

**Comment by laurenluz** [comment]
seems fixed on live

![image](https://user-images.githubusercontent.com/75490971/121409172-6a9fee00-c91e-11eb-840f-778a9b0a2f09.png)
