### ISSUE TITLE
I broke something but I have no link to open an issue on the page.

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-2#858]
I broke something when making a project, my connection might have timed out or something but anyway.. 

the page itself is kind of blank.. currently none of the text on this page offers me a direct link to open an issue to report the problem.

![image.png](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/30604f50-12d3-4133-af86-1c24ca2052f0)

**Comment by mateodaza** [comment]
I added a link to github when you click on "Please report an issue" - I think you had a timeout for some reason, can't replicate it
