### ISSUE TITLE
After creating a project, I get "An Unexpected Error Has Occurred" but the project is added fine

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-2#861]
I hit "start raising funds" got "setting everything up" and then "an unexpected error has occurred" on a white page.

Testing on next with a clean cache

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/91d297af-1659-482e-9604-b9907c580ff1)

**Comment by divine-comedian** [comment]
resolved with duplicate issue #874
