### ISSUE TITLE
Edits to Projects not being saved - EDIT: edits to projects take ~5 min to show up

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-2#862]
A user also reported this error from Live in issue #819

I'm testing on Next with Brave and a clean cache

Edited my project by adding text:
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/3ba6179c-e700-4e10-92f3-2a6e07dee2f8)

It confirmed that edits were "Saved" but when I went to view the project the edits didn't show up:

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/54457a68-9476-462b-8be4-68bccd2cdbdc)

**Comment by laurenluz** [comment]
seems to be working now on next!

![image](https://user-images.githubusercontent.com/75490971/118542320-184d2200-b710-11eb-875d-77150e2f2971.png)

![image](https://user-images.githubusercontent.com/75490971/118542349-200cc680-b710-11eb-9a3a-bb60aeb7b001.png)

**Comment by laurenluz** [comment]
also my previous edits on the other projects are now showing up too

nice job @mateodaza 

![image](https://user-images.githubusercontent.com/75490971/118542496-521e2880-b710-11eb-9053-66995866e143.png)

**Comment by laurenluz** [comment]
oh WAIT... I just tried to update my photo and it didn't stick.

what I saved: 
![image](https://user-images.githubusercontent.com/75490971/118545827-5ea48000-b714-11eb-9f5c-f99dc20e2e73.png)

what it was after the fact:
![image](https://user-images.githubusercontent.com/75490971/118545861-695f1500-b714-11eb-99be-79f376ef24d1.png)

**Comment by mateodaza** [comment]
Thanks for this feedback, will take a look

**Comment by laurenluz** [comment]
I just tried editing my project description again and this time the edits didn't show up in the project page... but when I went to re-edit the edits showed up there in the text field...

it looks like they're not being saved properly... or perhaps there is a delay until they show up on the frontend?

**Comment by laurenluz** [comment]
lo and behold. the update showed up when I went back to check 5 or so minutes later

**Comment by mateodaza** [comment]
not sure about the delay on showing the update, will take a look on that and maybe remove all intent on caching the info there - please also confirm if the edition on project image works now

**Comment by laurenluz** [comment]
update the image and it worked perfect!

then I edited my project description and it also worked perfectly without delay
