### ISSUE TITLE
Search bar not working correctly for projects

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-2#863]
I just made a project called "mangos for everyone" and can't find it by searching the projects page... even though it shows up under "my projects"

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/0f18011a-19e1-44ab-abc9-b5f8a9fbb7e2)

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/19295580-8701-43bc-a83e-4be46db46ea2)

**Comment by mateodaza** [comment]
can you try again and see if it still happens? I'm not able to replicate

**Comment by laurenluz** [comment]
it seems to be working ok now. I thought maybe it was because the project was brand new, so I made a new project and searched right away, but it comes up just fine...

![image](https://user-images.githubusercontent.com/75490971/118695572-95d56880-b7ca-11eb-8ff9-ff6ea0538eda.png)
