### ISSUE TITLE
Long load time when I click "Show more projects" on the home page https://next.giveth.io/projects

### ISSUE THREAD

**Issue by ForestSoleil** [Giveth/giveth-2#865]
## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by mateodaza** [comment]
can you try again and let me know if you still feel it slow?

**Comment by ForestSoleil** [comment]
Does not feel slow anymore. In fact, "Show more projects" is gone and instead I can continously scroll until In reach the end of the page. Thanks Mateo! (& sorry for my delayed response - I was locked out of GitHub for the past week or so due to 2fa sending to my old phone that wasn't turning on....until signing and praying to it today worked haha back in!)
