### ISSUE TITLE
xdai logos are not showing up... broken links?

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-2#871]
![Screen Shot 2021-05-19 at 8 38 04 AM](https://user-images.githubusercontent.com/14945613/118841893-02369180-b8c9-11eb-8e05-553af3cb9887.png)

![Screen Shot 2021-05-19 at 8 45 25 AM](https://user-images.githubusercontent.com/14945613/118844042-eb913a00-b8ca-11eb-9984-600fa002b3e2.png)

on the donate page: https://next.giveth.io/donate/giveth-2021:-retreat-to-the-future

**Comment by mateodaza** [comment]
I merged some work from @MerlinEgalite related to this, it should be showing now
