### ISSUE TITLE
The Twitter auto text is a little aggressive and missing our twitter handle :-D

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-2#872]
![Screen Shot 2021-05-19 at 8 46 49 AM](https://user-images.githubusercontent.com/14945613/118843369-470ef800-b8ca-11eb-96a7-0c01dcc20a83.png)

Maybe it could say:
------
Check out <name> on @Givethio 

<link>
------
And then they can add their own flavor if they want

**Comment by mateodaza** [comment]
Gotcha!

**Comment by divine-comedian** [comment]
Brave Browser clean cache and cookies
`next.giveth`

sharing a project on twitter looks to be updated to griff's suggestion.
![image](https://user-images.githubusercontent.com/67759413/119270366-55129080-bbca-11eb-89ac-10d38b70c0a8.png)

great work!
