### ISSUE TITLE
When creating a project, I get a blank screen upon submitting

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-2#874]
Testing on staging with chrome and metamask

After i complete project creation and press submit. I get a blank screen
![image.png](https://images.zenhubusercontent.com/5ffdde8079760c4346381d45/2035ff66-3811-46be-98e4-b3ed77e153e8)

![image.png](https://images.zenhubusercontent.com/5ffdde8079760c4346381d45/55994ba3-44c6-4e9e-9e99-0070b0e865f8)

Then I press the back button in my browser and it takes me to the account page... 
![image.png](https://images.zenhubusercontent.com/5ffdde8079760c4346381d45/09992fc7-ba1c-4954-b16d-7ec32186922e)

When I click my projects on the side it shows that my project was successfully added
![image.png](https://images.zenhubusercontent.com/5ffdde8079760c4346381d45/d61db838-f67e-4f62-84d5-5d9559ab670e)

**Comment by mateodaza** [comment]
Can you please do testing on http://next.giveth.io/ - staging.giveth.io is out of date

**Comment by WhyldWanderer** [comment]
Okay.. I was testing on next.giveth.io chrome and metamask with the same steps as above

After submitting my project i get "Cannot read property 'getAttribute' of undefined"

![image.png](https://images.zenhubusercontent.com/5ffdde8079760c4346381d45/10732fc9-c5f6-4b64-9115-df7e72dcc8dd)

When I press back in my browser, it again brings me to the "My Account" page

![image.png](https://images.zenhubusercontent.com/5ffdde8079760c4346381d45/b5e38523-4bb0-4037-af98-e0b926266f57)

On the side, i can see that i have a project 'My Projects (1) 
![image.png](https://images.zenhubusercontent.com/5ffdde8079760c4346381d45/abe1621a-4309-4f5d-bbc2-6e5d87422e40)

But when I click the link, I get this

![image.png](https://images.zenhubusercontent.com/5ffdde8079760c4346381d45/819459cf-0f9e-4a8a-9ec0-97b5521f2b1d)

Here is the console view:
![image.png](https://images.zenhubusercontent.com/5ffdde8079760c4346381d45/490e3af6-7616-4729-bde2-017be45aae99)
![image.png](https://images.zenhubusercontent.com/5ffdde8079760c4346381d45/daf1d3cd-ffef-4fe4-b134-be76dfbc319f)
![image.png](https://images.zenhubusercontent.com/5ffdde8079760c4346381d45/59b150ae-7199-4cae-a6f9-258026f74f01)
![image.png](https://images.zenhubusercontent.com/5ffdde8079760c4346381d45/d35669ce-91a2-4efd-bac1-a8be89fb2f7d)

**Comment by mateodaza** [comment]
Checking on it! Thanksss

**Comment by divine-comedian** [comment]
testing on `next.giveth`
brave browser clean cache and cookies. 

successfully made project with MM
![image](https://user-images.githubusercontent.com/67759413/119697884-ab780d00-be1e-11eb-9c29-9a4f0a9b4972.png)

my heckn project shows up in 'my projects' list

![image](https://user-images.githubusercontent.com/67759413/119698011-cf3b5300-be1e-11eb-99b4-7a2ad0270da0.png)

issue looks to be resolved.
