### ISSUE TITLE
Replace 'Learn More' with 'View Project' on 'My Projects' page in 'My Accoount'

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-2#876]
Testing on next.giveth.io with chrome and metamask

As a maker, it is a bit confusing when the link under my own projects in my account says "learn more"

![image.png](https://images.zenhubusercontent.com/5ffdde8079760c4346381d45/9fa6d626-338b-4296-be64-155fab42719b)

Can we change this to say 'View Project' instead when its being viewed on this page?

**Comment by divine-comedian** [comment]
Brave Browser, clean cache and cookies
`next.giveth`
the text has been updated refletcing the proposed update from ashley
![image](https://user-images.githubusercontent.com/67759413/119270484-db2ed700-bbca-11eb-8a10-08f13c79d63a.png)
