### ISSUE TITLE
Error screen while navigating within 'My Account' section

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-2#878]
Testing on next.giveth.io in chrome with metamask

I was editing my project and pressed the button to go back to "my projects'
![image.png](https://images.zenhubusercontent.com/5ffdde8079760c4346381d45/cbab3b48-9e78-4a7e-8a06-6fcaf8f94475)

But I am getting an error screen after pressing the button
![image.png](https://images.zenhubusercontent.com/5ffdde8079760c4346381d45/162937e6-7903-4f01-b6ca-3da4943c4242)

Here is the console view..
![image.png](https://images.zenhubusercontent.com/5ffdde8079760c4346381d45/cfa9e827-a216-4204-af71-53782cfd4441)
![image.png](https://images.zenhubusercontent.com/5ffdde8079760c4346381d45/814cefea-003b-4403-a646-b056c540696e)

If I refresh the page in my browser, it loads the "My Projects' page correctly

**Comment by divine-comedian** [comment]
testing on next.giveth
clean cache and cookies on brave
signed in with MM i go into edit my project, I change some text or don't change anything and I hit the 'back' button. tried the same process with several projects.
**goes back to my projects page with no error.**
