### ISSUE TITLE
Anonymous donations not showing up on project page

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-2#883]
Testing on next.giveth.io with chrome and metamask

When I make an anonymous donation, it does not show up under donations on the project page but the transaction was completed in my wallet.
![image](https://user-images.githubusercontent.com/74267818/119031845-c521dc00-b968-11eb-83f0-ceba6d896136.png)

Transaction: https://ropsten.etherscan.io/tx/0xbc6f42baa76b6aea9d97196e1df88e9e5f115c49e97b04746014d7588798315a

**Comment by mateodaza** [comment]
I answered this in this other [issue](https://github.com/Giveth/giveth-2/issues/882#issuecomment-845526287)  instead, my bad haha

Nop, nevermind - still WIP

EDIT: Now it's working! haha

**Comment by divine-comedian** [comment]
next.giveth
brave browser, clean cache and cookies
just made an anonymous donation to a project.
it went through and shows up on the project page. 
looks to be resolved!
![image](https://user-images.githubusercontent.com/67759413/119555546-fbe26280-bd6b-11eb-9154-78a8f8459f57.png)
