### ISSUE TITLE
Having Issues loading photo and text edits

### ISSUE THREAD

**Issue by mellymails** [Giveth/giveth-2#886]
## 📋 Anything to add?
Hi, we have been trying to upload our project and the photo keeps showing our initial selection. We have changed it and uploaded the second photo, however, it only shows the old one when we click "learn more". Also, the language keeps showing the old edits and not the updated language. In a nutshell, it seems like the issue is with updating the project to our real-time push. It shows correctly in the edit screen but not the public-facing version.

Ex: "The social fabric of W. Oakland being the focus and what we prioritize in this space. Start small, start local and ."

We have corrected this several times but the old photo and language correction is not sticking. 

## ⏰ Urgency/Deadline/Blockers?
We have some issues with showing the kids and cannot spread the word until it corrected. We have finally freed up our time without the kids and community day to day for two weeks. Any help would go a long way in helping us get set up.

## ❓ Why is it important?
Because we want to push it and get our first project off the ground to meet the needs of the families we intend to support. (that urgently need it)

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by mateodaza** [comment]
Hey thanks for reaching! We'll be making a big update to the app where this will be solved  (more likely in a day) I'll get back to you when it's ready!!
Also sorry for the inconvenience, we have had many other issues like this from other users

**Comment by mateodaza** [comment]
You can check this out again! sorry for the delay
