### ISSUE TITLE
Proposed changes to Discord

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-2#887]
While composing a user guide for our discord server in the docs, I realized that we could take this opportunity to refresh and update the discord server with a few small things that would make it more new user friendly as well as a bit more engaging.

Here is a link to the guide I am working on: https://hackmd.io/8NVdNYUhTUOOwSOpuFdG9w
(It is still a work in progress... please feel free to leave comments or suggestions)

I would like to add channel descriptions in the server and allow for users to assign themselves a role as well as add a welcome message that guides newcomers. Willy was generous enough to grant me Admin rights so I can make the changes but I would like to share my ideas here for feedback or objections before making any changes.

The current flow:
When new users come to our server they see this pop-up
![image](https://user-images.githubusercontent.com/74267818/119553235-af415c00-bd58-11eb-8d68-2a301e660c11.png)

I propose to change it to this.
![image](https://user-images.githubusercontent.com/74267818/119556084-d2213f80-bd5b-11eb-8cc3-3b28d0b745c4.png)

Our welcome channel is currently the landing channel and I would like to add a message here and make it a read only channel.
Proposed welcome message: https://hackmd.io/Lb0bEh_cQvy6iFMGzyqvwA?both
Because the welcome channel would be read only, this means that the general channel should be available to new users in case they are having trouble getting roles or solving captchas.

Below the welcome message, they would be able to choose a role for themselves by reacting with an emoji.
They can choose between 💝 Giver and 🦄 Maker or even choose both. 
Can you think of any more roles we would like to offer for users? maybe theyre not a donor or project owner but they would like to contribute to the community... maybe partner? or something? idk what do you think?
This role reaction would be performed by carl.gg and is simple to set up. It would look something like this:
![image](https://user-images.githubusercontent.com/74267818/119561239-2a5b4000-bd62-11eb-8add-f9a2458d2181.png)

I propose to add channel descriptions to each channel that reflect what is written in the guide above.

I propose to make the following channel name updates:
#giveth-1-dev --->  #givethtrace-dev
#giveth-2-dev --->  #givethio-dev
#tokenomics --->   #giv-economy
and to move #fundraising to the general section below communications rather than the buidl section.

@willyogo @geleeroyale What do you think?

**Comment by geleeroyale** [comment]
This looks great - thanks for getting my opinion!

**Comment by willyogo** [comment]
My only concern is that this looks too good! (jk 😉 )

This is so awesome, thank you for taking initiative @WhyldWanderer ❤️
