### ISSUE TITLE
on UI https://giveth.io/projects the fee tx cost renderx for ETH even when you use xDAI

### ISSUE THREAD

**Issue by lebed2045** [Giveth/giveth-2#913]
## 📋 Anything to add?
when you donate to projects on xDAI chain https://giveth.io/projects - the fee renders as it Ethereum
![image](https://user-images.githubusercontent.com/1270800/147417048-061feefd-0633-4db2-8877-bc48c5763578.png)

## ⏰ Urgency/Deadline/Blockers?
not urgent

## ❓ Why is it important?
people might assume that fee is expensive and change decision to donate. But in reality it's super cheap.

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by GriffGreen** [comment]
Closing in favor of the one in the Next repo
